### ISSUE TITLE
[Feature]: add possibility to use Bearer Token 

### ISSUE THREAD

**Issue by F-PMOR** [netbox-community/ansible_modules#1014]
### NetBox version

v3.4.7

### Feature type

Change to existing Plugin

### Proposed functionality

# Add the possibility to change the Authorization token type.
I propose to be able to change the Authorization token type from "Token", to anything else, for exemple : "Bearer" (that is used in Oauth2.)

# Change to do

__in the file : nb_inventory.py__
Line : 2016. 
```
       if token:
            self.headers.update({"Authorization": "Token %s" % token})
```
changed to : 

```
       if token:
            self.headers.update({"Authorization": "%s" % token})
```

And in the Netbox inventory file. We just have to put the token type to use.
```
api_endpoint: https://url_to_netbox
token: Bearer token_information
```

## but could be changed to something more convenient
Test could be made to check if the token type is provided, if not, it 's automatically used as "Token", however, we use the token type given.

### Use case

# information

This simple change make possible to change the type of token send to proxy/netbox in order to use Oauth2 for exemple. Tests done and fonctionnal.

### External dependencies

No dependencies.

**Comment by rodvand** [comment]
Related PR: #1023
