### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by ignatenkobrain** [netbox-community/ansible_modules#102]
Hello,

the LICENSE and galaxy.yml says `MIT`, but the note on top of the code says `GPL-3.0+`...

Which one is correct? Also, I would appreciate if you could fix this and publish new version to a galaxy.

**Comment by FragmentedPacket** [comment]
@ignatenkobrain I opened a PR for the changes. Does this answer your question? I will hopefully have a new version pushed up no later than this weekend.
