### ISSUE TITLE
[Feature]: Add support for virtual disks to nb_inventory plugin

### ISSUE THREAD

**Issue by eu-tomas** [netbox-community/ansible_modules#1141]
### NetBox version

v3.7.0

### Feature type

Change to existing Plugin

### Proposed functionality

NetBox 3.7.0 introduced the concept of Virtual Disks to model multiple disks assigned to a single Virtual Machine. 

When using the nb_inventory plugin it does not yet recognize this relationship (or the fact that there are any assigned virtual disks via the virtual_disk_count attribute). 

This functionality works pretty much the same as the virtual network interfaces, and it would make sense for the machine's virtual disks (preferably including their custom fields) to also be an integrated part of the virtual machine inventory output when retrieving a VM via the nb_inventory plugin.

### Use case

Right now the nb_inventory plugin does not recognize the  virtual disks associated to a VM (or that there are any). This means that it requires explicitly querying the NetBox API for any Virtual Disks associated to the VM and using those, when it would make more sense to have them as a sub property of of the Virtual Machine object, just like the Interfaces are part of a VM.

As the virtual disk objects are fairly bare bones (vm, name, size, description, tags) and it is very likely everyone will customize it with custom fields, it might be helpful if the custom fields of the virtual disks could also be part of the output somehow.

**Comment by damo2929** [comment]
while at it please can we add modules to create viurtual disk from ansible in netbox so that the inventory can be updated with reality

**Comment by sc68cal** [comment]
I am 👍 on this, if someone pushes a PR implementing

**Comment by tkn2023** [comment]
When will this be implemented?

**Comment by sc68cal** [comment]
This is an open source project. It will be implemented when someone contributes it.
