### ISSUE TITLE
[Feature]:  Virtual Disk support feature added in v3.7

### ISSUE THREAD

**Issue by damo2929** [netbox-community/ansible_modules#1144]
### NetBox version

V3.7.0

### Feature type

New Module

### Proposed functionality

Add ansible module support for creating, updating and deleting VirtualDisk Model that was introduced in version 3.7

### Use case

will allow for ansible to audit a system and ensure all raw disks are in netbox,
will also allow for updating an exisiting disk if it's been changed in the hypervisor.
ensuring it has support for custom fields will also allow it have other options that are not currently supported by the model.

**Comment by damo2929** [comment]
closing duplicate

**Comment by bluikko** [comment]
Duplicate of which issue? A search with term "virtual" did not find it, could you add it as a reference please?
I could only find #1141 which completed and is about inventory only. Not the feature listed here.

**Comment by damo2929** [comment]
virtual disks have already been implemented in the collection hence me closing it.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
