### ISSUE TITLE
[Feature]: Add VPN Tunnels to nb_inventory

### ISSUE THREAD

**Issue by peterbaumert** [netbox-community/ansible_modules#1146]
### NetBox version

v3.7.0

### Feature type

Change to existing Module

### Proposed functionality

NetBox 3.7.0 introduced the concept of VPN Tunnels.

When using the nb_inventory plugin it does not yet recognize/display those.

### Use case

Automaticalls deploy VPNs based on netbox config.

**Comment by sc68cal** [comment]
I think an `nb_lookup` call for that information is more appropriate

**Comment by peterbaumert** [comment]
> I think an `nb_lookup` call for that information is more appropriate 

Okay sorry. I am still new to ansible and the combination with netbox :)
