### ISSUE TITLE
new feature for interface-connections support

### ISSUE THREAD

**Issue by tkspuk** [netbox-community/ansible_modules#115]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Any plans to support interface-connections model，many thanks

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by FragmentedPacket** [comment]
@tkspuk I think someone is currently working on this and is a duplicate issue.

Take a look at #116 and issue #91. If those meet this, you can close this issue and track the others. You can always comment on the others that you're interested in this or give it a thumbs up so people know they aren't the only ones to want this!

**Comment by tkspuk** [comment]
noted and Thanks，I will close this issue.
