### ISSUE TITLE
[Feature]: NetBox 3.7 VPN 

### ISSUE THREAD

**Issue by antoinekh** [netbox-community/ansible_modules#1156]
### NetBox version

v3.7.0

### Feature type

New Module

### Proposed functionality

Support for the new VPN Tunnels

### Use case

Configure VPN Tunnels

**Comment by sc68cal** [comment]
Duplicate of #1146

**Comment by sc68cal** [comment]
Actually #1149

**Comment by sc68cal** [comment]
Sorry, referenced issues were for support in the lookup plugin after pynetbox & netbox moved the api endpoint

**Comment by FloSch62** [comment]
The endpoints for the l2vpns and terminations in https://github.com/netbox-community/ansible_modules/blob/devel/plugins/lookup/nb_lookup.py#L209 needs also to be updated to the new endpoints

**Comment by richbibby** [comment]
happy to work on this one
