### ISSUE TITLE
Documentation: Publish docs to RTD

### ISSUE THREAD

**Issue by FragmentedPacket** [netbox-community/ansible_modules#118]
##### ISSUE TYPE

 - Documentation update

##### SUMMARY
Implement documentation for RTD (Auto documentation of Python docstrings, module documentation that looks like Ansible module documentation, contribution docs, changelog, etc.)

**Comment by gundalow** [comment]
We (Ansible) will provide this for you. We should have an update in the next month or so.

**Comment by FragmentedPacket** [comment]
Ok awesome! I will just close this issue for now and await the update.

**Comment by bluikko** [comment]
@gundalow Any updates? How would the documentation be provided?

**Comment by FragmentedPacket** [comment]
I'll be hopefully getting this done soon as I'm getting back from vacation, but docs (out of date most likely) can be found here: https://docs.ansible.com/ansible/2.10/collections/netbox/netbox/index.html#plugins-in-netbox-netbox

**Comment by gundalow** [comment]
Hi,
I believe https://docs.ansible.com/ansible/2.10/collections/netbox/netbox/index.html#plugins-in-netbox-netbox is correct as of the last time the `ansible` package was rebuilt.

So for `ansible-2.10.0 Alpha 8` https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible-2.10.0a8.deps#L58 `netbox.netbox: 0.3.1`
