### ISSUE TITLE
[Bug]: Poweroutlet is missing type iec-60320-c21

### ISSUE THREAD

**Issue by sapergus** [netbox-community/ansible_modules#1229]
### Ansible NetBox Collection version

v3.18

### Ansible version

```bash
ansible [core 2.16.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pergus/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/pergus/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### NetBox version

v3.7.3

### Python version

3.10

### Steps to Reproduce

Create a poweroutlet using  netbox.netbox.netbox_power_outlet that has the type set to iec-60320-c21.

### Expected Behavior

Since I read the value iec-60320-c21 from the same netbox instance that I use ansible against I expect ansible to create a poweroutlet of type iec-60320-c21.

It seems that  iec-60320-c21 has beed defined in netbox/dcim/choices.py since at least NetBox version 3.5.0.

### Observed Behavior

Ansible failes with this error message:
"msg": "value of type must be one of: iec-60320-c5, iec-60320-c7, iec-60320-c13, iec-60320-c15, iec-60320-c19, iec-60309-p-n-e-4h, iec-60309-p-n-e-6h, iec-60309-p-n-e-9h, iec-60309-2p-e-4h, iec-60309-2p-e-6h, iec-60309-2p-e-9h, iec-60309-3p-e-4h, iec-60309-3p-e-6h, iec-60309-3p-e-9h, iec-60309-3p-n-e-4h, iec-60309-3p-n-e-6h, iec-60309-3p-n-e-9h, nema-5-15r, nema-5-20r, nema-5-30r, nema-5-50r, nema-6-15r, nema-6-20r, nema-6-30r, nema-6-50r, nema-l5-15r, nema-l5-20r, nema-l5-30r, nema-l5-50r, nema-l6-20r, nema-l6-30r, nema-l6-50r, nema-l14-20r, nema-l14-30r, nema-l21-20r, nema-l21-30r, CS6360C, CS6364C, CS8164C, CS8264C, CS8364C, CS8464C, ita-e, ita-f, ita-g, ita-h, ita-i, ita-j, ita-k, ita-l, ita-m, ita-n, ita-o, hdot-cx, got: iec-60320-c21 found in data"

**Comment by sc68cal** [comment]
If you add it to https://github.com/netbox-community/ansible_modules/blob/devel/plugins/modules/netbox_power_outlet.py#L213 and create a PR i will approve
