### ISSUE TITLE
netbox_interface.py missing from collection

### ISSUE THREAD

**Issue by gundalow** [netbox-community/ansible_modules#124]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Hi,
`netbox_interface.py` was in ansible/ansible:devel though isn't included in this collection.

Should it be?

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by FragmentedPacket** [comment]
Yes. It was actually converted to `netbox_device_interface` to differentiate from the two endpoints that use interfaces: devices and virtual machines

There is also a `netbox_vm_interface` to handle the vm interfaces

**Comment by gundalow** [comment]
Thanks for the info (and quick response)

`netbox_interface` was added in Ansible 2.8, so we need to keep that file. At the moment this module is in the `community.general` collection. I wonder if it would make sense for it to be added to this collection.

**Comment by gundalow** [comment]
Currently `community.general` depends on `netbox.netbox`

**Comment by gundalow** [comment]
oh, also `plugins/inventory/netbox.py` is  community.general

I'd like to see plugins/inventory/netbox.py and netbox_interface moved into this collection.

**Comment by FragmentedPacket** [comment]
The inventory plugin has been moved into this collection. I did rename it to `nb_inventory` due to the fact that calling it looks really ugly and non-intuitive (`netbox.netbox.netbox`) and then we have the lookup plugin in here as well that would be found at `netbox.netbox.netbox` as well.

I'd rather not have the `netbox_interface` in this collection as it has outdated code and all the modules now make use of classes, etc. to prevent as much code duplication as necessary.

**Comment by gundalow** [comment]
OK,
I've added inventory/netbox to https://github.com/ansible-community/collection_migration/pull/479

My concern about leaving netbox_interface in community.general is that current users may not know about netbox.netbox (ie the docs aren't link)

It's OK for `netbox_interface` to be in `netbox.netbox` and marked as deprecated then deleted in the future.

**Comment by FragmentedPacket** [comment]
I will look into how to signify it is deprecated and get it added to this collection. We can keep this issue open and I'll get it closed once I get it merged into the repo.

Thanks for all the feedback!

**Comment by gundalow** [comment]
> I will look into how to signify it is deprecated and get it added to this collection. We can keep this issue open and I'll get it closed once I get it merged into the repo.
> 
> Thanks for all the feedback!

Thank you, given this, I've raised https://github.com/ansible-community/collection_migration/pull/496 

I realize there has been some back and forth with all of this while we've been learning. Thak you for your understanding.

**Comment by FragmentedPacket** [comment]
No problem! I appreciate you reaching out to figure everything out!

**Comment by bluikko** [comment]
I might be the only one with this opinion but I find it very cumbersome to have to always have two plays in Ansible for the VM/device API endpoints. How likely is it that there is a device and a VM with the same name?

**Comment by DouglasHeriot** [comment]
@bluikko It's not just about the namespace and id space - it's the Netbox API endpoints are separate for devices vs VMs. So even if the same module supported both devices and vms, it would need a parameter to specify if you're working with a device or vm.

**Comment by bluikko** [comment]
@DouglasHeriot I understand that - I'm just suggesting that the collection could make that decision, instead of the user. Anyways it seems I'm the only one who is bothered with this.
