### ISSUE TITLE
Collection listed as deprecated

### ISSUE THREAD

**Issue by gundalow** [netbox-community/ansible_modules#125]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Module question
 - Module creation help
 - Documentation update

##### SUMMARY
https://galaxy.ansible.com/netbox_community/ansible_modules

Says
> This item has been deprecated. We recommend that you take a look at one of these instead.

Do you know why
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by gundalow** [comment]
The setting is here
<img width="1153" alt="Screen Shot 2020-03-04 at 9 56 11 AM" src="https://user-images.githubusercontent.com/940557/75898824-87539900-5e32-11ea-8e50-307ca369bb8a.png">

**Comment by FragmentedPacket** [comment]
This was after our discussion on the naming. This Github repo is used by `netbox.netbox` now and figured I'd just deprecate `netbox_community.ansible_modules` to let users know.

Should I go about this another way?

**Comment by gundalow** [comment]
ah, I see
https://galaxy.ansible.com/netbox_community/ansible_modules and https://galaxy.ansible.com/netbox/netbox both point to this repo

Maybe an update (publish) to netbox_community/ansible_modules's README that links to https://galaxy.ansible.com/netbox/netbox ?

**Comment by gundalow** [comment]
Related: I've updated the namespace.collection name here https://github.com/ansible-community/collection_migration/pull/479

**Comment by FragmentedPacket** [comment]
Thanks for taking care of that.

I've pushed an updated version to the old namespace that shows it has moved to a new namespace.

https://galaxy.ansible.com/netbox_community/ansible_modules

I was wondering how to update the avatar for the Netbox namespace so it looks more professional. Do you know how to do that?

**Comment by gundalow** [comment]
> Thanks for taking care of that.
> 
> I've pushed an updated version to the old namespace that shows it has moved to a new namespace.
> 
> https://galaxy.ansible.com/netbox_community/ansible_modules

I wonder if the whole README should only contain a link to the new collection?
Either way, what you've done is an improvement over what we have today

> I was wondering how to update the avatar for the Netbox namespace so it looks more professional. Do you know how to do that?


https://galaxy.ansible.com/my-content/namespaces/19761 or if you don't have access to that let me know the URL of an image and I'll set it.

**Comment by FragmentedPacket** [comment]
Does the README look better now for the old collection?

**Comment by gundalow** [comment]
Perfect, thank you for the quick turn around on this.
