### ISSUE TITLE
[Feature]: netbox_cluster - Adds status field

### ISSUE THREAD

**Issue by lalgarvi-te** [netbox-community/ansible_modules#1275]
### NetBox version

v3.3.10

### Feature type

Change to existing Module

### Proposed functionality

Add the apparently missing field status to Cluster resources.
Choices:                                                                 
- planned | Planned
- staging | Staging
- active | Active
- decommissioning | Decommissioning
- offline | Offline

### Use case

To allow the operational status of Clusters to be changed via ansible.

**Comment by richbibby** [comment]
happy to work on this

**Comment by lalgarvi-te** [comment]
thank you :)
