### ISSUE TITLE
[Feature]: netbox_cluster_group - Adds description field

### ISSUE THREAD

**Issue by lalgarvi-te** [netbox-community/ansible_modules#1276]
### NetBox version

v3.3.10

### Feature type

Change to existing Module

### Proposed functionality

Add the apparently missing field description to Cluster Group resources as string.

### Use case

To add description to Cluster Groups.

**Comment by richbibby** [comment]
happy to work on this

**Comment by lalgarvi-te** [comment]
oh this one merged already too :) ticket can be closed? @richbibby @rodvand

**Comment by richbibby** [comment]
yes, @lalgarvi-te this one can be closed
