### ISSUE TITLE
[Feature]: netbox_location - Add facility field

### ISSUE THREAD

**Issue by lalgarvi-te** [netbox-community/ansible_modules#1280]
### NetBox version

v3.3.10

### Feature type

Change to existing Module

### Proposed functionality

Add the apparently missing field facility to Location resources.

### Use case

To add facility to Locations.

**Comment by richbibby** [comment]
picking this up also as related to #1279

**Comment by richbibby** [comment]
closing as completed by #1282

**Comment by lalgarvi-te** [comment]
again thanks :)
