### ISSUE TITLE
[Feature]: Netbox Location Module missing Status parameter

### ISSUE THREAD

**Issue by richwats** [netbox-community/ansible_modules#1291]
### NetBox version

v4.0.7

### Feature type

Change to existing Module

### Proposed functionality

The current netbox_location module is missing the status parameter option.   

### Use case

We use the status parameter to mark that objects are in planning rather than deployed.  Whilst we can edit the location(s) in the GUI I would prefer to set this in code.

**Comment by richbibby** [comment]
Hi. thanks for raising this issue. it is actually a duplicate of #1279 that has been resolved in PR #1282. so this functionality will be in the next release
