### ISSUE TITLE
New Module Netbox Virtual Chassis

### ISSUE THREAD

**Issue by nathbooth** [netbox-community/ansible_modules#137]
ISSUE TYPE

    Feature Idea

SUMMARY

 -  virtual-chassis

**Comment by nathbooth** [comment]
Currently WIP, will raise PR when complete

**Comment by toerb** [comment]
@FragmentedPacket: I am currently trying implementing this module but I got stuck.

virtual-chassis has one required field, called `master`.
But regarding the documentation it is not filterable by this field.
I don't see a good way to add this module without the option to filter after `master` or `master_id`.

I already tried by using the `q` filter but I did not succeed so far and it bloats up the code.
Do you have an idea on how to implement this modules correctly?

**Comment by FragmentedPacket** [comment]
Are your questions still valid after submitting the PR?

**Comment by toerb** [comment]
The PR is now using the method to filter by `q`. While this is not pretty I think it's currently the best way to filter for virtual-chassis in the NetBox API.

**Comment by FragmentedPacket** [comment]
Ok awesome. I will take the time and review it today. Thanks for your contributions!

**Comment by toerb** [comment]
@nathbooth: This feature request is implemented now. It is shipped in v0.3.0.
