### ISSUE TITLE
Discussion: ip-address key within Inventory plugin

### ISSUE THREAD

**Issue by FragmentedPacket** [netbox-community/ansible_modules#139]
##### ISSUE TYPE

 - Discussion

##### SUMMARY

Currently when the inventory fetches the IP addresses of interfaces, it puts them under the following variable name: `ip-addresses`.

This will be a breaking change if we were to move to `ip_addresses` instead which follows PEP styling.

I agree with changing it, but would like more feedback.

##### EXPECTED RESULTS

```
interface["ip_addresses"]
```

##### ACTUAL RESULTS

```
interface["ip-address"]
```

**Comment by karstenjakobsen** [comment]
`ip_addresses` would be preferable to `ip-address` - specialy when Ansible in general wants to use underscore

**Comment by DouglasHeriot** [comment]
I think given this project is still quite new and at v0.x, stability is not assumed yet. Changes like this to clean up should be encouraged.

If it breaks anyone's Ansible usage then they can continue to use the old version of this collection until either they update their Ansible config, or this project implements an option to go back to old behaviour. Is that a fair opinion?

**Comment by FragmentedPacket** [comment]
I think I'd rather make it a breaking changing than a toggled change, but I agree that they can stick to a different version.

I do need to get better about SemVer changes, so I will start with this and put it into 0.2.0 release so people can stay at 0.1.10 as some folks may allow patch upgrades in their requirement files.
