### ISSUE TITLE
Testing: Update netbox to 2.6, 2.7

### ISSUE THREAD

**Issue by DouglasHeriot** [netbox-community/ansible_modules#144]
Currently Travis runs tests against Netbox 2.5 and 2.6. As per the policy of supporting the latest 2 versions, this should be updated to 2.6 & 2.7

**Comment by FragmentedPacket** [comment]
I will try and take a look tonight. I may have to split out the tests for 2.6 and 2.7. Once 2.8 is released then they wouldn't have to have separate tests though.

**Comment by FragmentedPacket** [comment]
This has been implemented #160
