### ISSUE TITLE
Ansible Inventory API Token optional

### ISSUE THREAD

**Issue by martink2** [netbox-community/ansible_modules#177]
Observed Behaviour:
Currently the inventory requires a API token to query the API. Even if 
Netbox does not require a key for read-only access.

Expected Behaviour:
API token is an optional argument if the user needs to query for information not 
available without login.

**Comment by FragmentedPacket** [comment]
Do you mind providing an example of this?

The required setting in `configuration.py` and the URL?

**Comment by martink2** [comment]
the netbox ansible inventory currently requires a token like:

`netbox_token: 0123456789abcdef0123456789abcdef01234567`

In the Netbox default configuration read access is granted without 
logging in to Netbox itself. This also extends to api usage so in case 
of read only requests like the inventory is doing a user can use it 
without even having an account in our Netbox.

**Comment by FragmentedPacket** [comment]
I understand the issue, but I'm not able to see how to reproduce the behavior on my local NetBox instance. Any API call I get a `authentication` required error when CURLing so I'm trying to reproduce to where I can do API calls without any account so I can start testing how this will look with error handling, etc.

**Comment by martink2** [comment]
Sorry i misunderstood the question we have the following in the config:
`LOGIN_REQUIRED = False`
`EXEMPT_VIEW_PERMISSIONS = ['*']` 

with this i can get a api response for (no additional headers):

`curl https://netbox.xxxxx.de/api/dcim/sites/`

**Comment by FragmentedPacket** [comment]
Thank you! I will try and remove the requirement for it, and make sure it is passing any error back if a token is required for the NetBox instance.

**Comment by FragmentedPacket** [comment]
@martink2 Do you mind testing the submitted PR for this to see if it is working as intended for you?

**Comment by ThomasADavis** [comment]
wait, isn't this also true of the rest of the modules/lookup plugins?  If you have enabled anonymous read-only, they should also work for getting information.. just fail when you try to write stuff.

At least the lookup plugin should be that way.. it's read-only.

**Comment by FragmentedPacket** [comment]
You're correct. This makes sense for the lookup plugin as well

**Comment by martink2** [comment]
Hi sorry for the communication delay,  works like a charm. Thanks for that very quick help!
