### ISSUE TITLE
Inventory: Add regions grouping

### ISSUE THREAD

**Issue by DouglasHeriot** [netbox-community/ansible_modules#178]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Add regions as a group by option, as in pull request ansible/ansible#60642

The region groups should not contain hosts directly, but should contain other site groups.

**Comment by FragmentedPacket** [comment]
That was an oversight on my part so thanks for catching this.

**Comment by FragmentedPacket** [comment]
Closed via #155
