### ISSUE TITLE
Modules: Fix ansible-test sanity issues

### ISSUE THREAD

**Issue by DouglasHeriot** [netbox-community/ansible_modules#180]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

v2.9.7

##### SUMMARY

`ansible-test sanity` has a lot of useful checks. I'm adding this to travis in #155 however will leave `validate-modules` disabled as there's a lot of work to do there.

##### STEPS TO REPRODUCE

```
ansible-test sanity --requirements --python 3.6 --skip-test pep8
```
(Skipping pep8 as it returns different errors to `black`, and `black` does a better job as it can automatically fix the issues)

##### EXPECTED RESULTS

No errors

##### ACTUAL RESULTS

See this gist for the errors: (it's a long list)
https://gist.github.com/DouglasHeriot/4d7e48430afe656b017d72dcbbb8c06d

**Comment by FragmentedPacket** [comment]
I'll try and get these fixed over the weekend.

Thanks for all your hard work on this stuff!
