### ISSUE TITLE
netbox_inventory_items problems..

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/ansible_modules#187]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

###### Ansible:

2.9.x

###### Netbox:

2.7.x

###### Collection:

0.20.0

##### SUMMARY

There is two issues/features.

1) All items are marked 'Manual entry'.  The discovered field is not being set/passed in.
simple line one fix - add 'discovered=dict(required=False, type='bool', default=True),' and it now marks the inventory properly.

2) Search/updates only use 1 field - name - which can be not very unique (ie, what I have more than one identical devices?).  The field size is also limited, so trying to cram a unique name in can be difficult. fix:  add serial, and description to the query.

I'll generate a PR when I'm done breaking things.  :)

**Comment by FragmentedPacket** [comment]
Thanks for finding this stuff!

1. Just a note, from the API, it looks like discovered defaults to False so that would probably be the better default.

2. I'm open to adding `serial` to the allow query params, but description may or may not be unique so I'd leave that one out.

Thanks again!

**Comment by FragmentedPacket** [comment]
Fixed in #220
