### ISSUE TITLE
Inventory: group_by options for cluster, cluster_type and cluster_group

### ISSUE THREAD

**Issue by DouglasHeriot** [netbox-community/ansible_modules#188]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:

v2.9.7
###### Netbox:

v2.8.1
###### Collection:

v0.2.0
##### SUMMARY

VMs are part of a cluster. A cluster has a group and a type. In my Netbox instance, we use type to specify "vmware" or "aws" or "azure", etc.

I need Ansible groups to be able to target just vmware, or just aws.

I can use the `compose` option on the inventory to pull out the cluster name that currently isn't extracted, but the type and group is not there (not returned by Netbox api when listing VMs)

**Comment by DouglasHeriot** [comment]
I've implemented this on top of #155 with tests. I'll open a pull request once #155 is merged.

**Comment by FragmentedPacket** [comment]
Closed via #191
