### ISSUE TITLE
Inventory: Option to flatten config_context and custom_fields to include vars directly on host

### ISSUE THREAD

**Issue by DouglasHeriot** [netbox-community/ansible_modules#194]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Currently `config_context` and `custom_fields` are dictionaries of variables on each host. This is inconvenient if you want to use Ansible's `group_vars` and `host_vars` to override variables. You'd have to use [`hash_behaviour = merge`](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-hash-behaviour), or the `combine` filter everywhere - neither of those options are nice.

For example, it would be nice to be able to set `ansible_user` directly with config context in Netbox, and not require any extra configuration in Ansible.

##### EXPECTED RESULTS

Optionally want to have:
```
host:
    some_custom_field: "hello"
```

##### ACTUAL RESULTS

```
host:
    custom_fields:
        some_custom_field: "hello"
```

**Comment by FragmentedPacket** [comment]
Closed via #195
