### ISSUE TITLE
Inventory: Handle virtual chassis - ignore children

### ISSUE THREAD

**Issue by DouglasHeriot** [netbox-community/ansible_modules#200]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:

2.9.7

###### Netbox:

2.8.3

###### Collection:

0.2.0

##### SUMMARY

"A virtual chassis represents a set of devices which share a single control plane: a stack of switches which are managed as a single device, for example."
https://netbox.readthedocs.io/en/stable/core-functionality/devices/#virtual-chassis

As the whole point of a virtual chassis is to have a shared control plane, a virtual chassis should be a single host in the inventory - there is no need (and its often not even possible) to connect to a child of the switch stack.

I propose that child chassis devices shouldn't be included in the inventory. Their interfaces are all included in the master device (in the Netbox UI, and API)

This was originally proposed in ansible/ansible#60642

##### EXPECTED RESULTS

```
            "Test Nexus One": {
                "device_type": "nexus-parent",
                "manufacturer": "cisco",
                "interfaces": [
                    {
                        "id": 1,
                        ...
    "manufacturer_cisco": {
        "hosts": [
            "Test Nexus One",
        ]
    },

```

##### ACTUAL RESULTS

```
            "Test Nexus Child One": {
                "device_type": "nexus-child",
                "interfaces": [],
                "manufacturer": "cisco",
                        ...
            },
            "Test Nexus One": {
                "device_type": "nexus-parent",
                "manufacturer": "cisco",
                "interfaces": [
                    {
                        "id": 1,
                        ...

    "manufacturer_cisco": {
        "hosts": [
            "Test Nexus Child One",
            "Test Nexus One",
        ]
    },

```

**Comment by FragmentedPacket** [comment]
Implemented via #202
