### ISSUE TITLE
Accept string for validate_certs as done in pynetbox library

### ISSUE THREAD

**Issue by smutel** [netbox-community/ansible_modules#211]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:

v2.9
###### Netbox:

v2.7.6
###### Collection:

v0.2.1
##### SUMMARY

The pynetbox library contains a parameter ssl_verify which could be a boolean or a string.
Here is comment about this option in the pynetbox library:
```
:param bool/str,optional ssl_verify: Specify SSL verification behavior
        see: requests_.
```
String is useful to specify a folder containing the certs. With this capability it's possible to use self-signed certs.

Currently this project does not accept string for the parameter validate_certs. Is-it possible to change that ?

**Comment by FragmentedPacket** [comment]
@smutel Yes that is a good point. I will make the changes and submit a PR for this.

Once i've submitted the PR, I will tag you in it so you can test it.
