### ISSUE TITLE
Inventory: Device Status Filtering & Grouping

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/ansible_modules#213]
##### ISSUE TYPE
 - Feature Idea

###### Ansible:
2.9.9

###### Netbox:
2.8.5

###### Collection:
0.2.1

##### SUMMARY
It would be useful to be able to filter and group_by device status.

##### USE CASE
As more people use this plugin, status will allow workflows to filter out devices that are not in an active state.

**Comment by DouglasHeriot** [comment]
The `status` and `status__n` (inverse) device/vm query filters should already work if you need to filter on active status.

You should also be able to make it group by status using the `keyed_groups` option, although I agree making it a supported convenient `group_by` option is worth doing. I haven't tested it, but I think this should do it:

```yaml
keyed_groups:
  - prefix: status
    key: status.value
```

Note that any properties on the device or vm option from the NetBox API are accessible by the `keyed_groups`, `groups`, and `compose` options.

You can see these details in the [rendered documentation on the Ansible site](https://docs.ansible.com/ansible/latest/plugins/inventory/netbox.html). It's a little bit obscure if you're just reading the source file - `extends_documentation_fragment: - constructed` is where this comes from.

**Comment by metabsd** [comment]
@DouglasHeriot Copy paste this anwser in the documentation as is. This is really usefull. Again good job!!! We are using the inv script to deploy change on a lot of device and it's working like a charm.

**Comment by ryanmerolle** [comment]
@DouglasHeriot i second the praise.  Not only work was your documentation right in with regards to status as a filter, but you also taught me about keyed_groups!

I appreciate all the work you do with this repo!

**Comment by FragmentedPacket** [comment]
Is `keyed_groups` the acceptable answer for this?

I will get @DouglasHeriot comments documented in the example if that is the only thing needed for this.

**Comment by ryanmerolle** [comment]
Keyed_groups is the way to go and should get documented as such.
