### ISSUE TITLE
nb_inventory plugin has no way to ignore SSL trust verification

### ISSUE THREAD

**Issue by dakennedy** [netbox-community/ansible_modules#216]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

###### Ansible:
 2.9.9-1

###### Netbox:
2.7.3

###### Collection:
0.2.1

##### SUMMARY
The inventory query plugin has no way to disable SSL trust verification.  This is problematic because adding the trusted CA to AWX's docker containers doesn't work out of the box.  However this should be an option because the other modules in the netbox.netbox gallery appear to work properly

##### STEPS TO REPRODUCE

use loop: in a play and have something similar to:

- name: Print Tenant VLAN name
  vars:
    netbox_url_protocol: "https://{{netbox_url}}"
    vlan_name: {{ item.value.name }}
    tenant: "tenant"
  debug:
    msg: "The VLAN ID is : {{ item.value.vid }}"
    state: merged
  when: vlan_name == "my_vlan"
  loop: "{{ query('netbox.netbox.nb_lookup', 'vlans', 
                    api_endpoint=netbox_url_protocol,
                    ssl_verify=false,
                    api_filter='tenant=' + tenant,
                    token=netbox_token) }}"

```

##### EXPECTED RESULTS
Get the data back for this vlan

The VLAN ID is : 101

##### ACTUAL RESULTS
SSL ERROR in the play 
```
{
    "msg": "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'requests.exceptions.SSLError'>, original message: HTTPSConnectionPool(host='netbox', port=443): Max retries exceeded with url: /api/ipam/vlans/?tenant=tntx&site=ashburn-va (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))",
    "_ansible_no_log": null
}
```

**Comment by FragmentedPacket** [comment]
I just want to confirm the issue. It appears your issue is really with the lookup plugin. That plugin doesn't appear to have any option to disable SSL so that will have to be added.

**Comment by dakennedy** [comment]
Thank you!  Should be a fairly easy edit
