### ISSUE TITLE
Include Ansible Inventory plugin too?

### ISSUE THREAD

**Issue by DouglasHeriot** [netbox-community/ansible_modules#22]
##### ISSUE TYPE
 - Feature Idea

Should the Netbox inventory plugin also be copied to this separate repo for development separate to Ansible core?

There's [open pull requests](https://github.com/ansible/ansible/pull/60642) that are taking some time to be merged, and I'd love to avoid them being tied to waiting for Ansible releases.

**Comment by FragmentedPacket** [comment]
That's a really good question. I may have to open an issue within Ansible repo to see how the authors feel about it. It appears with the license I can move it on over without any repercussions, but just want to make sure it's OK before I do so.

If they're OK with it, the next steps would be to submit a PR here, add in unit and integration tests before merging.

**Comment by DouglasHeriot** [comment]
There's also this Netbox lookup plugin waiting to be merged:
https://github.com/ansible/ansible/pull/59611

**Comment by cpmills1975** [comment]
> There's also this Netbox lookup plugin waiting to be merged:
> [ansible/ansible#59611](https://github.com/ansible/ansible/pull/59611)

That's mine. More than happy to support any method to getting this out in the wild. :-)

**Comment by FragmentedPacket** [comment]
@cpmills1975 I would accept a PR for that with accompanying unit and integration tests! I assume there will either be bugs or people requesting more features so as long as you can help maintain it, that would be great as well.

**Comment by cpmills1975** [comment]
> @cpmills1975 I would accept a PR for that with accompanying unit and integration tests! I assume there will either be bugs or people requesting more features so as long as you can help maintain it, that would be great as well.

Sounds good. What I'm struggling with a bit is how to effectively write some tests for this as, like your modules, it is wholly dependent upon having access to a Netbox instance and, for to be able to test the lookups, known information within it that Ansible can pull out. Do you have, or would you be interested in, hosting a Netbox instance somewhere that I can query for known values?

**Comment by FragmentedPacket** [comment]
You can write unit tests with mock data to test the code functionality of it. I can probably take a look at it and help write the unit tests.

If you look at the **.travis.yml**, it shows that we spin up a Netbox instance and run our integration tests against. If you look at the integration tests, it shows the token and URL that is used to connect to it.

If you have issues with creating the tests, open an issue on it, and we can discuss it in more detail there. I'm also available on the NetworkToCode slack channel. http://slack.networktocode.com/

**Comment by FragmentedPacket** [comment]
@DouglasHeriot It has been added (#54), but not officially release in any version. You can build the collection from source. Please note the namespace and collection name change since moving to the netbox-community repo.


I will most likely release a new version pretty soon as the repo has been pretty quiet.

**Comment by DouglasHeriot** [comment]
@FragmentedPacket thanks! I'll try and get to testing/improving this soon.
