### ISSUE TITLE
update_netbox_object is unstable on unsorted lists (like tags)

### ISSUE THREAD

**Issue by monkz** [netbox-community/ansible_modules#242]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.9

###### Netbox:
2.8.5

###### Collection:
0.2.3

##### SUMMARY
Updates are triggered if the order of tags does not match those in the playbook.
```
    "diff": {
        "after": {
            "tags": [
                "storage",
                "nvme"
            ]
        },
        "before": {
            "tags": [
                "nvme",
                "storage"
            ]
        }
    },
```
##### STEPS TO REPRODUCE
Create an inventory item with with tags mentioned above.

##### EXPECTED RESULTS
Order in list of tags is ignored.

##### ACTUAL RESULTS
If order of tags does not fit the returned order, an update is triggered.

https://github.com/netbox-community/ansible_modules/blob/8cbbfde0522a054e7b394da4d9b7646a798674bd/plugins/module_utils/netbox_utils.py#L851

**Comment by FragmentedPacket** [comment]
Thanks for the report!

I will try and get this fixed soon. I think we can just convert tags to sets and then test.

**Comment by monkz** [comment]
Works - thank you
