### ISSUE TITLE
update_netbox_object is unstable if value ends on whitespace (like in the description)

### ISSUE THREAD

**Issue by monkz** [netbox-community/ansible_modules#243]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.9

###### Netbox:
2.8.5

###### Collection:
0.2.3

##### SUMMARY
Netbox trims strings, the netbox collection detects a difference between playbook and returned value. Thous triggers an update.
```
    "diff": {
        "after": {
            "description": "WWN:  ",
        },
        "before": {
            "description": "WWN:",
        }
```

##### STEPS TO REPRODUCE
Create an inventory item with description that ends on whitespace.

##### EXPECTED RESULTS
Either the collection trims as well, or issues a warning about trailing whitespace.

##### ACTUAL RESULTS
It gets updated over and over, because the value with whitespace (in ansible-playbook) does not match the returned value from netbox that is trimmed.

**Comment by FragmentedPacket** [comment]
Thanks for this report! This should be able to be fixed within the the `_normalize_data` method.

**Comment by monkz** [comment]
Works as well. thank you for this fix too

**Comment by FragmentedPacket** [comment]
Thanks for reporting these bugs!
