### ISSUE TITLE
nb_lookup: Multiple same-type "api_filter" arguments unsupported

### ISSUE THREAD

**Issue by jkuzma07** [netbox-community/ansible_modules#246]
##### ISSUE TYPE
- Bug Report 

##### SUMMARY

When trying to pass multiple "api_filter" arguments of a common type, the resulting GET is flattened to the last supplied value only.

##### STEPS TO REPRODUCE

```yaml
- debug:
    msg: "{{ query('nb_lookup', 'devices', api_endpoint=netbox_url, token=netbox_token,
                    api_filter='role=foo role=bar status=active status=planned'
                    ) }}"
```

##### EXPECTED RESULTS

Return a list of dicts: devices having either "foo" or "bar" roles, and status of either "active" or "planned".
```
"GET /api/dcim/devices/?q=&role=foo&role=bar&status=active&status=planned HTTP/1.0" 200
```
##### ACTUAL RESULTS

```
"GET /api/dcim/devices/?role=bar&status=planned HTTP/1.0" 200
```

**Comment by FragmentedPacket** [comment]
I will look further into a fix for this. I believe the reason this happens is because is creates a dictionary when parsing what the user passes in, and since there are duplicate keys, it uses the last one.

**Comment by FragmentedPacket** [comment]
Do you mind testing #250 ?

I believe this issue should be fixed by that PR.

**Comment by jkuzma07** [comment]
Seems to work as advertised. Thanks for the fix. Cheers!
