### ISSUE TITLE
I have issue resolving device_type from netbox_device.py module

### ISSUE THREAD

**Issue by ghost** [netbox-community/ansible_modules#252]
##### ISSUE TYPE
 - Module question

###### Ansible:
2.9.9
###### Netbox:
4.3.1
##### SUMMARY
I have issue resolving device_type from netbox_device.py module when device_type is integer
For example, the device_type is 1841 then I would get below message
  msg: '{"device_type":["Related object not found using the provided numeric ID: 1841"]}'
##### STEPS TO REPRODUCE
    - name: DEVICE
      collections:
        - netbox.netbox
      netbox_device:
        netbox_url: 
        netbox_token: 
        data:
          name: test
          device_type: "1841"
          device_role: "{{ device_role }}"
          platform: Cisco IOS
          site: test
          tenant: test
        state: active

##### ACTUAL RESULTS
  msg: '{"device_type":["Related object not found using the provided numeric ID: 1841"]}'

```

```

**Comment by FragmentedPacket** [comment]
Could you provide a verbose run of this? That appears to be something returned from the NetBox server itself.

**Comment by kyungl9** [comment]
The full traceback is:
  File "/tmp/ansible_netbox_device_payload_4ohvgy4t/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 643, in _create_netbox_object
    nb_obj = nb_endpoint.create(data)
  File "/home/leonard/venv/lib/python3.6/site-packages/pynetbox/core/endpoint.py", line 287, in create
    ).post(args[0] if args else kwargs)
  File "/home/leonard/venv/lib/python3.6/site-packages/pynetbox/core/query.py", line 381, in post
    return self._make_call(verb="post", data=data)
  File "/home/leonard/venv/lib/python3.6/site-packages/pynetbox/core/query.py", line 274, in _make_call
    raise RequestError(req)
fatal: [test]: FAILED! => changed=false 
  invocation:
    module_args:
      data:
        asset_tag: null
        cluster: null
        comments: null
        device_role: Router
        device_type: '1841'
        face: null
        name: test
        platform: Cisco IOS
        position: null
        primary_ip4: null
        primary_ip6: null
        rack: null
        serial: FTX1144Y0LV
        site: test
        status: null
        tags:
        - automated
        tenant: test
      netbox_token: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      netbox_url: http://localhost:8000
      state: present
      validate_certs: true
  msg: '{"device_type":["Related object not found using the provided numeric ID: 1841"]}'

**Comment by FragmentedPacket** [comment]
Hmm this is an interesting predicament. I made a change to allow users to pass in integers for these and wasn't expecting people to have only numerical device types.

The reason for the change as well is due to the Jinja templating in Ansible will always be a string even if using the `|int` so trying to pass in the ID of a lookup will result in a string and then pass the string to the NetBox IP and the task fails.

Let me think about this a bit more to see how we can solve this.
