### ISSUE TITLE
"Failed to establish connection to Netbox API"

### ISSUE THREAD

**Issue by swickera** [netbox-community/ansible_modules#260]
Hi, following your example playbooks at https://galaxy.ansible.com/netbox/netbox against a test installation and am receiving "Failed to establish connection to Netbox API" messages.

Noted with v0.2.3, v0.2.2 and spot checked other versions back to v0.1.10, all with the same result.  This is on RHEL 7.8 with python 2.7.5 and 3.6.8, Ansible version 2.9.10.

I've forced both python3 and python2 interpreters with Ansible and neither is working.

This seems to be an issue calling pynetbox.api() from the modules; running the same call from both python2 and python3 interpreters manually as follows works just fine:

> import pynetbox
> nb = pynetbox.api('http://server:8000','redacted_token')
> nb.dcim.devices.all()

Sample playbook (formatting is munged in markdown):

> ---
> - name: "Test NetBox modules"
>   connection: local
>   hosts: localhost
>   gather_facts: False
>   collections:
>     - netbox.netbox
>   
>   tasks:
>     - name: Create device within NetBox with only required information
>       netbox_device:
>         netbox_url: http://server:8000
>         netbox_token: redacted
>         validate_certs: false
>         data:
>           name: Test66
>           device_type: Cisco Test
>           device_role: Core Switch
>           site: Test Site
>           status: Staged
>         state: present

Traceback:
> The full traceback is:
>   File "/tmp/ansible_netbox_device_payload_eqq9r_ri/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 417, in _connect_netbox_api
>     nb = pynetbox.api(url, token=token, ssl_verify=ssl_verify)
> fatal: [localhost]: FAILED! => {
>     "changed": false,
>     "invocation": {
>         "module_args": {
>             "data": {
>                 "asset_tag": null,
>                 "cluster": null,
>                 "comments": null,
>                 "custom_fields": null,
>                 "device_role": "Core Switch",
>                 "device_type": "Cisco Test",
>                 "face": null,
>                 "name": "Test66",
>                 "platform": null,
>                 "position": null,
>                 "primary_ip4": null,
>                 "primary_ip6": null,
>                 "rack": null,
>                 "serial": null,
>                 "site": "Test Site",
>                 "status": "Staged",
>                 "tags": null,
>                 "tenant": null
>             },
>             "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
>             "netbox_url": "http://server:8000",
>             "query_params": null,
>             "state": "present",
>             "validate_certs": false
>         }
>     },
>     "msg": "Failed to establish connection to Netbox API"
> }

**Comment by ThomasADavis** [comment]
What version of pynetbox are you using?  if it's 5.0 or greater, this will happen.

in our local requirements file, we have:

pynetbox <5.0

**Comment by swickera** [comment]
I was at 5.0.3; just down-revved to v4.3.3 and an getting a similar error but with more noise:

> The full traceback is:
>   File "/tmp/ansible_netbox_device_payload_pck8_85j/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 419, in _connect_netbox_api
>     self.version = float(nb.version)
>   File "/usr/local/lib/python3.6/site-packages/pynetbox/api.py", line 230, in version
>     http_session=self.http_session,
>   File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 195, in get_version
>     verify=self.ssl_verify,
>   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 76, in get
>     return request('get', url, params=params, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> fatal: [localhost]: FAILED! => {
>     "changed": false,
>     "invocation": {
>         "module_args": {
>             "data": {
>                 "asset_tag": null,
>                 "cluster": null,
>                 "comments": null,
>                 "custom_fields": null,
>                 "device_role": "Core Switch",
>                 "device_type": "Cisco Test",
>                 "face": null,
>                 "name": "Test66",
>                 "platform": null,
>                 "position": null,
>                 "primary_ip4": null,
>                 "primary_ip6": null,
>                 "rack": null,
>                 "serial": null,
>                 "site": "Test Site",
>                 "status": "Staged",
>                 "tags": null,
>                 "tenant": null
>             },
>             "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
>             "netbox_url": "http://mos-swick19new.adsroot.itcs.umich.edu:8000",
>             "query_params": null,
>             "state": "present",
>             "validate_certs": false
>         }
>     },
>     "msg": "Failed to establish connection to Netbox API"
> }

**Comment by swickera** [comment]
I was at v5.0.3; down-revving to v4.3.3 resolved this.  Thank you for the suggestion!
