### ISSUE TITLE
Lookup plugin: nb_lookup doesn't default to validate certs

### ISSUE THREAD

**Issue by matte4711** [netbox-community/ansible_modules#273]
##### ISSUE TYPE

 - Bug Report

###### Ansible: 

ansible 2.9.10

###### Netbox:

v2.8.7
###### Collection:

v 0.3.0

##### SUMMARY

nb_lookup plugin does not default to validate_certs

##### STEPS TO REPRODUCE

use nb_lookup plugin in any playbook and do not pass validate_certs. 

```yaml
vars: 
    device: "{{ query('netbox.netbox.nb_lookup', 'devices', api_filter='name={}'.format(inventory_hostname),  api_endpoint='{}'.format(netbox_url), token='{}'.format(netbox_token))[0].value }}"

```

There will be a warning similar to this one:

`/Users/matte/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host 'netbox-lab.netnod.se'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,`

The culprit seems to be at:
[https://github.com/FragmentedPacket/ansible_modules/blob/devel/plugins/lookup/nb_lookup.py#L199
](nb_lookup.py#L199)

`        netbox_ssl_verify = kwargs.get("validate_certs")`
vs
`        netbox_ssl_verify = kwargs.get("validate_certs", True)`

##### ACTUAL RESULTS

```

```

**Comment by FragmentedPacket** [comment]
Can you test the attached PR to see if it fixes your issue?

**Comment by matte4711** [comment]
Thanks!
I can confirm that this fix solves the problem.
