### ISSUE TITLE
Documentation: Show example of using as inventory in README

### ISSUE THREAD

**Issue by yzguy** [netbox-community/ansible_modules#283]
##### ISSUE TYPE
 - Documentation update

##### SUMMARY
The README currently has examples of using this within tasks, but none showing how to use it for inventory. It would be helpful for a very simple example to be placed in the README, then link to the information within `plugins/inventory/nb_inventory.py` for more options.

I'm happy to create a PR for this, just wondering if there is any thoughts on this, and if just linking to the information in `nb_inventory.py` for more options is sufficient. Just something simple like:

```
netbox_inventory.yml
---
plugin: netbox.netbox.nb_inventory
api_endpoint: http://netbox-demo.org:32768
token: 0123456789abcdef0123456789abcdef01234567
config_context: True
interfaces: True
group_by:
  - device_roles

compose:
  ansible_network_os: platform.slug
```

` ansible-inventory --list -i netbox_inventory.yml`

**Comment by adamwoolhether** [comment]
I was having difficulty with some as well, and found detailed examples for each modules [here](https://github.com/netbox-community/ansible_modules/tree/v0.3.1/plugins/modules).

**Comment by FragmentedPacket** [comment]
I'm planning to get a RTD site going for this hopefully within the next two weeks while I'm on vacation and it should be more example rich. Please stay posted, but you're more than welcome to add an example of the inventory plugin to the README in the meantime if you'd like.

**Comment by ThomasADavis** [comment]
I'd make sure that you document the use of environment variables, instead of putting the netbox api token into the yaml configuration file.  We also use onepassword, and a setup like this:

first, we create a bootstrap.sh that contains:

```
#!/bin/bash

#
# install ansible to the user's home directory.
# this avoids polluting the system ansible, and gets the right version of everything
# on centos7/8
#

rm -rf ./venv

python3 -m venv ./venv

source ./venv/bin/activate

export PYCURL_SSL_LIBRARY=nss
pip install pycurl

pip install -r requirements.txt

PATH=~/.local/bin:$PATH

ansible-galaxy collection install netbox.netbox --force
ansible-galaxy collection install ovirt.ovirt --force

chmod 0600 ansible.cfg
```

requirements.txt:

```
ansible
dnspython
netaddr
snimpy
pynetbox <5.0
redis
pygsheets
mysql-connector-python
```
and setup.sh script that gets sourced that does:

```
eval $(op signin)
export NETBOX_TOKEN=$(op get item netbox | jq .details.fields[1].value | cut -f2 -d\")
export NETBOX_API=$(op get item netbox | jq .details.fields[0].value | cut -f2 -d\")
export PATH=~/.local/bin:$PATH
export ANSIBLE_REMOTE_TMP=/tmp
source ./venv/bin/activate
```

note: this does have problems, it's expecting the defaults to be in a certain order..

We put this in all playbooks:

```
  pre_tasks:
    - name: get the netbox credentials
      set_fact:
        netbox_url:   '{{ lookup( "onepassword", "netbox", field="username" ) }}'
        netbox_token: '{{ lookup( "onepassword", "netbox", field="password" ) }}'
```

With this, we know we have the right python/ansible/ansible-galaxy modules, with the correct pycurl setup, 
the netbox tokens are not saved in any file that can accidently end up in a git repo with public access..
