### ISSUE TITLE
netbox_interface no longer exists

### ISSUE THREAD

**Issue by gundalow** [netbox-community/ansible_modules#285]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
In https://github.com/netbox-community/ansible_modules/pull/225 `netbox_interface` was deleted. This module previously shipped in Ansible, so it need to continue to exist.
If it's been replaced by another module (though under a different name) then `meta/runtime.yml` needs updating to include ` redirect`

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by gundalow** [comment]
@FragmentedPacket @DouglasHeriot  @loganbest @lampwins @cpmills1975 Can you provide any info on this/

**Comment by FragmentedPacket** [comment]
We got the Ansible lint working, but was having an issue with it failing on that module. What are the steps to take for this as I couldn't find any documentation.

**Comment by gundalow** [comment]
> We got the Ansible lint working, but was having an issue with it failing on that module. What are the steps to take for this as I couldn't find any documentation.

@FragmentedPacket ansible-lint or ansible-test? 

Could you please raise a PR to add it back and copy the error(s) in as a comment, then we can take a look.
