### ISSUE TITLE
NetBox 2.9 Tags Move from List to List of Dictionaries

### ISSUE THREAD

**Issue by jvanderaa** [netbox-community/ansible_modules#287]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.9.11

###### Netbox:

2.9 beta 1

###### Collection:

0.2.3

##### SUMMARY

Tags in NetBox 2.9 are moving data types

##### STEPS TO REPRODUCE

Create a NetBox 2.9 beta, and assign tags, tags now have a different output from NetBox

### NetBox 2.8 Response

```
      "tags": [
        "test_tag01"
      ],
```

### NetBox 2.9 Response

```
      "tags": [
        {
          "id": 1,
          "url": "https://netbox-beta/api/extras/tags/1/",
          "name": "test_tag01",
          "slug": "test_tag01",
          "color": "607d8b"
        }
      ],
```

**Comment by dotSource-GmbH** [comment]
adjust the def extract_tags ... worked for me 

 def extract_tags(self, host):
        #return host["tags"]
        # 2020-08-31 by tse new tag structure in netbox 2.9
        try:
            return [sub['name'] for sub in host["tags"] ]
        except Exception:
            return

**Comment by FragmentedPacket** [comment]
I'm going to look into this since I'll be in the car for about 24 hours this coming weekend.

I was thinking we should probably go with slug due to uniqueness and then since we use it with the `group_by` option, would also serve that well.

Is there any objections?
