### ISSUE TITLE
NetBox 2.9 -> Add Tag Module

### ISSUE THREAD

**Issue by jvanderaa** [netbox-community/ansible_modules#288]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

In NetBox 2.9 beta tags now need to be created before they can be added to a device. A module should be developed to support tag manipulation (CRUD)

**Comment by minitriga** [comment]
Ahh just come to add this. Thank you for doing so.

**Comment by FragmentedPacket** [comment]
This is implemented per #368
