### ISSUE TITLE
Failed to parse with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is reserved to provide a port

### ISSUE THREAD

**Issue by MaartenMol** [netbox-community/ansible_modules#294]
##### ISSUE TYPE

 - Bug Report
 - Module question

###### Ansible:

2.9.10

###### Netbox:

2.8.8

###### Collection:

0.3.1

##### SUMMARY

Parsing error:
```
[WARNING]:  * Failed to parse /tmp/awx_91_tqj5wpri/project/inventory.yml with
ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not
allowed, this character is reserved to provide a port.
```
When using the query_filters option in my inventory.yml. Without this option it runs perfectly. Is this a bug or am I doing something wrong?

##### STEPS TO REPRODUCE

With the following inventory.yml I get the above parsing error:

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: XXXXX
token: XXXXX
config_context: True
interfaces: True
flatten_custom_fields: True
group_names_raw: True
group_by:
  - device_roles
query_filters:
  - tenant: "TEST-KLANT"
  - tag: virtualmachine
```

However, when leaving out the query_filter part, Ansible parses it perfectly. What is going wrong?

```yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: XXXXX
token: XXXXX
config_context: True
interfaces: True
flatten_custom_fields: True
group_names_raw: True
group_by:
  - device_roles
```

##### EXPECTED RESULTS

I expect perfect parsing just like when not using query_filters.
##### ACTUAL RESULTS

```
    2.410 INFO     Updating inventory 6: TEST-KLANT
    3.421 INFO     Reading Ansible inventory source: /tmp/awx_91_tqj5wpri/project/inventory.yml
    3.424 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    3.424 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    3.424 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1149, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1039, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 215, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 198, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /tmp/awx_91_tqj5wpri/project/inventory.yml as it did not pass its verify_file() method
script declined parsing /tmp/awx_91_tqj5wpri/project/inventory.yml as it did not pass its verify_file() method
toml declined parsing /tmp/awx_91_tqj5wpri/project/inventory.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /tmp/awx_91_tqj5wpri/project/inventory.yml with
auto plugin: Invalid type for configuration option plugin_type: inventory
plugin: ansible_collections.netbox.netbox.plugins.inventory.nb_inventory
setting: query_filters : Invalid type provided for "list": {'tenant': 'TEST-
KLANT'}
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/var/lib/awx/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1260, in parse
    self._read_config_data(path=path)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/__init__.py", line 229, in _read_config_data
    self.set_options(direct=config)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/__init__.py", line 75, in set_options
    self._options = C.config.get_plugin_options(get_plugin_class(self), self._load_name, keys=task_keys, variables=var_options, direct=direct)
  File "/usr/lib/python3.6/site-packages/ansible/config/manager.py", line 349, in get_plugin_options
    options[option] = self.get_config_value(option, plugin_type=plugin_type, plugin_name=name, keys=keys, variables=variables, direct=direct)
  File "/usr/lib/python3.6/site-packages/ansible/config/manager.py", line 418, in get_config_value
    keys=keys, variables=variables, direct=direct)
  File "/usr/lib/python3.6/site-packages/ansible/config/manager.py", line 511, in get_config_value_and_origin
    (to_native(_get_entry(plugin_type, plugin_name, config)), to_native(e)))
[WARNING]:  * Failed to parse /tmp/awx_91_tqj5wpri/project/inventory.yml with
yaml plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /tmp/awx_91_tqj5wpri/project/inventory.yml with
ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not
allowed, this character is reserved to provide a port.
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /tmp/awx_91_tqj5wpri/project/inventory.yml as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by FragmentedPacket** [comment]
What if you remove the quotes from the text on the first filter?

Have you tried downgrading to maybe `0.3.0` of the collection and seeing if the issue remains?

**Comment by MaartenMol** [comment]
> What if you remove the quotes from the text on the first filter?
> 
> Have you tried downgrading to maybe `0.3.0` of the collection and seeing if the issue remains?

Tried both without luck. Installing version 0.3.0 doesn't solve the issue and removing the quotes doesn't help either. Am I just missing something?

**Comment by FragmentedPacket** [comment]
It seems like some kind of formatting bug on the YAML file.

```
plugin: ansible_collections.netbox.netbox.plugins.inventory.nb_inventory
setting: query_filters : Invalid type provided for "list": {'tenant': 'TEST-
KLANT'}
```

From your YAML file, it appears it should be a list for `query_filters`, but it is not seeing that when parsing the file.

Maybe try pasting your inventory file into: https://jsonformatter.org/yaml-formatter and then copying it back into it?

**Comment by MaartenMol** [comment]
> It seems like some kind of formatting bug on the YAML file.
> 
> ```
> plugin: ansible_collections.netbox.netbox.plugins.inventory.nb_inventory
> setting: query_filters : Invalid type provided for "list": {'tenant': 'TEST-
> KLANT'}
> ```
> 
> From your YAML file, it appears it should be a list for `query_filters`, but it is not seeing that when parsing the file.
> 
> Maybe try pasting your inventory file into: https://jsonformatter.org/yaml-formatter and then copying it back into it?

Did that, looking at git after it did change a few lines but didn't solve it! :(

**Comment by FragmentedPacket** [comment]
Let me try yours after a while. Just got back from PTO, but I'll try your file and see if I can reproduce it.

**Comment by FragmentedPacket** [comment]
I ran into other issues, but not this one.

What if you recreate a virtualenv and install Ansible and pynetbox fresh and see if that solves your issue?

I'm not entirely sure why it is failing to properly parse your inventory file. You could possibly try creating a new one from scratch and seeing if that resolves your issue.

**Comment by MaartenMol** [comment]
> I ran into other issues, but not this one.
> 
> What if you recreate a virtualenv and install Ansible and pynetbox fresh and see if that solves your issue?
> 
> I'm not entirely sure why it is failing to properly parse your inventory file. You could possibly try creating a new one from scratch and seeing if that resolves your issue.

Ran it in a fresh box:
```
# ansible-inventory -v --list -i inventory.test.yml
Using /etc/ansible/ansible.cfg as config file
Fetching: https://HOSTNAME/api/docs/?format=openapi
Fetching: https://HOSTNAME/api/dcim/devices/?limit=0&tenant=TEST-KLANT&tag=virtualmachine
[WARNING]:  * Failed to parse /root/inventory.test.yml with auto plugin: HTTP Error 400: Bad Request
[WARNING]:  * Failed to parse /root/inventory.test.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /root/inventory.test.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is reserved to provide a port.
[WARNING]: Unable to parse /root/inventory.test.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```

**Comment by MaartenMol** [comment]
Alright I found the issue. Used the following inventory.yml:

```
plugin: 'netbox.netbox.nb_inventory'
api_endpoint: 'https://HOSTNAME'
token: 'API_KEY'
config_context: true
interfaces: true
group_names_raw: true
group_by:
  - device_roles
query_filters:
  - tenant: test-klant
  - tag: virtualmachine
#  - tenant_id: 2
flatten_custom_fields: true
```

As I tested, when commenting out the query for tenant and added tenant_id it did work! Then I tried the tenant query again but with the SLUG value of the tenant instead of the name it did work. So, is this as intended or a bug?

**Comment by FragmentedPacket** [comment]
That's what I was seeing as well. I will mess with this further and try different versions of NetBox. It seems to be doing some kind of validation or something.

**Comment by FragmentedPacket** [comment]
Alright. This looks to go back quite a bit. I will look into error handling for the request and have it just error out with the actual message from the API when invalid choices are selected.

Here is an example cURL command that fails and the returned output:
```bash
curl http://localhost:32771/api/dcim/devices/\?limit\=0\&tenant\=TEST-TENANT -H "Authorization: Token 0123456789abcdef0123456789abcdef01234567"
{"tenant":["Select a valid choice. TEST-TENANT is not one of the available choices."]}
```

Here is one that is a valid choice:
```bash
curl http://localhost:32771/api/dcim/devices/\?limit\=0\&tenant\=test-tenant -H "Authorization: Token 0123456789abcdef0123456789abcdef0123456
7"
{"count":0,"next":null,"previous":null,"results":[]}
```

I think at least returning what the API provides in the error would be beneficial to the user to better understand what went wrong with the request (HTTP 400).

**Comment by MaartenMol** [comment]
@FragmentedPacket currently running in an issue with the same error. I am trying to use a VARIABLE in the inventory.yml:

```
plugin: netbox.netbox.nb_inventory
api_endpoint: 'api_host.com'
token: XXXXX
config_context: true
interfaces: true
flatten_custom_fields: true
group_names_raw: true
group_by:
  - tags
query_filters:
  - tenant: "{{ tenant_name }}"
  - tag: virtualmachine
```

Als tried the following: "{{ ansible_env['tenant_name'] }}"

Both giving the same error as the original post. Would this mean that VARIABLES don't come trough or?

**Comment by FragmentedPacket** [comment]
What kind of variable? This loads before any variables are loaded I believe, but do you want to use an environment variable?

**Comment by MaartenMol** [comment]
> What kind of variable? This loads before any variables are loaded I believe, but do you want to use an environment variable?

Yes, as I am using AWX too. I want 1 Inventory file for many different tenants. As CREDENTIALS and ENVIRONMENT variables are both supported in AWX for Inventory Sources, I planned to use that. 

So I need the VARIABLE so the single inventory file can act for all tenants with just simply giving the tenant name in a ENV variable. Is this possible? Becuase as I look into AWX, it should be able to.

(PS: The same goes for CREDENTIALS that can be given using AWX, however it doesn't accept those either. So currently I need to config the API url and key in flat file)

**Comment by FragmentedPacket** [comment]
https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/inventory/nb_inventory/netbox.netbox.nb_inventory_inventory.html

There are supported environment variables for the token and endpoint. And then try the `{{ lookup('env', 'nameofenv') }}` within the inventory file for the tenant.

Let me know if that works

**Comment by MaartenMol** [comment]
> https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/inventory/nb_inventory/netbox.netbox.nb_inventory_inventory.html
> 
> There are supported environment variables for the token and endpoint. And then try the `{{ lookup('env', 'nameofenv') }}` within the inventory file for the tenant.
> 
> Let me know if that works

I will tomorrow when I get back to work! Thanks for the fast response! Will let you know if it works.

**Comment by MaartenMol** [comment]
> https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/inventory/nb_inventory/netbox.netbox.nb_inventory_inventory.html
> 
> There are supported environment variables for the token and endpoint. And then try the `{{ lookup('env', 'nameofenv') }}` within the inventory file for the tenant.
> 
> Let me know if that works

Alright ran the following:

```
plugin: netbox.netbox.nb_inventory
config_context: true
interfaces: true
flatten_custom_fields: true
group_names_raw: true
group_by:
  - tags
query_filters:
  - tenant: "{{ lookup('env', 'tenant_name') }}"
  - tag: vm
```

But no luck, also giving the correct VAR names in my credentials don't work.

**Comment by FragmentedPacket** [comment]
You will most likely need to have a custom credential for it that sweet those as environment variables. 

Join our NTC Slack and hit me up: networktocode.slack.com

**Comment by MaartenMol** [comment]
> You will most likely need to have a custom credential for it that sweet those as environment variables. 
> 
> 
> 
> Join our NTC Slack and hit me up: networktocode.slack.com

Ah I have, a custom credential with the specified variable names from readthedocs. I will join slack when I am at work again.

**Comment by MaartenMol** [comment]
> You will most likely need to have a custom credential for it that sweet those as environment variables.
> 
> Join our NTC Slack and hit me up: networktocode.slack.com

Can't join the Slack link provided. I think sign-up isn't open/public?

**Comment by MaartenMol** [comment]
> https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/inventory/nb_inventory/netbox.netbox.nb_inventory_inventory.html
> 
> There are supported environment variables for the token and endpoint. And then try the `{{ lookup('env', 'nameofenv') }}` within the inventory file for the tenant.
> 
> Let me know if that works

Is there another way, or a way to troubleshoot shit. Can't get more from logging than the given log above.

**Comment by FragmentedPacket** [comment]
Slack.networktocode.com

**Comment by MaartenMol** [comment]
Opened a new issue for the variables that won't get picked up: https://github.com/netbox-community/ansible_modules/issues/313
