### ISSUE TITLE
Extend netbox_ip_address.py to allow assignment of IPs to virtual machines

### ISSUE THREAD

**Issue by Twisted64** [netbox-community/ansible_modules#302]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY
Tried this for a little while before I realised the module is only filtering physical devices. We can add interfaces to virtual machines, and now we'd like to add IP addresses to those interfaces as well.

I think it's taking the machine name and filtering on dcim.devices.filter("name")
so it would need to accept a separate parameter to filter on virtualization.virtual_machines.filter("name")

and then do all the other magic that it already does.

**Comment by FragmentedPacket** [comment]
A PR would be welcome if you can.

I'm currently pretty busy with life and this repo. Attempting to get #298 squared away via #303.

I don't see much time to implement this in the foreseeable future. :(

**Comment by adamwoolhether** [comment]
Hi @Twisted64, sorry for the off-topic response, but how does one even add an IP address to a specific device's interface?

I don't see the module-equivalent of the GUI's "Interface Assignment" section when adding an IP to a specific device's interface.

Assigning a specific IP to a specific device's interface doesn't seem possible, or simply done in via the netbox_ip_address module...

**Comment by Twisted64** [comment]
@adamwoolhether Check the code, there are a few examples in there. Copied below.

When you call the module, you identify the interface by passing the name and also name of the device it's on.

- name: Ensure that an IP inside 192.168.1.0/24 is attached to GigabitEthernet1
      netbox_ip_address:
        netbox_url: http://netbox.local
        netbox_token: thisIsMyToken
        data:
          prefix: 192.168.1.0/24
          vrf: Test
          interface:
            name: GigabitEthernet1
            device: test100
        state: present
    - name: Attach a new available IP of 192.168.1.0/24 to GigabitEthernet1
      netbox_ip_address:
        netbox_url: http://netbox.local
        netbox_token: thisIsMyToken
        data:
          prefix: 192.168.1.0/24
          vrf: Test
          interface:
            name: GigabitEthernet1
            device: test100
        state: new

**Comment by FragmentedPacket** [comment]
We now have a docs site and the specific module docs can be found here:
https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/modules/netbox_device_interface/netbox.netbox.netbox_device_interface_module.html

**Comment by ThomasADavis** [comment]
wait, you mean this doesn't work for you?

```- name: and the IP address..
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ nic.reported_devices[0]['ips'][0]['address'] }}/32"
      tenant: OMNI
      vrf: omni-core
      interface:
          virtual_machine: "{{ vm.name }}"
          name: "{{ nic.reported_devices[0]['name'] }}"
    state: present
  when: nic.reported_devices | length > 0
  loop: "{{ nics.ovirt_nics }}"
  loop_control:
    loop_var: nic
```

for virtual machines, you use 'virtual_machine', not 'device'.

**Comment by Twisted64** [comment]
That works!
So, here's the relevant documentation link, the examples don't demonstrate a virtual machine, but we (I) need to understand that an interface can refer to both. Anyway I'll close this off.

https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/modules/netbox_ip_address/netbox.netbox.netbox_ip_address_module.html#parameter-data/interface
