### ISSUE TITLE
Inventory plugin fails when permissions are restricted

### ISSUE THREAD

**Issue by cpmills1975** [netbox-community/ansible_modules#312]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.9

###### Netbox:

2.9-beta1 and possibly earlier

###### Collection:

1.0.0

##### SUMMARY

Inventory plugin fails when permissions are restricted

##### STEPS TO REPRODUCE

Create a token for a user that, through the permissions model as implemented, does not have permission to access virtual machines. When attempting to load the inventory, the process throws an exception when it hits the 403 forbidden on /api/virtualization/virtual-machines/?limit=0

##### EXPECTED RESULTS

I guess ideally a 403 permissions denied should be ignored, or warned, but either way the inventory will simply fail to include devices or virtual machines if permission to grant them is not permitted.

##### ACTUAL RESULTS
Exception is thrown and inventory gathering fails.

**Comment by FragmentedPacket** [comment]
Yeah I agree with warning. I will try and get a fix in for this soon.
