### ISSUE TITLE
Request to netbox does not follow redirects on 308

### ISSUE THREAD

**Issue by aslafy-z** [netbox-community/ansible_modules#318]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

Requests does not follow redirects.

##### STEPS TO REPRODUCE

- Configure netbox to use HTTP
- Add nginx ingress controller in front of it with HTTPS and HTTP to HTTPS redirect (default to 308)
- Query netbox and get pagination links

##### EXPECTED RESULTS
```log
Fetching: https://netbox.corp/api/dcim/devices/?limit=0
Fetching: https://netbox.corp/api/dcim/devices/?limit=1000&offset=1000
```

##### ACTUAL RESULTS

```log
Fetching: https://netbox.corp/api/dcim/devices/?limit=0
Fetching: http://netbox.corp/api/dcim/devices/?limit=1000&offset=1000
...
File "/usr/lib64/python3.6/urllib/request.py", line 673, in redirect_request
    raise HTTPError(req.full_url, code, msg, headers, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
```

Digging a bit more into it, it looks like `open_url` ansible function follows redirects by default.
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L1130
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L689
https://github.com/netbox-community/ansible_modules/blob/devel/plugins/inventory/nb_inventory.py#L262

But, as netbox sends back a 308 redirect and urllib has no handler for it, it sends back an error: https://docs.python.org/3/library/urllib.request.html#httpredirecthandler-objects
> Otherwise, raise HTTPError if no other handler should try to handle this URL

A quick fix would be to add `follow_redirect=True` to the `open_url` call.

**Comment by FragmentedPacket** [comment]
If you'd like to implement that fix, I would accept that PR.

I'm in the process of gathering fixes for NetBox 2.9.

**Comment by FragmentedPacket** [comment]
I am actually kind of curious as to why it goes from HTTPS to HTTP though after looking at the info you posted.

I'm wondering if this is something that needs to be changed in your NGINX config or NetBox config to provide the HTTPs in the pagination results?

**Comment by FragmentedPacket** [comment]
Here is some articles regarding my thought process and possible fixes:
https://docs.djangoproject.com/en/2.2/ref/settings/#secure-proxy-ssl-header
https://stackoverflow.com/questions/42818940/django-rest-framework-pagination-links-do-not-use-https
