### ISSUE TITLE
Site data is not getting updated when site was previously created.

### ISSUE THREAD

**Issue by katieneedshelp** [netbox-community/ansible_modules#324]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.9.9

###### Python:
3.8.3

###### Netbox:

2.7.10

###### Collection:

1.0.1

##### SUMMARY

netbox_site module doesn't update an data associated with a site when the site already exists. For the example below, I updated the facility associated with the pre-existing site.

##### STEPS TO REPRODUCE

Site1 was previously created. The facility for Site1 is "Facility ABC." The task should update the facility to "Facility D."

```yaml
- name: "Configure a site in NetBox"
  netbox.netbox.netbox_site:
    netbox_url: "URL"
    netbox_token: "TOKEN"
    data:
      name: Site1
      status: Active
      # tenant:
      facility: Facility D
      time_zone: US/Central
      physical_address: 123 Main Street
      tags: market:A
      contact_name: Bob Smith
    state: present
```

##### EXPECTED RESULTS

ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asn": null,
                "comments": null,
                "contact_email": null,
                "contact_name": "Bob Smith",
                "contact_phone": null,
                "custom_fields": null,
                "description": null,
                "facility": "Facility D",
                "latitude": null,
                "longitude": null,
                "name": "Site1",
                "physical_address": "123 Main Street",
                "region": null,
                "shipping_address": null,
                "slug": null,
                "status": "Active",
                "tags": [
                    "market:A"
                ],
                "tenant": null,
                "time_zone": "US/Central"
            },
            "netbox_token": "",
            "netbox_url": "",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "site Site1 updated",
    "site": {
        "asn": null,
        "circuit_count": null,
        "comments": "",
        "contact_email": "",
        "contact_name": "Bob Smith",
        "contact_phone": "",
        "created": "2020-08-27",
        "custom_fields": {},
        "description": "",
        "device_count": null,
        "facility": "Facility D",
        "id": 12,
        "last_updated": "2020-08-27T18:22:54.980253Z",
        "latitude": null,
        "longitude": null,
        "name": "Site1",
        "physical_address": "123 Main Street",
        "prefix_count": null,
        "rack_count": null,
        "region": null,
        "shipping_address": "",
        "slug": "site1",
        "status": "active",
        "tags": [
            "market:A"
        ],
        "tenant": null,
        "time_zone": "US/Central",
        "virtualmachine_count": null,
        "vlan_count": null
    }
}

##### ACTUAL RESULTS

ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asn": null,
                "comments": null,
                "contact_email": null,
                "contact_name": "Bob Smith",
                "contact_phone": null,
                "custom_fields": null,
                "description": null,
                "facility": "Facility D",
                "latitude": null,
                "longitude": null,
                "name": "Site1",
                "physical_address": "123 Main Street",
                "region": null,
                "shipping_address": null,
                "slug": null,
                "status": "Active",
                "tags": [
                    "market:A"
                ],
                "tenant": null,
                "time_zone": "US/Central"
            },
            "netbox_token": "",
            "netbox_url": "",
            "query_params": null,
            "state": "present",
            "validate_certs": true
        }
    },
    "msg": "site Site1 already exists",
    "site": {
        "asn": null,
        "circuit_count": null,
        "comments": "",
        "contact_email": "",
        "contact_name": "Bob Smith",
        "contact_phone": "",
        "created": "2020-08-27",
        "custom_fields": {},
        "description": "",
        "device_count": null,
        "facility": "Facility ABC",
        "id": 12,
        "last_updated": "2020-08-27T18:22:54.980253Z",
        "latitude": null,
        "longitude": null,
        "name": "Site1",
        "physical_address": "123 Main Street",
        "prefix_count": null,
        "rack_count": null,
        "region": null,
        "shipping_address": "",
        "slug": "site1",
        "status": "active",
        "tags": [
            "market:A"
        ],
        "tenant": null,
        "time_zone": "US/Central",
        "virtualmachine_count": null,
        "vlan_count": null
    }
}

```

```

Thank you!

**Comment by FragmentedPacket** [comment]
Can you test attached PR to see if it resolves your issue?

**Comment by katieneedshelp** [comment]
That fixes my issue! Thanks so much for the quick fix!
