### ISSUE TITLE
Feautres Request : Manage Miscellaneous Extra Config Contexts

### ISSUE THREAD

**Issue by ltDan79** [netbox-community/ansible_modules#331]
##### ISSUE TYPE
 - Feature Idea
###### Ansible:
2.9.123
###### Netbox:
2.8.8
###### Collection:
1.0.1
##### SUMMARY
Hello, I need to manage with Ansible the Extra Config Contexts  (Fron GUI : Ohter->Config Contexts or API : extras/config-contexts)
Would you mind to add this features ?
Thanks

**Comment by FragmentedPacket** [comment]
Thanks for the request @ltDan79.

This is a duplicate issue and the original can be found here https://github.com/netbox-community/ansible_modules/issues/135

I'm not sure when it will get implemented as higher priority stuff comes up, but if you have Python knowledge, I would suggest taking a stab at implementing it and reaching out to me if you need help.

**Comment by ltDan79** [comment]
@FragmentedPacket I will try to do something on my personal time ...
