### ISSUE TITLE
[Feature]: Add 'Custom Fields' Module

### ISSUE THREAD

**Issue by adamwoolhether** [netbox-community/ansible_modules#335]
##### ISSUE TYPE

 - Feature Idea

###### Netbox:

Netbox 2.9

###### Collection:

v1.0.2

##### SUMMARY
Custom fields in Netbox need to be created manually. A module to create new custom fields should be developed.

**Comment by FragmentedPacket** [comment]
@adamwoolhether This isn't possible via the API, only from the admin site so unfortunately at this time this feature cannot be implemented until NetBox exposes this via API.

**Comment by adamwoolhether** [comment]
Hi @FragmentedPacket, as of 2.10.0 custom fields have been exposed to API. can I request this be reopened?

reference: https://github.com/netbox-community/netbox/issues/5274

**Comment by FragmentedPacket** [comment]
Sure. If you want to take a stab at implementing it, that would be great!
