### ISSUE TITLE
[feature request] nb_inventory: use tag slugs instead of tag names

### ISSUE THREAD

**Issue by szelga** [netbox-community/ansible_modules#339]
slugs are used for a lot of things, but not for tags. it would be great for uniformity and filtering by tags.

**Comment by FragmentedPacket** [comment]
I agree with this. There is a PR to fix tags in 2.9 and I want to make this an option (name or slug)

**Comment by jkuzma07** [comment]
#333 updated to extract tags by slug instead of by name. Not sure about how to approach option selection for slug vs name, but at least this adheres to the norm used elsewhere.

**Comment by FragmentedPacket** [comment]
Closing this as @jkuzma07 changed from name to slug. If the use-case arises for possibly using the name, we can implement it at that time.
