### ISSUE TITLE
nb_inventory: add status to host_vars

### ISSUE THREAD

**Issue by 1977er** [netbox-community/ansible_modules#352]
##### SUMMARY
It would be nice to have the Netbox (device/vm) status field variable available as host_vars. 

##### STEPS TO REPRODUCE
```
ansible-inventory -i netbox.yml --host my_test_host
```

##### EXPECTED RESULTS
```
{
...
 "status": {
    "label": "Decommissioning",
    "value": "decommissioning"
 }
...
}
```

##### ACTUAL RESULTS
none yet

**Comment by FragmentedPacket** [comment]
Fixed by #353
