### ISSUE TITLE
Ipam not assigning ip address to devices due to  prefix requires an object to be assigned to it

### ISSUE THREAD

**Issue by jawyoonis** [netbox-community/ansible_modules#358]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Module question
 - Module creation help
 - Documentation update

###### Ansible:
 **2.10.2**

###### Netbox:
 2.9.4

###### Collection:
 **1.1.0**

##### SUMMARY

I am trying assign ips to devices  that have been populated. When  i try to assign primary ip address to management interface it gives me the error that i need to assign object to the prefix. `   },
    "msg": "A prefix and assigned_object is required"
}
`
But if i replace `interface` with `assigned_object` then i am getting this new error where it says that the object is not **serializable.** ` },

    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1602269515.2836826-31280-148169262299539/AnsiballZ_netbox_ip_address.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1602269515.2836826-31280-148169262299539/AnsiballZ_netbox_ip_address.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1602269515.2836826-31280-148169262299539/AnsiballZ_netbox_ip_address.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_ip_address', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_netbox_ip_address_payload_22x2122j/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py\", line 383, in <module>\n  File \"/tmp/ansible_netbox_ip_address_payload_22x2122j/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_ip_address.py\", line 379, in main\n  File \"/tmp/ansible_netbox_ip_address_payload_22x2122j/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 203, in run\n  File \"/tmp/ansible_netbox_ip_address_payload_22x2122j/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 48, in _handle_state_new_present\n  File \"/tmp/ansible_netbox_ip_address_payload_22x2122j/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 90, in _ensure_ip_in_prefix_present_on_netif\n  File \"/tmp/ansible_netbox_ip_address_payload_22x2122j/ansible_netbox_ip_address_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_ipam.py\", line 104, in _get_new_available_ip_address\nAttributeError: 'dict' object has no attribute 'serialize'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
`

##### STEPS TO REPRODUCE

```- name: Ensure that an IP inside Management prefix is attached to Management 0
  netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      prefix: "{{ mgmt_ip_prefix }}"
      assigned_object:
        name: Management0
        device: "{{ item.device_name }}"
    state: present
  register: mgmt_addresses_output
  with_items: "{{ devices.list }}"
- debug: var=mgmt_addresses_output
- name: "Set device primary IP"
  netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.item.device_name }}"
      primary_ip4: "{{ item.ip_address.address }}"
  register: attach_primary_ip_output
  loop: "{{ mgmt_addresses_output.results }}"


```

##### EXPECTED RESULTS
 This code above suppose to assign ip addresses to each device. 

##### ACTUAL RESULTS
 I am getting object error for the prefix. 

```
...
```

**Comment by FragmentedPacket** [comment]
What version of `pynetbox` are you running?

**Comment by jawyoonis** [comment]
i was pynetbox==4.2.5 but i upgrade to 5.1.xx and it actually worked.  But i also change interface to `assigned_object`. The issue was the version of pynetbox i was using.

**Comment by FragmentedPacket** [comment]
Ok great! Glad you got it figured out!

**Comment by jawyoonis** [comment]
Thank you! :)
