### ISSUE TITLE
Extract services data with the compose option?

### ISSUE THREAD

**Issue by syreel** [netbox-community/ansible_modules#362]
### ISSUE TYPE
 - Module question

###### Ansible:
2.9.13

###### Netbox:
2.9.3

###### Collection:
1.1.0

##### SUMMARY
Is it possible to use the compose function to set a variable to data held within the services data?
We have servers that have different ssh ports and the correct port is stored under a service called "SSH" on each device/VM. Is it possible to extract this data using the compose function to set an "ansible_port" variable for ansible to ssh to the correct port?

**Comment by FragmentedPacket** [comment]
I don't think there is a great way to do this using the compose function as you have to get into a list (which SSH can most likely be in a different element).

I would suggest adding `services` to the `group_by` option, and then managing this with group_vars.

You can have an `SSH` group_vars folder and another file in it that specifies the `ansible_port: {{ services | selectattr('name', 'equalto', 'SSH') | map(attribute='port') }}`

This should then map the necessary port there.

You can also try the compose function with getting into a list element and port.
