### ISSUE TITLE
Searching for keywords that include spaces under the api_filter condition does not match

### ISSUE THREAD

**Issue by takmiz** [netbox-community/ansible_modules#363]
##### ISSUE TYPE

 - Bug Report

##### STEPS TO REPRODUCE

I used query command at ansible netbox module.
Searching for keywords that include spaces under the api_filter condition does not result in a hit.
ex) giga 1

I excute playbook with debug mode.
So it was showd bellow results.
```
'name': ['giga'], '_raw_params': ['1']
```
I hope bellow results
```
'name': ['giga 1']
```

This is a playbook and result.

```
cat get_interface.yml
- hosts: localhost
  gather_facts: False
  connection: local
  collections:
    - netbox.netbox
  tasks:
    - debug:
        msg: "{{ query('netbox.netbox.nb_lookup', 'interfaces', api_filter='device=xxxxxx  name=giga 1', api_endpoint='http://localhost:8000', token='xxxxxxxxx') }}"


$ ansible-playbook -i localhost, get_interface.ymll -vvvvv
:
TASK [debug] ********************************************************************************************************************************************************************************************************************************
task path: /home/ubuntu/get_interface.yml:13
Netbox lookup for interfaces to http://localhost:8000 using token 0123456789abcdef0123456789abcdef01234567 filter device=xxxxxxxx  name=giga 1
filter is {'device': ['xxxxxxxxxx'], 'name': ['giga'], '_raw_params': ['1']}
ok: [localhost] => {
    "msg": []
}
META: ran handlers
META: ran handlers
```

**Comment by FragmentedPacket** [comment]
@takmiz You'll need to quote the the value that has spaces in it for it to work.

`"{{ query('netbox.netbox.nb_lookup', 'interfaces', api_filter='device=xxxxxx  name=\"giga 1\"', api_endpoint='http://localhost:8000', token='xxxxxxxxx') }}"`

Let me know if you have any other questions, but going to close the issue at this point.

**Comment by takmiz** [comment]
I've solved the problem!! Thank you!!
