### ISSUE TITLE
nb_lookup: Can't query IP-Address by id

### ISSUE THREAD

**Issue by idle-hae** [netbox-community/ansible_modules#370]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
2.9.13

###### Netbox:
2.9.4

###### Collection:
netbox collection version 1.1.0

##### SUMMARY
I need to query netbox for a specific ip address. I would like to filter this with the id of the ip-address.
This results in an error.

##### STEPS TO REPRODUCE

```yaml
- name: "Get ip-address by id"
  debug:
    msg:  "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                    api_endpoint=netbox_url,
                    api_filter='id=6293',
                    token=netbox_token) }}"
```

##### EXPECTED RESULTS
I expect to get a dict of the queried ip address.

##### ACTUAL RESULTS
```
An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'ValueError'>, original message: A reserved ('id', 'pk', 'limit', 'offset') kwarg was passed. Please remove it try again.
```

**Comment by FragmentedPacket** [comment]
This appears to be an implementation detail with using `pynetbox` and is generated from that library.

It appears we should be able to query by `id`, but not sure the why on not searching by it.

I would open an issue with `pynetbox` and see the reasoning and see if there is a possible workaround.

**Comment by idle-hae** [comment]
Im sorry to open the issue again.

Is it possible that I'm just using the lookup module wrong for what I'm trying to achieve? Maybe there is just an argument, other than api_filter, that I need to use.

I noticed, that one doesn't need to search for a specific address by id, but can define it as part of the path. (e.g. http://netbox/api/ipam/ip-addresses/6293/)

What the api filter does is calling http://netbox/api/ipam/ip-addresses/?id=6293, which leads to a list with one entry.
Is there a way in the lookup module to not search for the address but to query by id? This should return just the specific object and not a list.

According to the documentation I found pynetbox should support this.
https://pynetbox.readthedocs.io/en/latest/endpoint.html
Try to search for "Referencing with an id."

Is there a way to call pynetbox this way with the lookup module?

**Comment by FragmentedPacket** [comment]
I've submitted a PR for this. Are you able to test this?

**Comment by idle-hae** [comment]
Thanks for reconsidering the issue!

Your PR looks like its working.
I tried to add some more parameters after `id` and it seems to handle that gracefully (pynetbox seems to just ignore them).

I noticed just one little thing:
As we are only expecting to get a single object from pynetbox, I think the the return statement should be modified to not generate a list, but a single object.
https://github.com/netbox-community/ansible_modules/blob/bbcefb6cfe134b33dd0062555f4981d109a08661/plugins/lookup/nb_lookup.py#L343

In my test it was sufficient to just remove the square brakets around data
` return data`

**Comment by FragmentedPacket** [comment]
Thanks for testing this!

I tried without creating a list like you said and I think the `lookup` casts it to a list which only provides the keys of the dictionary, but it works fine with `query` so for the sake of backwards compatibility, I will leave it as is.

I will merge this in as well.
