### ISSUE TITLE
Using dns_name for netbox.netbox.nb_inventory for WinRM using Kerberos

### ISSUE THREAD

**Issue by spiglee** [netbox-community/ansible_modules#378]
##### ISSUE TYPE
 - Module question

###### Ansible:
2.9.15

###### Netbox:
2.9.9

###### Collection:
1.1.0

##### SUMMARY
I am trying to use the "netbox.netbox.nb_inventory" plugin as a dynamic inventory with Ansible to pull from Netbox. I have some virtual machines set up in Netbox and appropriate interfaces with IPs and DNS as well that are associated with the virtual machines. I can readily query Netbox using this plugin with ansible-inventory and see all of the details for a virtual machine (including associated interface and dns_name). This all works fine.

My problem is that I need to use the winrm connection method and kerberos as the transport to connect to these windows machines. I can make this work fine from ansible when I manually build out the inventory list using the DNS name / FQDN, but I cannot find a way to grab and use the dns_name when trying to use this Netbox plugin. Kerberos requires the FQDN to work properly. I am able to make NTLM work when sourcing from this Netbox plugin, but that's because IP is OK to use for NTLM. We need to get things working with Kerberos, though. I'd prefer not to use NTLM.

Is there a way with the current plugin to connect via DNS name / FQDN rather than IP? I can't figure out how to accomplish this based on the variables/examples given with this plugin, assuming it's possible in its current release state. Any examples would be greatly welcomed as I'm a bit green still with using Ansible.

**Comment by FragmentedPacket** [comment]
I don't believe there is a current way unless you assign it via something that we include in the inventory.. possibly custom fields or something.

We can look at adding grabbing the `dns_name` from the primary IP address defined for the device.

**Comment by spiglee** [comment]
If there was some way to grab it and then let us use that in place of the IP for making the connection, that would allow using Kerberos as a host connection option with dynamic Ansible inventory. As of right now, I am falling back to using NTLM and it's functional as it is able to work with an IP address, but Kerberos (which is a more preferred and secure means of making a WinRM connection) does have a requirement to connect via FQDN. I'll keep an eye out to see if this comes around as an option in a newer release to connect via FQDN in place of IP.

Thanks.

**Comment by FragmentedPacket** [comment]
For sure. I will try and get something going this weekend and have you test it once it's ready and make sure it works for what you need.

**Comment by nahun** [comment]
I was looking at doing the same thing so that the Ansible hostname = primary IP dns_name. Similar to what I did in the `extract_name` method for the virtual_chassis_name option in #383 (I understand this feature and virtual_chassis_name would be mutually exclusive). This is mostly because I'm migrating to Netbox and some of my current playbooks and roles depend on the `inventory_hostname` being the FQDN. I was going to add a task to lookup the dns_name using the primary IP ID to all my playbooks/roles, but if this feature gets implemented I would probably use it as well.

**Comment by cpmills1975** [comment]
I'm wondering whether this is better served by asking for the primary_ip to include the assigned with the dns_name in upstream NetBox when retrieving a device or VM (I'm assuming that is the first port of call for the inventory plugin).  I am receiving Webhooks from NetBox in to an Ansible playbook and while this doesn't use the inventory plugin, it does include the device's primary_ip. I then perform a lookup using the lookup plugin to retrieve the dns_name for the assigned IP. It would be so much easier if the dns_name was included with the IP address from the outset and for, what, 100 additional bytes, it seems like it wouldn't add too much to the webhook/device lookup payload.

**Comment by nahun** [comment]
So you mean getting the NetBox API modified to return the dns_name with the primary_ip information? That would be nice for sure, needs an issue created in that project. Until then, I hope this solution works for the inventory plugin.
