### ISSUE TITLE
Feature request: custom fields for nb_query

### ISSUE THREAD

**Issue by hyudra** [netbox-community/ansible_modules#379]
Dear all,

I'd like to request to get custom fields choice ID from label. Is it possible? I looked into code and seem there's no support for '/extras/_custom_field_choices/'

**Comment by FragmentedPacket** [comment]
Let me look into this and I'll get back to you on if we can accomplish this.

**Comment by nahun** [comment]
Netbox 2.10 makes big changes to custom fields and the API has changed with `/extras/_custom_field_choices/` no longer existing. When creating/updating you no longer need the choice ID for a custom field, just the value. Example with pynetbox:

```python
import pynetbox
nb = pynetbox.api(NB_URL, token=NB_TOKEN)
nb.dcim.devices.create({
    "name": "test",
    "device_role": 1,
    "device_type": 1,
    "status": "active",
    "site": 1,
    "custom_fields": {
        "environment": "production"
    }
})
```

**Comment by hyudra** [comment]
> Netbox 2.10 makes big changes to custom fields and the API has changed with `/extras/_custom_field_choices/` no longer existing. When creating/updating you no longer need the choice ID for a custom field, just the value. Example with pynetbox:
> 
> ```python
> import pynetbox
> nb = pynetbox.api(NB_URL, token=NB_TOKEN)
> nb.dcim.devices.create({
>     "name": "test",
>     "device_role": 1,
>     "device_type": 1,
>     "status": "active",
>     "site": 1,
>     "custom_fields": {
>         "environment": "production"
>     }
> })
> ```

I see. thanks for information.

By the way, is there anyway to add 'Config Context' field on Devices and VMs? I looked into the current code and seem it's not supported yet.

**Comment by FragmentedPacket** [comment]
There is a PR open for it, but I think it needs a bit more work to conform to current modules.

PR is #364

**Comment by FragmentedPacket** [comment]
I'm going to close this issue as there is a current issue opened for the `config_ contexts`.

PR #364 and Issue #135
