### ISSUE TITLE
White space returned 

### ISSUE THREAD

**Issue by Abulhallaj** [netbox-community/ansible_modules#392]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
ansible 2.9.15
###### Netbox:
netbox (v2.9.10)

###### Collection:
v1.1.0

##### SUMMARY
White space returned in device_role names and it's cause error when using on ansible-playbook.
I read a lot of thread about this bug here: https://github.com/netbox-community/ansible_modules/issues/59 and https://github.com/ansible/ansible/pull/53384 and all other linked threads but not find the solution!

##### STEPS TO REPRODUCE
netbox_inv.yml
```yaml
---
plugin: netbox
api_endpoint: https://xxxxxxxx.xxx/
token: xxx
validate_certs: False
config_context: False
group_by:
  - device_roles
```

then using command below to see result:
ansible-inventory -v --list -i netbox_inv.yml 

##### EXPECTED RESULTS
    "device_roles_Core-Switches": {
        "hosts": [
            "Core-xxx_3850(SW1)", 
            "Core-xxx", 
            "xxxx-Core_3850(SW1)", 
            "xxxx-Core_3850(SW2)", 
            "xxyy-Core(SW1)", 
            "xxyy-Core(SW2)", 
            "xxyy-Core(SW3)"
        ]
    },
##### ACTUAL RESULTS
    "device_roles_Core Switches": {
        "hosts": [
            "Core-xxx_3850(SW1)", 
            "Core-xxx", 
            "xxxx-Core_3850(SW1)", 
            "xxxx-Core_3850(SW2)", 
            "xxyy-Core(SW1)", 
            "xxyy-Core(SW2)", 
            "xxyy-Core(SW3)"
        ]
    },

##### output of playbook
ansible-playbook create_config.yml 
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see
details
[WARNING]: Could not match supplied host pattern, ignoring: device_role_Core
[WARNING]: Could not match supplied host pattern, ignoring: Switches

PLAY [Create config using netbox] ****************************************************************
skipping: no hosts matched

PLAY RECAP ***************************************************************************************

**Comment by FragmentedPacket** [comment]
This might be using the built-in Ansible NetBox inventory plugin.

Try changing `plugin` to `plugin: netbox.netbox.nb_inventory`. You can also just install `ansible-base` rather than `ansible` and then install the collection to replicate the proper behavior as well.

**Comment by Abulhallaj** [comment]
changing plugin name cause the below error:
plugin: netbox.netbox.nb_inventory

abulhallaj@ansible:~/Ansible$ ansible-inventory -v --list -i netbox_inv.yml
```
Using /home/abulhallaj/Ansible/ansible.cfg as config file
[WARNING]:  * Failed to parse /home/abulhallaj/Ansible/netbox_inv.yml with auto
plugin: No module named typing
[WARNING]:  * Failed to parse /home/abulhallaj/Ansible/netbox_inv.yml with yaml
plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /home/abulhallaj/Ansible/netbox_inv.yml with ini
plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is a
YAML file.
[WARNING]: Unable to parse /home/abulhallaj/Ansible/netbox_inv.yml as an
inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}

```

**Comment by Abulhallaj** [comment]
Removing **ansible** and installing **ansible-base** solve the problem!

Thanks @FragmentedPacket
