### ISSUE TITLE
self.version 2.10 seen as lower than 2.9

### ISSUE THREAD

**Issue by vkantsev** [netbox-community/ansible_modules#395]
##### ISSUE TYPE
* Bug Report

##### SOFTWARE VERSIONS
Ansible:
2.9.15

Netbox:
2.10.1

Collection:
1.1.0
 
##### SUMMARY
Version check for `v2.10` returns `< 2.9` in 
https://github.com/netbox-community/ansible_modules/blob/bf69006da7244244efaad4df417f2ce5cc008fc1/plugins/module_utils/netbox_ipam.py#L60 
due to 
https://github.com/netbox-community/ansible_modules/blob/bf69006da7244244efaad4df417f2ce5cc008fc1/plugins/module_utils/netbox_utils.py#L476

**Comment by FragmentedPacket** [comment]
Thank you for this! I will try and get this fixed tonight and am planning to cut a new release soon as well.

**Comment by vkantsev** [comment]
I thank you Sir 🎩 .
