### ISSUE TITLE
Feature request: Add group_by status

### ISSUE THREAD

**Issue by slinderud** [netbox-community/ansible_modules#397]
##### ISSUE TYPE
 - Feature Idea

###### Ansible:
ansible 2.10.4

###### Netbox:
Netbox 2.10.1

###### Collection:
Devel

##### SUMMARY
Is it possible to have group_by work on the status field?
I've tested with the devel branch and it does not look like #353 and #359 fixes this.

**Comment by FragmentedPacket** [comment]
You're right. I completely missed that. I'm thinking of having the group names model after the **value** of the status as it's lower case and somewhat matches the others.

Example:
```
      "status": {
        "value": "active",
        "label": "Active"
      },
```

Group name would be: `status_active`. What is your opinion? The **value** or **label**?

@1977er what is your opinion?

**Comment by slinderud** [comment]
I think value would be the most consistent choice.

Thanks! Really enjoy your work on all of this :)

**Comment by 1977er** [comment]
I would opt for `value`, too.
