### ISSUE TITLE
Tag IDs can't be pushed with the naming  

### ISSUE THREAD

**Issue by amaizenshtein** [netbox-community/ansible_modules#407]
I'm running Netbox - v2.10.2 - 2020-12-21
Python 3.8
I've observed when trying to push Tags to devices via the below playbook using names, it popus errors shown below

VAR File:

gcp_devices:
  - name: "iot-dev-297420-us-c1-fw02.gcp.xxx.xxx"
    site: "GCP"
    device_type: "panos-vm"
    tenant: gcp_panos
    platform: panos
    device_role: "Firewall"
    tag: [gcp,DEV,QA,Staging]
    status: Active
    inband_management_ip: "172.30.238.195"
    
Playbook TASK:

- name: "TASK 2: CREATE DEVICE WITHIN NETBOX"
      netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          name: "{{ device.name }}"
          device_type: "{{ device.device_type }}"
          device_role: "{{ device.device_role }}"
          platform: "{{ device.platform }}"
          tenant: "{{ device.tenant }}"
          tags: "{{ device.tag }}"
          custom_fields:
             inband_management_ip: "{{ device.inband_management_ip }}"
          site: "{{ device.site }}"
          status: "{{ device.status }}"
        state: present
      with_items:
        - "{{ gcp_devices }}"
      loop_control:
        loop_var: device
      when: "device.name not in nb_device_output"
      register: nb_device
      
      
Errors:
strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  warnings.warn(\nTraceback (most recent call last):\n  File \"/Users/amaizensht/.ansible/tmp/ansible-tmp-1609947021.722891-47932-88713551337636/AnsiballZ_netbox_device.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/amaizensht/.ansible/tmp/ansible-tmp-1609947021.722891-47932-88713551337636/AnsiballZ_netbox_device.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/amaizensht/.ansible/tmp/ansible-tmp-1609947021.722891-47932-88713551337636/AnsiballZ_netbox_device.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netbox_community.ansible_modules.plugins.modules.netbox_device', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/2r/84_y4y1120q7zyrbmwbj0sbrb10jbr/T/ansible_netbox_device_payload_033pvr85/ansible_netbox_device_payload.zip/ansible_collections/netbox_community/ansible_modules/plugins/modules/netbox_device.py\", line 267, in <module>\n  File \"/var/folders/2r/84_y4y1120q7zyrbmwbj0sbrb10jbr/T/ansible_netbox_device_payload_033pvr85/ansible_netbox_device_payload.zip/ansible_collections/netbox_community/ansible_modules/plugins/modules/netbox_device.py\", line 262, in main\n  File \"/var/folders/2r/84_y4y1120q7zyrbmwbj0sbrb10jbr/T/ansible_netbox_device_payload_033pvr85/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_dcim.py\", line 55, in __init__\n  File \"/var/folders/2r/84_y4y1120q7zyrbmwbj0sbrb10jbr/T/ansible_netbox_device_payload_033pvr85/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 470, in __init__\n  File \"/var/folders/2r/84_y4y1120q7zyrbmwbj0sbrb10jbr/T/ansible_netbox_device_payload_033pvr85/ansible_netbox_device_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py\", line 843, in _find_ids\nUnboundLocalError: local variable 'temp_dict' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

When I moved from Python 3.8 Python 3.9.1
I was able to run playbook using tag names but was giving me errros when using tag IDs as numbers

**Comment by FragmentedPacket** [comment]
I closed the other one as I believe it was a duplicate.

Working on this now.

**Comment by FragmentedPacket** [comment]
@amaizenshtein Do you mind testing the PR?

**Comment by amaizenshtein** [comment]
What needs to be done on this? should I upgrade Netbox or Python  to any
new version?

On Sat, Jan 9, 2021 at 6:44 AM Mikhail Yohman <notifications@github.com>
wrote:

> @amaizenshtein
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_amaizenshtein&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=m_UBS4aFnEAMCyF4fuekJIPk2W_RDBzGhHiLG0xltRE&s=h7dbQuFmLYIgE2XJlinzSiJarNRsQRVNQV__2WxoHFY&e=>
> Do you mind testing the PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_netbox-2Dcommunity_ansible-5Fmodules_issues_407-23issuecomment-2D757095460&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=m_UBS4aFnEAMCyF4fuekJIPk2W_RDBzGhHiLG0xltRE&s=9N_mI--jTD_kZRRB3r5jHpfj1BB-iGKC5rDqeTUIYb0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHO6W7FSYO5HKHBQVOCJDPTSY7NJHANCNFSM4VXXJ44A&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=m_UBS4aFnEAMCyF4fuekJIPk2W_RDBzGhHiLG0xltRE&s=WFQhiuUL332NPPA-bGMJR9k7a-EkLVL_mmVJEYXneGU&e=>
> .
>


-- 

*Alex Maizenshtein* *| Sr Principal Network Engineer | 3 x CCIE #34560
(R&S/SP/DC)*

M: +972-54-6501229*   | *T: +972-74-7265076*  | **www.paloaltonetworks.com
<http://www.paloaltonetworks.com/>*

*[image: id:image001.png@01D3087F.63E335E0]*

**Comment by FragmentedPacket** [comment]
There are instructions here on how to pull down the PR and build.

https://netbox-ansible-collection.readthedocs.io/en/latest/getting_started/installation.html#build-from-source-pull-request

**Comment by amaizenshtein** [comment]
Hi Mikhail,

In my setup I have fully production system, not sure if this build can
somehow by mistake corrupt the existing one, I would prefer to roll out a
Dev Netbox and try it there
This part might take some time, if anyone can test it before it would be
perfect

On Sun, Jan 10, 2021 at 5:11 AM Mikhail Yohman <notifications@github.com>
wrote:

> There are instructions here on how to pull down the PR and build.
>
>
> https://netbox-ansible-collection.readthedocs.io/en/latest/getting_started/installation.html#build-from-source-pull-request
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__netbox-2Dansible-2Dcollection.readthedocs.io_en_latest_getting-5Fstarted_installation.html-23build-2Dfrom-2Dsource-2Dpull-2Drequest&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=LeVGWn4ayCXSUeQo22DBLZj-epSRKvVlF8f3rNhh6Oc&s=EJqA0_lSaoAETXG9mI91HxqIdGGrdrG9yn9TM2ZPm3Y&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_netbox-2Dcommunity_ansible-5Fmodules_issues_407-23issuecomment-2D757405562&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=LeVGWn4ayCXSUeQo22DBLZj-epSRKvVlF8f3rNhh6Oc&s=mv6EJXNp-mJBn-XjSIOGKwyYO_g4THF3IHP82NJtRhI&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHO6W7AZEZTNYQAGHIQF36TSZELELANCNFSM4VXXJ44A&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=LeVGWn4ayCXSUeQo22DBLZj-epSRKvVlF8f3rNhh6Oc&s=JNXYfQLBKUFuSOIk-Blz8iOl9KxRhYPEdcn97RUaMN8&e=>
> .
>


-- 

*Alex Maizenshtein* *| Sr Principal Network Engineer | 3 x CCIE #34560
(R&S/SP/DC)*

M: +972-54-6501229*   | *T: +972-74-7265076*  | **www.paloaltonetworks.com
<http://www.paloaltonetworks.com/>*

*[image: id:image001.png@01D3087F.63E335E0]*

**Comment by FragmentedPacket** [comment]
No problem. I tested this locally as well as added tests for it.

I think that is good enough for now, but typically try and just validate with the user.

I will go ahead and merge the PR and will try and cut a new release this weekend that you can use.

**Comment by amaizenshtein** [comment]
Awesome, thanks!

On Sun, 10 Jan 2021 at 9:12 Mikhail Yohman <notifications@github.com> wrote:

> Closed #407
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_netbox-2Dcommunity_ansible-5Fmodules_issues_407&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=3_MzOhXWjL9Sj6_SN_c7pLW0Cd2p-xQf-g67DaUizR4&s=75JJxQRhRBDX4PtaNawyVM96PZCMOUPkGkUtahTLTMU&e=>
> via #409
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_netbox-2Dcommunity_ansible-5Fmodules_pull_409&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=3_MzOhXWjL9Sj6_SN_c7pLW0Cd2p-xQf-g67DaUizR4&s=WUB7VYXLMiVHsQyyHmkFEmLTcHit2OsLfV0TiGLy4ko&e=>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_netbox-2Dcommunity_ansible-5Fmodules_issues_407-23event-2D4187759808&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=3_MzOhXWjL9Sj6_SN_c7pLW0Cd2p-xQf-g67DaUizR4&s=o1eL4o8Vryzy5AJd5CconE_-OxJl63lEfVm6UQm6xzU&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHO6W7GELI3CJWQGNQ3P3XTSZFHMRANCNFSM4VXXJ44A&d=DwMCaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=OC9usBOsJkDotOENUahZfEXlZ6FsNm6Og7thc87eFUs&m=3_MzOhXWjL9Sj6_SN_c7pLW0Cd2p-xQf-g67DaUizR4&s=Zh1QeGtOH5GIwVSQ-PvFgTsQIBp09wQGv7zwyzK-2Rk&e=>
> .
>
-- 

*Alex Maizenshtein* *| Sr Principal Network Engineer | 3 x CCIE #34560
(R&S/SP/DC)*

M: +972-54-6501229*   | *T: +972-74-7265076*  | **www.paloaltonetworks.com
<http://www.paloaltonetworks.com/>*

*[image: id:image001.png@01D3087F.63E335E0]*
