### ISSUE TITLE
Feature: Create prefix if not present option when using netbox_ip_address

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/ansible_modules#417]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:
2.10.4

###### Netbox:
2.10.3

###### Collection:
1.2.1

##### SUMMARY
Add a new module option for netbox_ip_address named something like `create_prefix` as a boolean field or `prefix_state` using the same options as the IP's state option for said module.

##### COMMENTS
Users can do this themselves by first calculating the prefix and running against the prefix module, so I would get the argument that this may not be a huge ROI feature.  I figured I would throw the feature up to see what people think.

**Comment by nahun** [comment]
My initial gut reaction is to not implement this feature since creating with the prefix module beforehand should be pretty simple. But thats just my initial reaction.

**Comment by sc68cal** [comment]
I am usually going the other way, where I explicitly create prefixes first, then the VLANs they are assigned to, then the individual IP assignments.
