### ISSUE TITLE
Enhancement: netbox_rack_group shall support parent (rack group) relationship

### ISSUE THREAD

**Issue by odysseus107** [netbox-community/ansible_modules#433]
##### ISSUE TYPE

 - Feature Idea

###### Ansible:
2.9.9

###### Netbox:
2.10.4

###### Collection:
2.0.0

##### SUMMARY
The Netbox UI supports setting a parent entry relationship when editing a rack group.

##### EXPECTED RESULTS
Using a property like 'parent_rack_group' is possible and adds the dependency between two rack groups

##### ACTUAL RESULTS
The property is not available

**Comment by rodvand** [comment]
Closing this as rack groups has been deprecated since 2.11.
