### ISSUE TITLE
Netbox query using nb_lookup fails with requests.exceptions.MissingSchema

### ISSUE THREAD

**Issue by vsvasilev** [netbox-community/ansible_modules#446]
##### ISSUE TYPE

 - Module question

###### Ansible:

ansible 2.10.6
  config file = None
  configured module search path = ['/home/vsvasilev/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vsvasilev/.pyenv/versions/3.9.2/lib/python3.9/site-packages/ansible
  executable location = /home/vsvasilev/.pyenv/versions/3.9.2/bin/ansible
  python version = 3.9.2 (default, Feb 22 2021, 05:11:29) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

###### Netbox:

2.6.7

###### Collection:

❯ ansible-galaxy collection list | grep netbox
netbox.netbox                 2.0.0  

##### SUMMARY

Failed to query Netbox using netbox.netbox.nb_lookup module.

##### STEPS TO REPRODUCE

```yaml
---

- name: query data from netbox
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:

    - name: "Get sites"
      debug:
        msg: "{{ query('netbox.netbox.nb_lookup', 'sites', api_endpoint='{{ netbox_url }}', token='{{ netbox_token }}') }}"

...
```

##### EXPECTED RESULTS

Get information about sites configured in Netbox instance.

##### ACTUAL RESULTS

Playbook failed with Error <class 'requests.exceptions.MissingSchema'>.

```
❯ ansible-playbook netbox-query.yml --vault-id ~/.vaultpass
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [query data from netbox] **********************************************************************************************************************************************************************************************************************************************************************************

TASK [Obtain prefixes] *****************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'requests.exceptions.MissingSchema'>, original message: Invalid URL '{{ netbox_url }}/api/dcim/sites/': No schema supplied. Perhaps you meant http://{{ netbox_url }}/api/dcim/sites/?"}
```

**Comment by FragmentedPacket** [comment]
You wouldn't quote or use Jinja brackets for vars.

`"{{ query('netbox.netbox.nb_lookup', 'sites', api_endpoint=netbox_url, token=netbox_token) }}"`

**Comment by FragmentedPacket** [comment]
Did this work for you?

**Comment by vsvasilev** [comment]
Hello Mikhail,

Thanks for the update! Sorry for the late update I just managed to test it. Seems like the error I get now is related to SSL certs:

```yaml
TASK [Get sites] ********************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'netbox.netbox.nb_lookup'. Error was a <class 'requests.exceptions.SSLError'>, original message: HTTPSConnectionPool(host='hostname', port=443): Max retries exceeded with url: /api/dcim/sites/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))"}
```

It seems that "validate_certs: False" is not a valid option for debug task so I have to look for another way to disable SSL cert validation in my case. Once I figure this out I should be able to check again and see if the nblookup operates properly in my case. Will keep you updated.

**Comment by vsvasilev** [comment]
Hello Mikhail,

I got it working using the "validate_certs=false" option. The working task looks like this:

```yaml
    - name: "Get sites"
      debug:
        msg: "{{ query('netbox.netbox.nb_lookup', 'sites',
                       api_endpoint=netbox_url,
                       token=netbox_token,
                       validate_certs=false) }}"
```

It took me sometime to figure this out due to improper [documentation](https://docs.ansible.com/ansible/latest/collections/netbox/netbox/nb_lookup_lookup.html) on the nb_lookup which states that "validate_certs" should be of type string while actually it is boolean. Thanks again for the help, I'm closing out this issue.
