### ISSUE TITLE
[Feature]: Group hosts by tenant group

### ISSUE THREAD

**Issue by karlism** [netbox-community/ansible_modules#447]
##### ISSUE TYPE
 - Feature Idea

###### Ansible:

```
ansible 2.9.17
  config file = /home/petruha/.ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Oct 13 2020, 09:04:17) [Clang 10.0.1 ]
```

###### Netbox:

2.9.11

###### Collection:

2.1.0

##### SUMMARY

Currently it is not possible to group hosts by tenant group, only by tenant. It would be nice to be able to group hosts by `tenant_group`, similar how it is already possible to group them by `cluster_group`.

**Comment by rodvand** [comment]
I'm closing this out as a stale issue. Feel free to re-open if you have more details or a PR ready.
