### ISSUE TITLE
nb_inventory lacks compatibility with ansible.netcommon 2.0.x 

### ISSUE THREAD

**Issue by riege-burghardt** [netbox-community/ansible_modules#452]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
ansible-2.10.5 and 2.10.6 (both tested)
ansible-base-2.10.5 and 2.10.6

###### Netbox:
not relevant but 2.10.4

###### Collection:
ansible.netcommon 2.0.0 (here is the relation to the problem, downgrade to version 1.5.0 works)
netbox.netbox 2.1.0

##### SUMMARY
ansible.netcommon 2.0.0 was released about one day ago. In my Vagrant configuration the Ansible version is set but other modules and collections are updated to the latest release. I am using a Centos 7 environment.

I had a VM running with above versions, especially the collection: ansible.netcommon 1.5.0. Everything was fine.

But a new VM with ansible.netcommon 2.0.0 does not even make a http(s) connect to the Netbox instance. The inventory is empty in this setup.

I guess that the collection of netbox.netbox is missing compatibility with the new version of ansible.netcommon.

##### STEPS TO REPRODUCE

Install Ansible 2.10.x with netbox.netbox 2.1.0 and latest dependencies. This will bring ansible.netcommon 2.0.x.

file: inventories/vault_netbox_inventory.yml
```yaml
---
plugin: netbox.netbox.nb_inventory
api_endpoint: https://<your_netbox>
validate_certs: True
config_context: False
token: <your_secret>
```

Command: 
> ansible-inventory -v -i inventories/vault_netbox_inventory.yml --list

##### EXPECTED RESULTS

```
Using /home/vagrant/.ansible.cfg as config file
Fetching: https://<your_netbox>/api/docs/?format=openapi
Fetching: https://<your_netbox>/api/dcim/devices/?limit=0&exclude=config_context
Fetching: https://<your_netbox>/api/virtualization/virtual-machines/?limit=0&exclude=config_context
Fetching: https://<your_netbox>/api/dcim/sites/?limit=0
Fetching: https://<your_netbox>/api/dcim/regions/?limit=0
Fetching: https://<your_netbox>/api/tenancy/tenants/?limit=0
Fetching: https://<your_netbox>/api/dcim/racks/?limit=0
Fetching: https://<your_netbox>/api/dcim/rack-groups/?limit=0
Fetching: https://<your_netbox>/api/dcim/device-roles/?limit=0
Fetching: https://<your_netbox>/api/dcim/platforms/?limit=0
Fetching: https://<your_netbox>/api/dcim/device-types/?limit=0
Fetching: https://<your_netbox>/api/dcim/manufacturers/?limit=0
Fetching: https://<your_netbox>/api/virtualization/clusters/?limit=0
Fetching: https://<your_netbox>/api/ipam/services/?limit=0
{
    "_meta": {
        "hostvars": {
           <content of several systems>
        }
    }
}
```

##### ACTUAL RESULTS

```
Using /home/vagrant/.ansible.cfg as config file
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}
```

There is no error message on the output and tcpdump shows no single request to our netbox instance. The output pops up immediately while the working environment takes some seconds to fulfill the request.

**Comment by FragmentedPacket** [comment]
Thank you. I will investigate this further to see what changed, and change the pinning of versions as well.

**Comment by nahun** [comment]
I submitted a PR for the fix, but the ansible.netcommon collection pushed a breaking change with their module_utils: ansible-collections/ansible.netcommon@8cda0e6
