### ISSUE TITLE
please provide an example for nb_inventory for the use with tower with token

### ISSUE THREAD

**Issue by RobVerduijn** [netbox-community/ansible_modules#456]
please provide an example on how to use the nb_inventory in ansible tower.
using an encrypted toke (secret) since we don't want everybody to be able to see the token.

Rob

**Comment by maxhoesel** [comment]
This blogpost from Redhat goes into detail on how to accomplish this: https://www.ansible.com/blog/using-an-inventory-plugin-from-a-collection-in-ansible-tower. Just replace the fields with a single entry for NETBOX_TOKEN and you should be good to go.

**Comment by RobVerduijn** [comment]
exactly what I was looking for

Thanks

**Comment by RobVerduijn** [comment]
Maybe it would be nice to share this knowledge in the readme

**Comment by FragmentedPacket** [comment]
It can be served in existing docs, and add steps for adding the custom credential into Tower.

**Comment by maxhoesel** [comment]
I created a little snippet that could be added to the docs. Unfortunately, I have no experience with rst as a format, so it's in Markdown. If anyone wants to convert it to rst and include it in a PR, feel free to do so,

https://gist.github.com/maxhoesel/8ca46bdca23c74af7ba9efa3024a87e4
