### ISSUE TITLE
Missing 'parent' and 'label' paramaters in netbox.netbox.netbox_inventory_item

### ISSUE THREAD

**Issue by igloo777** [netbox-community/ansible_modules#464]
Hi all! 
I miss for the parameters 'parent' and 'label', because it helps to model parent/child relations between let's say module, slot of module and transceiver. 

`Unsupported parameters for (netbox.netbox.netbox_inventory_item) module: parent found in data. Supported parameters include: asset_tag, description, device, discovered, manufacturer, name, part_id, serial, tags`

Is it possible to add these parameters?

**Comment by FragmentedPacket** [comment]
Yes. It's totally possible. Not sure if I will have time to implement it, but we have docs on it. https://netbox-ansible-collection.readthedocs.io/en/latest/getting_started/contributing/modules/update_module.html

Another PR was merged recently that would is similar to the `parent` option you're requesting. #460

**Comment by rodvand** [comment]
Added in https://github.com/netbox-community/ansible_modules/pull/682
