### ISSUE TITLE
Feature Request Add missing IPAM - Prefix/VLAN Roles modules

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/ansible_modules#467]
IPAM - Prefix/VLAN Roles are probably an easy module to add that is currently missing.

**Comment by mathieu-mp** [comment]
Sorry if I am off-topic, but didn't you miss [netbox_ipam_role](https://netbox-ansible-collection.readthedocs.io/en/latest/plugins/netbox_ipam_role_module.html) ?

**Comment by ryanmerolle** [comment]
No I think I somehow just missed this.  Not sure how.  And funny enough @FragmentedPacket followed me down the rabbit hole!

Sorry for that!
