### ISSUE TITLE
netbox2.10 interface tags are wrong in inventory.

### ISSUE THREAD

**Issue by ThomasADavis** [netbox-community/ansible_modules#472]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

ansible v2.10

###### Netbox:

v2.10.5

###### Collection:

v3.0

##### SUMMARY

Tags in interfaces are returned as raw objects, instead of being processed into an array.

This makes ansible to not work in this form:

```
  - item.name == 'ovirtmgmt'
  - "'default' not in item.tags"
```
and templates to also fail.
```
{% if 'default' in item.tags %}
```
where item = interface description with an interface tag.

##### EXPECTED RESULTS

```
  "tags":[
"default"
]
```
##### ACTUAL RESULTS

```
                        "tags": [
                            {
                                "color": "9e9e9e",
                                "id": 130,
                                "name": "default",
                                "slug": "default",
                                "url": "http://netbox/api/extras/tags/130/"
                            }
                        ],
```

**Comment by FragmentedPacket** [comment]
Closed via #473
