### ISSUE TITLE
Cannot group by tags in Netbox v2.10.4

### ISSUE THREAD

**Issue by simo735** [netbox-community/ansible_modules#474]
##### ISSUE TYPE
 - Bug Report

###### Ansible:

ansible 2.8.5
ansible 2.9.18
###### Netbox:
v2.10.4

###### Collection:
With Ansible 2.8.5 > tested with netbox native plugin
With Ansible 2.9.18 > 3.0.0 (last version)

##### SUMMARY

From Ansible i can create a dynamic inventory and group them by: sites, device_roles, manufacturers...etc this not works with tags.
I found that this issue was reported on netbox v2.9 and the issue has been closed but it still not working on v2.10.

##### STEPS TO REPRODUCE

1- Add add entries in netbox (devices,tags,location...etc )
2- type those command: (to test with collection use netbox.netbox line)

```yaml

ansible-galaxy collection install netbox.netbox


vi netbox_inventory.yml
---
plugin: netbox
# plugin: netbox.netbox
api_endpoint: YOUR_NETBOX_URL
token: YOUR_TOKEN
validate_certs: False
config_context: False
group_by:
  - tags

ansible-inventory -v --list -i netbox_inventory.yml
```

##### EXPECTED RESULTS

A list of my hosts grouped by tags
##### ACTUAL RESULTS

```
 [WARNING]:  * Failed to parse /home/user/netbox_inventory.yml with auto plugin: sequence item 1: expected string or Unicode, dict found
 [WARNING]:  * Failed to parse /home/user/netbox_inventory.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
 [WARNING]:  * Failed to parse /home/user/netbox_inventory.yml with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.
 [WARNING]: Unable to parse /home/user/netbox_inventory.yml as an inventory source
 [WARNING]: No inventory was parsed, only implicit localhost is available
```

**Comment by hyudra** [comment]
Your plugin will not use version 3.0.0, it'll use from base Ansible. 
You need to use

`plugin: netbox.netbox.nb_inventory`

Also, I think you may need to remove
`---`

**Comment by simo735** [comment]
@hyudra  thank you, i install the collection and i tried this solution but i have this error : 

[WARNING]:  * Failed to parse /home/user/netbox_inventory.yml with auto plugin: No module named typing
[WARNING]:  * Failed to parse /home/user/netbox_inventory.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /home/adm-moelidrissi/netbox_inventory.yml with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.
[WARNING]: Unable to parse /home/user/netbox_inventory.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
{
    "_meta": {
        "hostvars": {}
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    }
}

**Comment by hyudra** [comment]
Try remove the 3 dashes at the top

**Comment by simo735** [comment]
@hyudra  i did it but unfortunately i get the same error

**Comment by hyudra** [comment]
Hmm. I'm not sure then.
I ever use this with ansible Tower/AWX. Not sure that it can use normally.

**Comment by knorring** [comment]
@simo735 The latest version of Ansible has an issue with the `group_by` plugin configuration. More specifically the `choices` keyword do not work with `list` options.

https://github.com/netbox-community/ansible_modules/blob/5cf6f49d2e3284180de8dc5c2d3714271f71b537/plugins/inventory/nb_inventory.py#L111-L140

A fix/feature for this issue has already been submitted to the Ansible repo: https://github.com/ansible/ansible/pull/74267

The related issue: https://github.com/ansible/ansible/issues/74225

**Comment by knorring** [comment]
A temporary fix is to remove the following lines from `ansible_modules/plugins/inventory/nb_inventory.py`:

https://github.com/netbox-community/ansible_modules/blob/5cf6f49d2e3284180de8dc5c2d3714271f71b537/plugins/inventory/nb_inventory.py#L114-L139

On my local installation the file is located here: `~/.ansible/collections/ansible_collections/netbox/ansible_modules/plugins/inventory/nb_inventory.py`.

This will disable verification of any values in the `group_by` setting.

I don't think you need the `---`.

**Comment by FragmentedPacket** [comment]
Did all the issues in this thread get resolved?

**Comment by S0LERA** [comment]
Hello,
I opened yesterday this issue related with the change of rack-groups and locations. [/netbox-community/ansible_modules/issues/520](/netbox-community/ansible_modules/issues/520)

I upgraded this morning to the 3.1.1 version and then the error of the first post appears again.

```
[WARNING]:  * Failed to parse /home/rundeck/data/proyectos/netbox/inventario/inventory_netbox with
ansible_collections.netbox.netbox.plugins.inventory.nb_inventory plugin: Invalid value "['tenant']" for configuration option "plugin_type:
inventory plugin: ansible_collections.netbox.netbox.plugins.inventory.nb_inventory setting: group_by ", valid values are: ['sites', 'site',
'location', 'tenants', 'tenant', 'racks', 'rack', 'rack_group', 'rack_role', 'tags', 'tag', 'device_roles', 'role', 'device_types', 'device_type',
'manufacturers', 'manufacturer', 'platforms', 'platform', 'region', 'cluster', 'cluster_type', 'cluster_group', 'is_virtual', 'services',
'status']
```

With this solution it works fine.
> 
> 
> A temporary fix is to remove the following lines from `ansible_modules/plugins/inventory/nb_inventory.py`:
> 
> https://github.com/netbox-community/ansible_modules/blob/5cf6f49d2e3284180de8dc5c2d3714271f71b537/plugins/inventory/nb_inventory.py#L114-L139
> 
> On my local installation the file is located here: `~/.ansible/collections/ansible_collections/netbox/ansible_modules/plugins/inventory/nb_inventory.py`.
> 
> This will disable verification of any values in the `group_by` setting.
> 
> I don't think you need the `---`.

**Comment by simo735** [comment]
@knorring  your solution works thank you.
@FragmentedPacket all the issue had been resolved.
