### ISSUE TITLE
netbox_cluster (and probably other modules) fail with ansible 2.10 and mitogen 0.3.0rc1

### ISSUE THREAD

**Issue by philfry** [netbox-community/ansible_modules#485]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

`netbox_cluster` and other netbox modules fail with
```
ModuleNotFoundError: No module named 'ansible_collections'
```
when using mitogen 0.3.0rc1 and ansible 2.10.

This is probably because `netbox_cluster.py` does not import `AnsibleModule`.
So this issue can be fixed by:
```patch
--- netbox_cluster.py.orig      2021-04-07 13:43:43.920287241 +0200
+++ netbox_cluster.py   2021-04-07 13:43:59.098401686 +0200
@@ -208,5 +208,6 @@
     netbox_cluster.run()
 
 
+from ansible.module_utils.basic import AnsibleModule
 if __name__ == "__main__":  # pragma: no cover
     main()
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  stragegy: mitogen_linear
  tasks:
    - netbox.netbox.netbox_cluster:
        netbox_url: '{{netbox_url}}'
        netbox_token: '{{netbox_token}}'
        data:
          name: 'my cluster'
          tenant: 'my tenant'
          cluster_type: KVM-Cluster
```

##### EXPECTED RESULTS

the task to complete successfully.

##### ACTUAL RESULTS

```
TASK [netbox.netbox.netbox_cluster] ***********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'ansible_collections'
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/me/.ansible/tmp/ansible_mitogen_runner_38_m0k6j/netbox_cluster.py\", line 166, in <module>\r\n    from ansible_collections.netbox.netbox.plugins.module_utils.netbox_utils import (\r\nModuleNotFoundError: No module named 'ansible_collections'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1} 
```

**Comment by FragmentedPacket** [comment]
Hi @philfry, thanks for the report.

At this point, I don't think this is necessarily the fault of the collection itself, but one that Molecule should probably fix as Ansible's method with collections is by adding the `ansible_collections` to the Python path.

I don't think requiring an import of `AnsibleModule` into each module that won't use it is a worthwhile fix within this repo for a third party.

Thanks again for your report, but at this time, there won't be any fix within this repo.

**Comment by xcorp** [comment]
I get a similar probably related issue with the `ip_address` module but with the error 
`Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed`
It's also fixed by importing `AnsibleModule`

@FragmentedPacket  what does Molecule has to do with it, or is it a typo and should be Mitogen?

I kinda agree with your argument that you shouldn't import modules not needed, but then as I understand it there has been some modifications done to it and renamed to `NetboxAnsibleModule`, which looks like it breaks stuff.
