### ISSUE TITLE
netbox_rack fails to find site information using name due to case

### ISSUE THREAD

**Issue by jcralbino** [netbox-community/ansible_modules#494]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
when creating a rack, with a site using only the name, we get an error 
    "msg": "Could not resolve id of site: dcb"

The issue is that name DCB is case sensitive

##### STEPS TO REPRODUCE
1. Create a yaml file with this content:
```
---
racks:
  - name: A46
    site: DCB
```
2. Create a site named DCB in netbox and slug DCB
3. Run the playbook

```   - name: Update racks
      netbox.netbox.netbox_rack:
        netbox_token: "{{ netbox_token }}"
        netbox_url: "{{ netbox_url }}"
        validate_certs: False
        data: "{{ item }}"
      loop: "{{ racks }}"

```

##### EXPECTED RESULTS
Rack is created using "Site: DCB" where DCB is the name of the site. regardless of the case type. 

##### ACTUAL RESULTS
Rack was not created as although name is DCB, the module changes it to lower case and then it cannot find the site correctly. 

```
failed: [localhost] (item={'name': 'A46', 'site': 'DCB'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "data": {
                "asset_tag": null,
                "comments": null,
                "custom_fields": null,
                "desc_units": null,
                "facility_id": null,
                "name": "A46",
                "outer_depth": null,
                "outer_unit": null,
                "outer_width": null,
                "rack_group": null,
                "rack_role": null,
                "serial": null,
                "site": "DCB",
                "status": null,
                "tags": null,
                "tenant": null,
                "type": null,
                "u_height": null,
                "width": null
            },
            "netbox_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "netbox_url": "https://netbox.mgmtdom.intra",
            "query_params": null,
            "state": "present",
            "validate_certs": false
        }
    },
    "item": {
        "name": "A46",
        "site": "DCB"
    },
    "msg": "Could not resolve id of site: dcb"
}
```

I tested that If i change the slug to dcb it works, well 
Also if i change "Site : 1" where 1 is Site Id also works.

I propose that more details is provided in the module documentation if this is not matching the name of the site keeping the case type.

**Comment by FragmentedPacket** [comment]
Do you mind reviewing https://netbox-ansible-collection.readthedocs.io/en/latest/getting_started/how-to-use/modules.html#state-present-create and letting me know if that helps you?
