### ISSUE TITLE
nb_inventory fails to cache network interfaces if tags are set for any interface of that host

### ISSUE THREAD

**Issue by TWitzenrath** [netbox-community/ansible_modules#535]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
2.10.10

###### Netbox:
2.11.4

###### Collection:
3.1.1

##### SUMMARY
When a (virtual) machine has a network interface that has tags attached to it, the whole "interfaces" information is not cached by ansibles inventory cache.

##### STEPS TO REPRODUCE

- activate caching for netbox.nb_inventory (cache_plugin: "jsonfile", cache: yes)
- add a virtual host "test" to netbox
- add interfaces to that host
- set a tag on one of those interfaces
- `ansible -a msg="{{ interfaces }}" -m debug  test` for the first time will output interfaces
- running the same for a second time, will output "[..] 'interfaces' is undefined"
- now clean the cache and run again
- now remove the tag from the interface and clean the cache, then run again as often you like

##### EXPECTED RESULTS

Cached information should be consistent with uncached information

##### ACTUAL RESULTS

Results were different depending on if cache was used or not

**Comment by nahun** [comment]
I submitted a fix for this. The cached inventory is getting modified during the interface host var processing so the next time it runs the cache now has the modified parameters and fails to process the interfaces.
