### ISSUE TITLE
Issue using a variable inside an api_filter with netbox.netbox.nb_lookup

### ISSUE THREAD

**Issue by marky2376** [netbox-community/ansible_modules#539]
##### ISSUE TYPE
 - Module question

###### Ansible:
Ansible 2.9.18 

###### Netbox:
v2.11.4

###### Collection:
3.1.1

##### SUMMARY
Not sure if I am doing something wrong with my understanding of the nblookup and api-filter or if it is not supported, but I am trying to use a variable inside of the api-filter.  See below.

##### STEPS TO REPRODUCE

```
- name: "Print IP"
  debug:
     msg: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses', api_filter= 'description=[c_description]', 
              api_endpoint='http://netbox.', token='', validate_certs='False') }}"

```

##### EXPECTED RESULTS
I intend for the lookup to check all IP addresses and return the value that matches my variable (c_description) that is in the brackets. 

##### ACTUAL RESULTS
If I have the variable in square brackets, nothing is returned:

```
ok: [localhost] => {
    "msg": []
}
```
If I use {{ or { or ", the whole database of IP addresses is returned.

Thanks.

**Comment by bluikko** [comment]
> ```
> - name: "Print IP"
>   debug:
>      msg: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses', api_filter= 'description=[c_description]', 
>               api_endpoint='http://netbox.', token='', validate_certs='False') }}"
> ```

It does work;
```yaml
- name: "Print IP"
  debug:
     msg: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses', api_filter= 'description=' ~ c_description, 
              api_endpoint='http://netbox.', token='', validate_certs='False') }}"
```
Try it out.

**Comment by marky2376** [comment]
Brilliant!  I did not see the tilda in any documentation.  Did I miss it?

**Comment by bluikko** [comment]
It is the concatenation operator. I do recall it wasn't the best documented one back when I was starting.

**Comment by marky2376** [comment]
I'm having the same issue with IPAM Prefixes but the concatenation operator is not working.  I am curious if there is a more proper solution that should be used?  

- name: "Lookup IP"
    set_fact:
      ip_address: "{{ query('netbox.netbox.nb_lookup', 'prefixes', api_filter='description=' ~ customer_name, api_endpoint='http://netbox.', token='', validate_certs='False') }}"

This query returns all prefixes, not the one matching my variable "customer_name"

**Comment by nahun** [comment]
The `/ipam/prefixes` API endpoint doesn't have a description query filter to use. This is a NetBox limitation. Please see the API specification/docs.

In the future, please use [GitHub Discussions](https://github.com/netbox-community/ansible_modules/discussions) for questions like these. Thanks!

**Comment by bluikko** [comment]
To add to the earlier comment - the API is completely documented and you can get it from the `/api/docs` URL.

**Comment by AIhmed** [comment]
I want to query all prefixes in the vrf. When i the run the following query i get all the prefixes in netbox:

vrf_prefixes: "{{ query('netbox.netbox.nb_lookup', 'prefixes', api_filter='vrf_name=' + vrf_name, api_endpoint=netbox_url, token=netbox_token) }}"

what query should i run to get all the prefixes inside a specifique vrf

**Comment by sc68cal** [comment]
You might need do do `vrf_name__ie` + vrf_name as [per the documentation](https://demo.netbox.dev/static/docs/rest-api/filtering/#string-fields)

**Comment by AIhmed** [comment]
I still get all the prefixes instead prefixes inside a specific vrf. the ansible code i am writing is as follows:
`- name: Get prefix by vrf_name
  ansible.builtin.set_fact:
    vrf_prefixes: "{{ query('netbox.netbox.nb_lookup', 'prefixes', api_endpoint=netbox_url, token=netbox_token, api_filter='vrf.name__ie=Shared') }}"
  tags:
    - read_vrf_prefixes`
to filter on the vrf name, should i use `vrf.name` or `vrf_name`?

**Comment by sc68cal** [comment]
I think `vrf_name__ie`

**Comment by sc68cal** [comment]
actually, I think VRFs are a first class object so you may have to look up the VRF and pass in the VRF id to the filter

**Comment by AIhmed** [comment]
So you suggest i should run a query and lookup for the VRF and then pass the vrf in the prefixes query like this:
`- name: Get vrf
     ansible.builtin.set_fact: vrf_prefixes: "{{ query('netbox.netbox.nb_lookup', 'prefixes', api_endpoint=netbox_url, token=netbox_token, api_filter='vrf_name=Shared') }}"`

`- name: Get Vrf Prefixes
      ansible.builtin.set_fact: vrf_prefixes: "{{ query('netbox.netbox.nb_lookup', 'prefixes', api_endpoint=netbox_url,  token=netbox_token, api_filter='vrf=' + vrf) }}"`
