### ISSUE TITLE
netbox.netbox.nb_inventory doesn't work properly with https scheme

### ISSUE THREAD

**Issue by chernogorsky** [netbox-community/ansible_modules#553]
Netbox: 2.11
ansible 2.10.3

plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.somedomain.com
validate_certs: false
config_context: false
interfaces: true
virtual_chassis_name: true
timeout: 300
group_by:
 - device_roles
 - platforms
 - tags
compose:
 ansible_network_os: platform.slug
 
Once I set https as an API_ENDPOINT, I receive the following:

Fetching: https://netbox.somedomain.com/api/docs/?format=openapi
Fetching: https://netbox.somedomain.com/api/dcim/devices/?limit=0&exclude=config_context
Fetching: https://netbox.somedomain.com/api/virtualization/virtual-machines/?limit=0&exclude=config_context
Fetching: https://netbox.somedomain.com/api/dcim/sites/?limit=0
Fetching: https://netbox.somedomain.com/api/dcim/regions/?limit=0
Fetching: https://netbox.somedomain.com/api/dcim/locations/?limit=0
Fetching: https://netbox.somedomain.com/api/tenancy/tenants/?limit=0
Fetching: https://netbox.somedomain.com/api/dcim/racks/?limit=0
Fetching: https://netbox.somedomain.com/api/dcim/device-roles/?limit=0
Fetching: https://netbox.somedomain.com/api/dcim/platforms/?limit=0
Fetching: https://netbox.somedomain.com/api/dcim/device-types/?limit=0
Fetching: https://netbox.somedomain.com/api/dcim/manufacturers/?limit=0
Fetching: https://netbox.somedomain.com/api/virtualization/clusters/?limit=0
Fetching: https://netbox.somedomain.com/api/dcim/interfaces/?limit=0
Fetching: https://netbox.somedomain.com/api/ipam/services/?limit=0
Fetching: http://netbox.somedomain.com/api/dcim/interfaces/?limit=1000&offset=1000
Fetching: http://netbox.somedomain.com/api/dcim/interfaces/?limit=1000&offset=1000

And then (as expected)
Traceback (most recent call last):
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/Users/mikhaelc/.pyenv/versions/3.8-dev/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

**Comment by jvanderaa** [comment]
I have had plenty of success using the inventory with an HTTPS endpoint. So I am not sure that this is related to the inventory specifically.

**Comment by chernogorsky** [comment]
Probably your installation has no http disabled
As showin in the log for some reason interface request goes to http  instead of https

**Comment by jvanderaa** [comment]
The title is deceiving. You are going to an uncommon add on of gathering the interfaces, and only that is going to the HTTP endpoint. All of the rest of the inventory is working just fine.

**Comment by chernogorsky** [comment]
@jvanderaa any proper title come in mind ? I'll replace.
but its connected to inventory, so my opinion its +- correct.

**Comment by chernogorsky** [comment]
My own netbox server misconfig
It returned http in 'next' section
Fixed in nginx.conf

**Comment by jvanderaa** [comment]
I would have added something about "when interfaces enabled" from the title perspective. Since it is beyond the defaults applied with the config. Similarly if something only happens with NetBox only when the Django toolbar is enabled, that you state that "when the toolbar is enabled". 

Glad you found the solution to the issue.
