### ISSUE TITLE
Add Tests: Netbox Inventory Plugin

### ISSUE THREAD

**Issue by FragmentedPacket** [netbox-community/ansible_modules#56]
##### ISSUE TYPE

 - Testing Update

##### SUMMARY
Need to build unit tests and possibly some integration testing for Netbox inventory plugin

**Comment by DouglasHeriot** [comment]
I plan to have a look at this as part of my other work on the inventory plugin.

Going to look at structuring the integration tests in such a way we can use the `ansible-test` tool as we do for the unit tests.
https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html

**Comment by FragmentedPacket** [comment]
@DouglasHeriot Let me know how that goes. Last time I checked it doesn't allow Docker compose which is the way we're building NetBox currently for integration testing. I wouldn't spend too much time on it if it becomes too much of a burden since we're already spinning up an instance for integration tests.

**Comment by DouglasHeriot** [comment]
We can probably close this now, implemented by #155 ?
It's not at 100% code coverage, but it's pretty solid.

**Comment by FragmentedPacket** [comment]
Agreed.
