### ISSUE TITLE
nb_lookup: unrecognised term locations

### ISSUE THREAD

**Issue by richardjohnallsopp** [netbox-community/ansible_modules#579]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
9.10.3

###### Netbox:
v2.11.11

###### Collection:
I tried with 3.1.1 but the `nb_lookup` still lists rack-groups in the code, so I reverted to using the built-in versions and I see the same issue.

##### SUMMARY
Unrecognized term `locations` when using the `nb_lookup` module to pull `rack-group` data via the API.

##### STEPS TO REPRODUCE

```yaml
    - name: "Obtain rack groups"
      debug:
        msg: "{{ query('netbox.netbox.nb_lookup', 'locations',
                       api_filter='site=' + site_code,
                       api_endpoint='',
                       token=netbox_key) }}"
      register: nb_rack_group_inventory
      tags:
        - "debug_n"
```

##### EXPECTED RESULTS

I expected to be able to pull the `rack groups/locations` data from NB using the `nb_lookup` ansible module.

##### ACTUAL RESULTS

I should point out that this was all working fine prior to the NB update we just did today.
```
TASK [Obtain rack groups] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => 
  msg: 'An unhandled exception occurred while running the lookup plugin ''netbox.netbox.nb_lookup''. Error was a <class ''ansible.errors.AnsibleError''>, original message: Unrecognised term locations. Check documentation'
```

**Comment by richardjohnallsopp** [comment]
I can see there is a locations module in the works - https://github.com/netbox-community/ansible_modules/pull/543#pullrequestreview-735505705, I've asked there if they can update the `nb_lookup` module as well. I did this locally `"locations": {"endpoint": netbox.dcim.locations},` and it resolved my issue.

**Comment by ryanmerolle** [comment]
duplicates #552
