### ISSUE TITLE
Feature: Add Netbox Services

### ISSUE THREAD

**Issue by loganbest** [netbox-community/ansible_modules#58]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Feature could be used to configure monitoring systems by addition of services defined in Netbox in Ansible hostvars. Netbox allows arbitrary structured data to be assigned to servers via custom fields, tags, configuration contexts and services. 

Original Related Ansible Core Issues:
https://github.com/ansible/ansible/issues/47918
https://github.com/ansible/ansible/pull/47919

@ollybee we've pulled the Inventory plugin out of core and into this collection. Could you please submit a new PR to this issue with your changes?

**Comment by FragmentedPacket** [comment]
@jhanssenfavaro Can you check the PR and see if it meets your requirements?
