### ISSUE TITLE
CI does not run sanity tests with ansible-core 2.11 and ansible-core's devel branch

### ISSUE THREAD

**Issue by felixfontein** [netbox-community/ansible_modules#583]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It currently only runs these tests with ansible-base 2.10, which is not a good idea at all.

Check out the testing requirements for inclusion in Ansible: https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#ci-testing

**Comment by ryanmerolle** [comment]
@gundalow @felixfontein I reviewed #591 with @rodvand and I think he addressed this concern.  I am just allowing you two to take a look before I merge to devel.
