### ISSUE TITLE
nb_lookup crash bug

### ISSUE THREAD

**Issue by pmusolino-rms** [netbox-community/ansible_modules#585]
##### ISSUE TYPE

 - Bug Report

###### Ansible:
ansible 4.5 [core 2.11.4] 

###### Netbox:

2.11.10
###### Collection:

netbox.netbox                 3.1.1
##### SUMMARY

Trying to use the nb_lookup example from the read the docs to get a list of devices
##### STEPS TO REPRODUCE

```yaml
---
- name: "Get Netbox inventory"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - name: Obtain list of devices from Netbox
    debug:
      msg: >
        "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
         manufactured by {{ item.value.device_type.manufacturer.name }}"
    loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
                    api_endpoint='https://netbox.example.com:8000',
                    token='abceasyas123xxxxxxxxx', validate_certs='no') }}"
```

##### EXPECTED RESULTS

Inventory of devices
##### ACTUAL RESULTS

Crashes

```
objc[82293]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[82293]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

**Comment by ThomasADavis** [comment]
The current module set is currently incompatible with any version of ansible newer than 2.10.7.

**Comment by ryanmerolle** [comment]
@pmusolino-rms & @ThomasADavis we just cut a release for the collection version 3.1.2.  Please update and let us know if you hav any other issues.

**Comment by pmusolino-rms** [comment]
I encountered the same crash bug.  I am running on mac os Catalina if that could be a factor.

From: Ryan Merolle ***@***.***>
Date: Monday, September 20, 2021 at 5:07 PM
To: netbox-community/ansible_modules ***@***.***>
Cc: Peter Musolino ***@***.***>, Mention ***@***.***>
Subject: Re: [netbox-community/ansible_modules] nb_lookup crash bug (#585)

@pmusolino-rms<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpmusolino-rms&data=04%7C01%7CPeter.Musolino%40rms.com%7Ce0545b5af1ab48e5f99f08d97c7ab264%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677688703093374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L8El6xTWjPAY4GAIZsgcNvD6Zk4X%2BPBOwCBXFujiVRA%3D&reserved=0> & @ThomasADavis<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FThomasADavis&data=04%7C01%7CPeter.Musolino%40rms.com%7Ce0545b5af1ab48e5f99f08d97c7ab264%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677688703103365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JJDG37Bm4Xp1sD6E3YqsLba2c56mxmQMSdKcVCcnc30%3D&reserved=0> we just cut a release for the collection version 3.1.2. Please update and let us know if you hav any other issues.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnetbox-community%2Fansible_modules%2Fissues%2F585%23issuecomment-923311184&data=04%7C01%7CPeter.Musolino%40rms.com%7Ce0545b5af1ab48e5f99f08d97c7ab264%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677688703103365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FDxy699xrupMOqux12ITRmQcIgujbBU46ccIzEw%2Fehc%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYUOZKFHWTGLWG47OB7XADUC6PCFANCNFSM5DVT22TA&data=04%7C01%7CPeter.Musolino%40rms.com%7Ce0545b5af1ab48e5f99f08d97c7ab264%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677688703113351%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OV5waXyoM9%2F5NwmgI8rahxMQ3pKrVWNN5DwN4cDhZHI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CPeter.Musolino%40rms.com%7Ce0545b5af1ab48e5f99f08d97c7ab264%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677688703113351%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=chHmHCDoAb05bB8TytYX15r8WTCsW87%2BUB1%2BLCFoxX0%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CPeter.Musolino%40rms.com%7Ce0545b5af1ab48e5f99f08d97c7ab264%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677688703123353%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gc0BPMDLpc4xRnrwyh%2F2RM%2Bh04RSlRjN4ItoAzunBvY%3D&reserved=0>.

**Comment by ryanmerolle** [comment]
First your query is wrong and also crashes for me.  Try:

```
    - name: Obtain list of devices from Netbox
      debug:
        msg: >
          "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
           manufactured by {{ item.value.device_type.manufacturer.name }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
                      api_endpoint='https://netbox.example.com:8000',
                      token='abceasyas123xxxxxxxxx', validate_certs=false) }}"
```

If you still have issues, did you use 3.1.2 like I said since we literally just cut the release for ansible-galaxy today?

**Comment by pmusolino-rms** [comment]
Hi Ryan,

I copied your example and changed just token and api_endpoint values.  I upgraded to 3.1.2, however same result.

ansible-playbook nb_inventory.yml

PLAY [Get Netbox inventory of APs] *************************************************************************************************************************************
objc[97433]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[97433]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state

$ ansible --version
ansible [core 2.11.5]
  config file = /path/to/ansible.cfg
  configured module search path = ['/path/to/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /path/to/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /path/to/.ansible/collections:/usr/share/ansible/collections
  executable location = /path/to/venv/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 06:20:32) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True

ansible-galaxy collection list netbox.netbox

# ~/.ansible/collections/ansible_collections
Collection    Version
------------- -------
netbox.netbox 3.1.2

# /path/to/venv/lib/python3.9/site-packages/ansible_collections
Collection    Version
------------- -------
netbox.netbox 3.1.2

Here is the crash dump from the apple Problem report tool
https://pastebin.com/3pm1T2qm


From: Ryan Merolle ***@***.***>
Date: Monday, September 20, 2021 at 6:26 PM
To: netbox-community/ansible_modules ***@***.***>
Cc: Peter Musolino ***@***.***>, Mention ***@***.***>
Subject: Re: [netbox-community/ansible_modules] nb_lookup crash bug (#585)

First your query is wrong and also crashes for me. Try:

    - name: Obtain list of devices from Netbox

      debug:

        msg: >

          "Device {{ item.value.display_name }} (ID: {{ item.key }}) was

           manufactured by {{ item.value.device_type.manufacturer.name }}"

      loop: "{{ query('netbox.netbox.nb_lookup', 'devices',

                      api_endpoint='https://netbox.example.com:8000',

                      token='abceasyas123xxxxxxxxx', validate_certs=false) }}"

If you still have issues, did you use 3.1.2 like I said since we literally just cut the release for ansible-galaxy today?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnetbox-community%2Fansible_modules%2Fissues%2F585%23issuecomment-923387861&data=04%7C01%7CPeter.Musolino%40rms.com%7Cfe9671783e3e4c9dd77408d97c85a8ea%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677735779823799%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=GyyMwvL2CQJSLePZBXC5Q6WzVX%2FDg5YbI%2F%2Bi1PNnUJQ%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYUOZJR3QWHS7M2AH6RM6DUC6YIPANCNFSM5DVT22TA&data=04%7C01%7CPeter.Musolino%40rms.com%7Cfe9671783e3e4c9dd77408d97c85a8ea%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677735779833794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DWnCTzFKwJxt7NS3tv8cnGp%2FVFSR4p1gwCJR1V9h62Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CPeter.Musolino%40rms.com%7Cfe9671783e3e4c9dd77408d97c85a8ea%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677735779833794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ug5bLQcn0l0F2e60pcAciINykq0zTk%2BhuDkH3ErIMOo%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CPeter.Musolino%40rms.com%7Cfe9671783e3e4c9dd77408d97c85a8ea%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637677735779843787%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qC6DL49BDHT2p%2FcymO3fQH3Y4Qe4ssnGoAto3uV3aj8%3D&reserved=0>.

**Comment by pmusolino-rms** [comment]
Martin,
This was it. Thanks for tracking that down.

Ok to close.
From: Martin Rødvand ***@***.***>
Date: Tuesday, September 21, 2021 at 7:51 AM
To: netbox-community/ansible_modules ***@***.***>
Cc: Peter Musolino ***@***.***>, Mention ***@***.***>
Subject: Re: [netbox-community/ansible_modules] nb_lookup crash bug (#585)

Since you're on a Mac, try running it with env no_proxy='*' ansible-playbook nb_inventory.yml

There's a note of this error on the doc site https://netbox-ansible-collection.readthedocs.io/en/latest/getting_started/how-to-use/modules.html?highlight=dead%20state#specifying-modules-in-a-playbook<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnetbox-ansible-collection.readthedocs.io%2Fen%2Flatest%2Fgetting_started%2Fhow-to-use%2Fmodules.html%3Fhighlight%3Ddead%2520state%23specifying-modules-in-a-playbook&data=04%7C01%7CPeter.Musolino%40rms.com%7C7f298cf8e772429366b508d97cf629c3%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637678218980861682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7myUdMywSrW554dPex5m1rL8%2FrIutbTGB1UH5p%2FLTKU%3D&reserved=0> referring to the bug ansible/ansible#32554 (comment)<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fansible%2Fansible%2Fissues%2F32554%23issuecomment-642896861&data=04%7C01%7CPeter.Musolino%40rms.com%7C7f298cf8e772429366b508d97cf629c3%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637678218980861682%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TsFNdc8enHQ1tMcx7L%2BvB5m9Aj%2FFPe%2Fu8WV48lxv%2Bzs%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnetbox-community%2Fansible_modules%2Fissues%2F585%23issuecomment-923906544&data=04%7C01%7CPeter.Musolino%40rms.com%7C7f298cf8e772429366b508d97cf629c3%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637678218980871675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k1JF88fCfqJIBy%2BHs6Tl1U10du6Q9oz%2FxMOAcE%2BKFM8%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYUOZK45RGFZ7B57GVQBKLUDBWUPANCNFSM5DVT22TA&data=04%7C01%7CPeter.Musolino%40rms.com%7C7f298cf8e772429366b508d97cf629c3%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637678218980871675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zfS1gtkO1NEeqoloGSePhG6SY1trVgC1FwqF%2Bzz8P5w%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CPeter.Musolino%40rms.com%7C7f298cf8e772429366b508d97cf629c3%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637678218980881673%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZjFLOC4ByRQoUMUU6HJdS35jW1S4knVnTukfYzCqqBk%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CPeter.Musolino%40rms.com%7C7f298cf8e772429366b508d97cf629c3%7Cd43fb8a804da4990b86cc4ba9ba4511f%7C0%7C0%7C637678218980891664%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bH33KAADmN7Dpwak5%2F7lOuMsdGPNS%2F8sd4zgubcUavY%3D&reserved=0>.
