### ISSUE TITLE
Feature: add Device and VM Interface information

### ISSUE THREAD

**Issue by loganbest** [netbox-community/ansible_modules#60]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Implement a new extractor method which includes the inventory information if requested. Additionally, make a second request to gather all device/vm IP addresses and attach them as a list to the interface object.

Original Ansible Core Issues/PR:
https://github.com/ansible/ansible/pull/55982

@mkeetman, since you submitted the original PR that has yet to be merged into core and we've pulled the inventory out of core and into this collection, could you submit a new PR to this Issue?

**Comment by loganbest** [comment]
Also paging @larsuhartmann as there was an additional issue and PR submitted relating to this. 

https://github.com/ansible/ansible/issues/59725
https://github.com/ansible/ansible/pull/60642

**Comment by loganbest** [comment]
Also paging @larsuhartmann @yannis100 as there was an additional issue opened on core relating to this

https://github.com/ansible/ansible/issues/59725
https://github.com/ansible/ansible/issues/60124
https://github.com/ansible/ansible/pull/60642

**Comment by abrown-bw** [comment]
+1

**Comment by FragmentedPacket** [comment]
@abrown-bw This has been implemented in PR #98. Do you mind testing?
