### ISSUE TITLE
[Feature]: Using Primary IP address as inventory_hostname

### ISSUE THREAD

**Issue by aventrax** [netbox-community/ansible_modules#601]
##### ISSUE TYPE
 - Feature Idea

###### Ansible:
```
ansible [core 2.11.4] 
  config file = /home/matteo/.ansible.cfg
  configured module search path = ['/home/matteo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/python-virtual-envs/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /home/matteo/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/python-virtual-envs/ansible/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.1
  libyaml = True
```

###### Netbox:
2.11.7

###### Collection:
3.1.2

##### SUMMARY
Using a standard YAML inventory I can pick one of hostname or IP addresses to build the inventory itself. Using nb_inventory.py that is not possible because the plugin get the "device name" from Netbox and uses that name as inventory_hostname, without any option to use the IP address. 
Unfortunately this stop the host_vars pairing, because on the host_vars/ folder I have files named host_vars/1.2.3.4.yaml and they match with the inventory_hostname, not with the inventory_host (which is correctly set with the device's IP address).

Using IP in inventory could be an uncommon way to use ansible, but I'd want to have the same features that a standard YAML inventory provides even with this (very helpful) nb_inventory.py plugin.

##### STEPS TO REPRODUCE

Having this files...

`host_vars/10.40.2.127.yaml`:
```
my_own_var: foo
```

`host_vars/10.40.2.128.yaml`:
```
my_own_var: bar
```
```
ansible-inventory -i inventories/site1--list
```

##### EXPECTED RESULTS

```
{
    "_meta": {
        "hostvars": {
            "10.40.2.127": {
                "my_own_var": "foo"
            },
            "10.40.2.128": {
                "my_own_var": "bar"
            }
        }
    },
    "all": {
        "children": [
            "hosts",
            "ungrouped"
        ]
    },
    "hosts": {
        "hosts": [
            "10.40.2.127",
            "10.40.2.128"
        ]
    }
}
```

##### ACTUAL RESULTS

```
{
    "_meta": {
        "hostvars": {
            "web1": {},
            "web2": {}
        }
    },
    "all": {
        "children": [
            "hosts",
            "ungrouped"
        ]
    },
    "hosts": {
        "hosts": [
            "web1",
            "web2"
        ]
    }
}
```

##### PULL REQUEST

I have done my first [PR ](https://github.com/netbox-community/ansible_modules/pull/600) on github, I'm sure that is not done the right way so I apologize for any error on my code. Anyway, it work for my case and maybe some of you can improve it.

**Comment by ryanmerolle** [comment]
I am always happy to give guidance with users and their first PR, so regardless of this issue, I will give feedback in that PR.

Before the project add yet another new option to the inventory, I'd love it for other users to weigh in.

I mean device name is how most people manage their infra.  As such hostvars match device name.  I'm curious if this is a common usage (ie hostvars being IPs).  I feel like there is a ton of down side for a management perspective to follow this route.

Furthermore, is this feature worth adding to the bloat of the inventory plugin?  It may, and it may not be much bloat.  I just want to see what others think.

**Comment by aventrax** [comment]
@ryanmerolle thanks for your patience.  Today I just wanted to try to fix the issue by me looking the code and so I forked the repository and tried. Github desktop app helped a lot and at the end it proposed a "pull request", I waited because I know that a new option on a community repository needs a sort of "public approval", I agree with you. Anyway after opening for the fifth time the app I didn't resist, i tought "if the community does not like the naming they can change it, or reject the PR. So, it has been my lack of patience to let me press the button ;)

For your question: on the official documentation there are a mix of IPs and hostnames, a couple of years ago I started that way because of a tutorial somewhere. Anyway, I'm just curious as you to see what the people usually do.

**Comment by nahun** [comment]
I am weary of adding another option to the inventory plugin as we do have a lot already. I am guilty of getting more added too.

I haven't heard of anyone else using IP addresses as the `inventory_hostname` so I don't know how much it would be used.

The bloat to the plugin code itself is negligible , its more around testing where it would add a lot.

**Comment by aventrax** [comment]
I'd want to add a bit of info about why I'm using IP addresses instead of hostnames.

Leaving Netbox apart for a moment, I'm using Ansible to deploy apps and configure them along with the operating system. This is usually performed on customer's facilities which we do control only partially, moreover this stuff will be performed over a VPN connection on their internal network and usually the ansible controller does not have any naming resolution working because of various limitation or issues that we can't address because we do not control the infrastructure. Because of how they "usually" work, we found that using IP address is more reliable and so our inventories (YAML, one for each customer) uses IP addressed and we have the host_vars folder full of variables and named with the IP address dot yaml.

Back to Netbox; it is used only for our company and I'm just trying to extend it to the customers, but I'd want to preserve all the host_vars without having to rename tons of files. This has been the primary reason for raising this issue.

**Comment by TheNetworkGuy** [comment]
As a network company, we primarily use IP's to get rid of a possible DNS failure. I think that, especially with software like Netbox and Ansible which handle the technical aspect of name to IP translation and administration, a better question would be "why not use IP addresses"?

**Comment by rodvand** [comment]
The pull request included some good discussion, and I think for now we are not going the way of assigning an IP address to a variable named hostname.
