### ISSUE TITLE
vlan_role uses name in query

### ISSUE THREAD

**Issue by MrDiba** [netbox-community/ansible_modules#612]
When using the netbox.netbox.netbox_vlan module I came across what I think is a bug. When using the vlan_role parameter the API call will use the `name` parameter, where as when using the prefix_role it will reference the `slug` parameter.

What I would expect is that both call's will use the slug parameter so that capital letters are not an issue. 

see:
https://github.com/netbox-community/ansible_modules/blob/master/plugins/module_utils/netbox_utils.py#L116
and:
https://github.com/netbox-community/ansible_modules/blob/master/plugins/module_utils/netbox_utils.py#L140

**Comment by rodvand** [comment]
While this might not have been intentional when creating the module, I think this will be more and more common as NetBox itself is looking to remove slugs (see https://github.com/netbox-community/netbox/issues/8036). Name is also a unique indicator here so I'm happy leaving it as it is.
