### ISSUE TITLE
Setting VM vCPU task is always "changed" on NetBox 2

### ISSUE THREAD

**Issue by bluikko** [netbox-community/ansible_modules#616]
##### ISSUE TYPE

 - Bug Report

###### Ansible:

2.11.6

###### Netbox:

2.11.12

Problem is not happening on NetBox 3.0.8.

###### Collection:

3.2.0

##### SUMMARY

Task to update VM vCPU is always reported "changed" status because NetBox uses 2 decimals for vCPU while the NetBox Ansible module uses only 1 decimal for vCPU:
```diff
--- before
+++ after
@@ -1 +1 @@
-vcpus: '4.00'
+vcpus: 4.0
```

So NetBox reports here vCPU was before "4.00" but the Ansible module uses "4.0" so it always updates the vCPU value.

#562 (and #605) got this halfway there - before it was "4.00" vs "4", but it still does not work 100%.

##### STEPS TO REPRODUCE

Have a task that updates vCPU on a VM.

```yaml
  netbox.netbox.netbox_virtual_machine:
    data:
      vcpus: 4
```

##### EXPECTED RESULTS

The vCPU number should be represented in same format (2 decimals) so that the task is not always status changed.

The bests would probably be to check how many decimals did NetBox give for the number and use the same format, so that if NetBox changes this again then it will continue to work right.

##### ACTUAL RESULTS

Task works but the status is "changed" on every run.

```

```

**Comment by rodvand** [comment]
@bluikko Could you test with the devel branch now? I believe I've got the idempotency issue sorted on both 2.11 and 3.0.

**Comment by jsalatiel** [comment]
Has this been merged ?
