### ISSUE TITLE
Create module for Wireless LAN

### ISSUE THREAD

**Issue by rodvand** [netbox-community/ansible_modules#652]
New data model introduced in NetBox 3.1.

Data model in NetBox: https://github.com/netbox-community/netbox/blob/feature/netbox/wireless/models.py
Current (beta) API:
<img width="485" alt="Screenshot 2021-11-17 at 20 24 24" src="https://user-images.githubusercontent.com/56864/142269095-931d7292-da0f-4385-87c2-0e822d1ce27a.png">

**Comment by ThomasADavis** [comment]
https://github.com/netbox-community/pynetbox/releases/tag/v6.4.0
