### ISSUE TITLE
Add nb_lookup endpoints for NetBox 3.1 support

### ISSUE THREAD

**Issue by rodvand** [netbox-community/ansible_modules#670]
##### ISSUE TYPE
- Feature

##### SUMMARY
Add endpoints defined in NetBox 3.1 to support lookups with 3.1 using the ansible collection.

netbox.wireless.wireless_lan_groups
netbox.wireless.wireless_lan_groups
netbox.wireless.wireless_lan
netbox.wireless.wireless_links

These endpoints are supported in pynetbox 6.4.0.

**Comment by rodvand** [comment]
@ThomasADavis You want to take a crack at it? You pretty much had the code ready in an earlier PR.

**Comment by ThomasADavis** [comment]
I can, I even have figured out how to track the pynetbox version, and do things based on that.
