### ISSUE TITLE
device_query_filter return all virtual machines irrespective of filters

### ISSUE THREAD

**Issue by najeebvv** [netbox-community/ansible_modules#677]
cat nb_inventory_local.yaml
plugin: netbox.netbox.nb_inventory
api_endpoint: http://localhost:8001/
_term: devices
validate_certs: false
device_query_filters:
  - role: 'server'
  - rack_id: 1
fetch_all: false
compose:
  tags: tags.name
  vm: is_virtual

in the above example, devices are filtered by rack id and role. even though virtual machines has no rack id and no matching role its still shown in the result.

[root@netbox ~]# ansible-inventory -vvv  --list -i nb_inventory_local.yaml
ansible-inventory 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible-inventory
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /root/nb_inventory_local.yaml as it did not pass its verify_file() method
script declined parsing /root/nb_inventory_local.yaml as it did not pass its verify_file() method
Fetching: http://localhost:8001/api/status
Fetching: http://localhost:8001/api/dcim/devices/?limit=0&role=server&rack_id=1&exclude=config_context
Fetching: http://localhost:8001/api/virtualization/virtual-machines/?limit=0&exclude=config_context
Fetching: http://localhost:8001/api/dcim/sites/?limit=0
Fetching: http://localhost:8001/api/dcim/regions/?limit=0
Fetching: http://localhost:8001/api/dcim/locations/?limit=0
Fetching: http://localhost:8001/api/tenancy/tenants/?limit=0
Fetching: http://localhost:8001/api/dcim/racks/?limit=0
Fetching: http://localhost:8001/api/dcim/device-roles/?limit=0
Fetching: http://localhost:8001/api/dcim/platforms/?limit=0
Fetching: http://localhost:8001/api/dcim/device-types/?limit=0
Fetching: http://localhost:8001/api/dcim/manufacturers/?limit=0
Fetching: http://localhost:8001/api/virtualization/clusters/?limit=0
Fetching: http://localhost:8001/api/ipam/services/?limit=0&device_id=15&device_id=11&device_id=12&device_id=13&device_id=14
Fetching: http://localhost:8001/api/ipam/services/?limit=0&virtual_machine_id=1
Parsed /root/nb_inventory_local.yaml inventory source with auto plugin
{
    "_meta": {
        "hostvars": {
            "srv-p-001": {
                "custom_fields": {},
                "device_roles": [
                    "server"
                ],
                "device_types": [
                    "hp-server"
                ],
                "is_virtual": false,
                "local_context_data": [
                    null
                ],
                "locations": [
                    "dc01"
                ],
                "manufacturers": [
                    "hpe"
                ],
                "racks": [
                    "rack-10"
                ],
                "regions": [
                    "deu01"
                ],
                "services": [],
                "sites": [
                    "deu01"
                ],
                "status": {
                    "label": "Active",
                    "value": "active"
                },
                "tags": [
                    "baremetal",
                    "dcp"
                ],
                "vm": false
            },
            "srv-p-002": {
                "custom_fields": {},
                "device_roles": [
                    "server"
                ],
                "device_types": [
                    "hp-server"
                ],
                "is_virtual": false,
                "local_context_data": [
                    null
                ],
                "locations": [
                    "dc01"
                ],
                "manufacturers": [
                    "hpe"
                ],
                "racks": [
                    "rack-10"
                ],
                "regions": [
                    "deu01"
                ],
                "services": [],
                "sites": [
                    "deu01"
                ],
                "status": {
                    "label": "Active",
                    "value": "active"
                },
                "tags": [
                    "dcp"
                ],
                "vm": false
            },
            "srv-p-003": {
                "custom_fields": {},
                "device_roles": [
                    "server"
                ],
                "device_types": [
                    "hp-server"
                ],
                "is_virtual": false,
                "local_context_data": [
                    null
                ],
                "locations": [
                    "dc01"
                ],
                "manufacturers": [
                    "hpe"
                ],
                "racks": [
                    "rack-10"
                ],
                "regions": [
                    "deu01"
                ],
                "services": [],
                "sites": [
                    "deu01"
                ],
                "status": {
                    "label": "Active",
                    "value": "active"
                },
                "tags": [
                    "dcp"
                ],
                "vm": false
            },
            "srv-p-004": {
                "custom_fields": {},
                "device_roles": [
                    "server"
                ],
                "device_types": [
                    "hp-server"
                ],
                "is_virtual": false,
                "local_context_data": [
                    null
                ],
                "locations": [
                    "dc01"
                ],
                "manufacturers": [
                    "hpe"
                ],
                "racks": [
                    "rack-10"
                ],
                "regions": [
                    "deu01"
                ],
                "services": [],
                "sites": [
                    "deu01"
                ],
                "status": {
                    "label": "Active",
                    "value": "active"
                },
                "tags": [],
                "vm": false
            },
            "srv-bkp-p-001": {
                "custom_fields": {},
                "device_roles": [
                    "server"
                ],
                "device_types": [
                    "hp-server"
                ],
                "is_virtual": false,
                "local_context_data": [
                    null
                ],
                "locations": [
                    "dc01"
                ],
                "manufacturers": [
                    "hpe"
                ],
                "racks": [
                    "rack-10"
                ],
                "regions": [
                    "deu01"
                ],
                "services": [],
                "sites": [
                    "deu01"
                ],
                "status": {
                    "label": "Active",
                    "value": "active"
                },
                "tags": [],
                "vm": false
            },
            "vm1": {
                "cluster": "dcp",
                "cluster_type": "kvm",
                "custom_fields": {},
                "device_roles": [
                    "virtual-machine"
                ],
                "is_virtual": true,
                "local_context_data": [
                    null
                ],
                "locations": [],
                "regions": [
                    "deu01"
                ],
                "services": [],
                "sites": [
                    "deu01"
                ],
                "status": {
                    "label": "Active",
                    "value": "active"
                },
                "tags": [],
                "tenants": [
                    "default"
                ],
                "vm": true
            }
        }
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    },
    "ungrouped": {
        "hosts": [
            "srv-p-001",
            "srv-p-002",
            "srv-p-003",
            "srv-p-004",
            "srv-bkp-p-001",
            "vm1"
        ]
    }
}

ansible --version
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

collection version: v3.4.0

**Comment by rodvand** [comment]
See https://github.com/netbox-community/ansible_modules/issues/471 where this is discussed. There is also a workaround proposed in the issue.

**Comment by najeebvv** [comment]
that method does not work for devices other than virtual machines and the expectation is to get only physical servers not virtual machines. If I need to exclude virtual machines from the output, using id__n: -1 does not work or any such method.
