### ISSUE TITLE
Update/Create Region Description Not Supported (netbox_region.py)

### ISSUE THREAD

**Issue by ScroungerE2E** [netbox-community/ansible_modules#688]
##### ISSUE TYPE
 - Bug Report

###### Ansible:
ansible --version
ansible [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/meggert/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/meggert/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True

###### NetBox:
NetBox v3.1.5

###### Collection:
v.3.4

##### SUMMARY
Using a Ansible playbook, the "description" field is not supported within the netbox_region.py as a valid data field: https://github.com/netbox-community/ansible_modules/blob/devel/plugins/modules/netbox_region.py#L115

##### STEPS TO REPRODUCE
A simple playbook to create/update a region within NetBox (using static values) is returns an error for the unsupported description filed:

PLAYBOOK USED FOR TESTING
```
---
- name: Created Static Region in Customer Netbox
  gather_facts: False
  hosts: localhost
  collections:
    - netbox.netbox

  tasks:
    - name: "Example state: present - Update"
      netbox_region:
        netbox_url: "https://hostname"
        netbox_token: "TOKEN"
        data:
          parent_region:
          name: California
          slug: california
          description: "State of California"
        state: "present"

```

##### EXPECTED RESULTS
Expectation is that the description field (STR) would be supported.
```
ansible-playbook cust_nbx_create_region.yaml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Created Static Region in Customer Netbox] ************************************************************************************************************************************************************

TASK [Example state: present - Update] *********************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

##### ACTUAL RESULTS
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (netbox_region) module: data.description. Supported parameters include: cert, state, query_params, netbox_url, data, validate_certs, netbox_token."}

```
ansible-playbook cust_nbx_create_region.yaml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Created Static Region in Customer Netbox] ************************************************************************************************************************************************************

TASK [Example state: present - Update] *********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (netbox_region) module: data.description. Supported parameters include: cert, state, query_params, netbox_url, data, validate_certs, netbox_token."}

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=
```

**Comment by rodvand** [comment]
I've added this to the devel branch. If you want to install it before a release is published to Galaxy (probably later in the week) you can install from GitHub - https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-a-collection-from-a-git-repository
