### ISSUE TITLE
[Feature]: Bridged interface support

### ISSUE THREAD

**Issue by kemeris2000** [netbox-community/ansible_modules#709]
ISSUE TYPE

    Feature

SOFTWARE VERSIONS
NetBox: 3.1.2
SUMMARY

Add ability to specify Bridged interface in netbox_device_interface plugin.

**Comment by sc68cal** [comment]
Has this new type been added to the NetBox API? I looked at https://netbox.readthedocs.io/en/stable/models/dcim/interface/#interface-types but it does not appear listed

**Comment by sc68cal** [comment]
Has this new type been added to the NetBox API? I looked at https://netbox.readthedocs.io/en/stable/models/dcim/interface/#interface-types but it does not appear listed

**Comment by kemeris2000** [comment]
> Has this new type been added to the NetBox API? I looked at https://netbox.readthedocs.io/en/stable/models/dcim/interface/#interface-types but it does not appear listed

This is not new interface type.
This is "bridge" parameter under dcim.interfaces model to specify bridge.

![image](https://user-images.githubusercontent.com/48207709/151117168-bd49abff-5bfb-4a52-bbf3-b161b12dac7e.png)

https://demo.netbox.dev/api/docs/

**Comment by sc68cal** [comment]
OK so you just create a device interface, say `br1000` then you use the bridge attribute to link other device interfaces back to it, just like a LAG. Got it.

**Comment by kemeris2000** [comment]
> r10

Yes.
