### ISSUE TITLE
[Bug]: Inventory Module will only load 1 prefix when multiple are associated to a site

### ISSUE THREAD

**Issue by Eric-Sim** [netbox-community/ansible_modules#732]
### Ansible NetBox Collection version

Development branch

### Ansible version

```bash
ansible [core 2.11.4]
  config file = None
  configured module search path = ['/Users/eric.sim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/eric.sim/.pyenv/versions/3.8.9/envs/ansible-test/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/eric.sim/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/eric.sim/.pyenv/versions/ansible-test/bin/ansible
  python version = 3.8.9 (default, Aug 25 2021, 11:07:09) [Clang 12.0.5 (clang-1205.0.22.11)]
  jinja version = 2.11.2
  libyaml = False
```

### NetBox version

2.11.8

### Python version

3.8

### Steps to Reproduce

Populate Netbox with at least one site having more than 1 prefix associated to it.
Load inventory from Netbox using netbox inventory plugin (must specify the "site_data" and "prefixes" options as True.)

### Expected Behavior

Expected behavior is that all prefixes associated to a site are included in the Ansible inventory.

### Observed Behavior

Only 1 prefix for each site is inserted into the site data in Ansible Inventory.

**Comment by Eric-Sim** [comment]
I will submit a PR to fix this (likely next week)
Assign bug to me if you wish.

**Comment by rodvand** [comment]
Have you had a chance to look at this @Eric-Sim ? Wondering if I should do a new release of the collection this week, could be nice to include this fix if possible.

**Comment by Eric-Sim** [comment]
I've identified the issue and can have the solution tested tomorrow.
