### ISSUE TITLE
netbox_device_type: slug is required

### ISSUE THREAD

**Issue by ignatenkobrain** [netbox-community/ansible_modules#74]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The `slug` is used in regions, sites and more places, and is not mandatory there. However, for `netbox_device_type`, it seems to be mandatory. It does not seem that it is necessary since other netbox ansible modules are generating it automatically.

**Comment by FragmentedPacket** [comment]
Thanks for this report. I totally see your point and I will change it to being optional and slugify it via the model as it appears it does via the GUI.

I will try and get this merged in this weekend and hopefully push out a new release as well once I solve the issues you've reported.

**Comment by FragmentedPacket** [comment]
Can you please test PR #77 for the fix and let me know?
