### ISSUE TITLE
[Feature]: Add Device Region

### ISSUE THREAD

**Issue by theotherguy2175** [netbox-community/ansible_modules#754]
### NetBox version

3.1.8

### Feature type

Change to existing Module

### Proposed functionality

Simple add the ability to update the device region:

    - name: Udpate Device
      netbox_device:
        netbox_url: "{{ url }}"
        netbox_token: "{{ token }}"
        validate_certs: no
        data:
          name: "{{ ansible_net_hostname }}"
          device_type: "{{ model }}"
          device_role: Router
          site: {{ site }}
          location: "{{ location }}"
          **region: "{{ region }}"**
          serial: "{{ serial }}"
        state: present

### Use case

Making the ability to use ansible to update the region for devices.

**Comment by ryanmerolle** [comment]
region is inherited by site, rack, or location.  Is your use case for a device not associated to either of those objects?  I see region in the UI as more of a filter to help narrow down site, rack, or location in the UI.

**Comment by rodvand** [comment]
As @ryanmerolle points out the region is not set directly on a device, it is derived from the site's region. So it doesn't make sense to add it to the `netbox_device` module as a device has to be assigned a site, and that site can be assigned a region. A device itself cannot be assigned region.
