### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by CaioSoaresBrazil** [netbox-community/ansible_modules#79]
Hi,

My ansible conf:

`ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
`
Installed Netbox modules:

`ansible-galaxy collection install netbox_community.ansible_modules
Process install dependency map
Starting collection install process
Installing 'netbox_community.ansible_modules:0.1.4' to '/root/.ansible/collections/ansible_collections/netbox_community/ansible_modules'
[root@NETBOX caio]# ansible-doc netbox_vrf`

Failing when trying to use a few modules:

`# ansible-doc netbox_vrf
[WARNING]: module netbox_vrf not found in: /root/.ansible/plugins/modules:/usr/
share/ansible/plugins/modules:/usr/local/lib/python3.6/site-
packages/ansible/modules`

`# ansible-doc netbox_tenant
[WARNING]: module netbox_tenant not found in: /root/.ansible/plugins/modules:/u
sr/share/ansible/plugins/modules:/usr/local/lib/python3.6/site-
packages/ansible/modules`

What did I miss?

Thanks.

**Comment by CaioSoaresBrazil** [comment]
Problem solved... the modules were in the wrong folder... transferred to the correct folder and it worked ! thanks.

**Comment by FragmentedPacket** [comment]
No problem. Here is a link on how to view the docs via the `ansible-doc` command.

https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html

It requires the fqcn, e.g. netbox_community.ansible_modules
