### ISSUE TITLE
Inventory: [Feature]: renaming hypen -> underscore in groups

### ISSUE THREAD

**Issue by DanielWeeber** [netbox-community/ansible_modules#795]
### NetBox version

v3.2.4

### Feature type

Change to existing Module

### Proposed functionality

One should be able to set a flag so that hypens (-) will be replaced with underscores (_)
I'm using scripts to sync my vmware vms to netbox. this is setting tags like "netbox-synced".

In the netbox dynamic inventory I use

```
group_by:
  - tags
```

hence this warning is popping up when using the dynamic inventory

```
Not replacing invalid character(s) "{'-'}" in group name (tags_netbox-synced)
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Not replacing invalid character(s) "{'-'}" in group name (tags_source-vcenter)
```

### Use case

Not showing any error when using

**Comment by rodvand** [comment]
Have you looked at setting `force_valid_group_names = always` in your ansible.cfg?https://docs.ansible.com/ansible/latest/reference_appendices/config.html#transform-invalid-group-chars

**Comment by ypid** [comment]
`force_valid_group_names = always` only partly fixed it for me because it still causes Ansible to emit `[WARNING]: Invalid characters were found in group names and automatically replaced, use -vvvv to see details`. This fixed it for me:

```
strict: False
keyed_groups:
  - key: tags
    prefix: 'tag'
```
