### ISSUE TITLE
[Feature]: nb_inventory list virtual machines assigned to cluster

### ISSUE THREAD

**Issue by trapecija** [netbox-community/ansible_modules#804]
### NetBox version

v3.2.4

### Feature type

Change to existing Plugin

### Proposed functionality

Possibility to list all virtual machines that are assigned to specific device/cluster.
For example i have device with name "server01", and i have cluster named "lxc", to cluster "lxc" is assigned device "server01". When i run command ansible-inventory --host server01 -i inventory.yml i got cluster name "lxc", but in additional i want to see what virtual machines is assigned on cluster "lxc".

### Use case

Receiving a more detailed infomation about device via ansible-inventory.

**Comment by trapecija** [comment]
yes, ansible says:
`Invalid value "['device_roles', 'platforms', 'cluster_server01']" for configuration option "plugin_type: inventory plugin:
ansible_collections.netbox.netbox.plugins.inventory.nb_inventory setting: group_by ", valid values are: ['sites', 'site', 'location', 'tenants', 'tenant', 'racks', 'rack', 'rack_group', 'rack_role', 'tags', 'tag', 'device_roles', 'role', 'device_types', 'device_type',
'manufacturers', 'manufacturer', 'platforms', 'platform', 'region', 'site_group', 'cluster', 'cluster_type', 'cluster_group', 'is_virtual', 'services', 'status']`

**Comment by rodvand** [comment]
This is my inventory.yml file:
```
plugin: netbox.netbox.nb_inventory
api_endpoint: MY_URL
token: MY_TOKEN
group_by:
  - cluster
```

**Comment by trapecija** [comment]
here is my inventory.yml:
`plugin: netbox.netbox.nb_inventory
api_endpoint: http://10.75.0.209:8000
token: '0123456789abcdef0123456789abcdef01234567'
validate_certs: no
config_context: True
fetch_all: True
group_by:
 - device_roles
 - platforms
 - cluster
compose:
 ansible_network_os: platform.slug
query_filters:
 - has_primary_ip: True`
 
 result:
 `{
    "ansible_host": "10.75.1.51",
    "ansible_network_os": "superserver-x11ddw-l",
    "cluster": "server01",
    "cluster_type": "lxcdocker",
    "config_context": [
        {}
    ],
    "custom_fields": {
        "Account": "-",
        "IPMI": "-",
        "Label": "-",
        "Price": "-"
    },
    "device_roles": [
        "server"
    ],
    "device_types": [
        "superchassis-815tqc-r706wb2"
    ],
    "is_virtual": false,
    "local_context_data": [
        null
    ],
    "locations": [],
    "manufacturers": [
        "supermicro"
    ],
    "platforms": [
        "superserver-x11ddw-l"
    ],
    "primary_ip4": "10.75.1.51",
    "racks": [
        "NL:AMS:DR:AMS17:Z6G:I13"
    ],
    "regions": [
        "eu"
    ],
    "services": [],
    "site_groups": [],
    "sites": [
        "site"
    ],
    "status": {
        "label": "Active",
        "value": "active"
    },
    "tags": [],
    "tenants": [
        "tenant"
    ]
}`

**Comment by rodvand** [comment]
Now you're running it with a single host, right? As your example, `ansible-inventory --host server01 -I inventory.yml`?

If you just run `ansible-inventory --list -I inventory.yml` you should get a list of the different groups created, and if you want to do something to the virtual machines on a specific cluster you can use `- hosts: cluster_server01` in your playbook. Is that anything near what you're looking for?

**Comment by trapecija** [comment]
yes, this is more that enough, thank you!
