### ISSUE TITLE
[Feature]: Add tenant option to netbox_location

### ISSUE THREAD

**Issue by jsalatiel** [netbox-community/ansible_modules#812]
### NetBox version

v3.2.5

### Feature type

Change to existing Module

### Proposed functionality

Accept the parameter tenant on the netbox.netbox.netbox_location module.

### Use case

Location should be able to be linked to a tenant like it can be done on the webinterface.

**Comment by sc68cal** [comment]
Is it `location` or is it `site`? Because at least the docs at https://docs.netbox.dev/en/stable/core-functionality/tenancy/ don't list `location` as being able to be assigned to a tenant.

**Comment by jsalatiel** [comment]
It's location. 
I always have to set manually on the webui because the module does not support it.

**Comment by jsalatiel** [comment]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/5522389/180109456-e6c8e49b-532c-4d05-9c48-572948dee7af.png">

**Comment by sc68cal** [comment]
I went and checked the [code](https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/models/sites.py#L344=) - it appears the docs are out of date. So yeah, that's fine, go ahead and add the tenant attribute

**Comment by jsalatiel** [comment]
Thank you. Hoping to see it working on next release ,:)

**Comment by sc68cal** [comment]
Do you plan on implementing this feature? It should be straight forward, since there are other objects that have the `tenant` attribute, so it should be easy to look at how it is implemented by other objects.

**Comment by jsalatiel** [comment]
Unfortunately I do not code. I hope someone else can implement that.

**Comment by rodvand** [comment]
Will be added in the next collection release.
