### ISSUE TITLE
[Feature]: Add option to mark all_in_use for the netbox_prefix module

### ISSUE THREAD

**Issue by jsalatiel** [netbox-community/ansible_modules#813]
### NetBox version

v3.2.5

### Feature type

Change to existing Module

### Proposed functionality

When creating a new prefix on the netbox webui, there is an checkbox to   Mark utilized  (Treat as 100% utilized)
Allow the netbox_prefix module set that permission on creation

### Use case

Some prefixes should be fully allocated by default.

**Comment by rodvand** [comment]
Will be included in the next release of the collection.
