### ISSUE TITLE
[Bug]: Lookup plugin crashes Python on MacBook M1

### ISSUE THREAD

**Issue by asand3r** [netbox-community/ansible_modules#816]
### Ansible NetBox Collection version

v3.7.1

### Ansible version

```bash
ansible [core 2.13.2]
  config file = None
  configured module search path = ['/Users/aahatsayuk/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/aahatsayuk/venv_ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/aahatsayuk/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/aahatsayuk/venv_ansible/bin/ansible
  python version = 3.10.5 (v3.10.5:f377153967, Jun  6 2022, 12:36:10) [Clang 13.0.0 (clang-1300.0.29.30)]
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v2.8.4

### Python version

3.10

### Steps to Reproduce

Make any simple lookup on MacBook M1.
---
- name: Check Netbox lookup plugin
  gather_facts: no
  hosts: all
  tasks:
    - name: Lookup VM in Netbox
      local_action:
        module: debug
        msg: "{{ query('netbox.netbox.nb_lookup', 'sites', api_endpoint='https://netbox.host.name', api_filter='name=site01', token='abcdef123') }}"

### Expected Behavior

Fetched Netbox data.

### Observed Behavior

TASK [Lookup VM in Netbox] *****************************************************************************************************************************
objc[29204]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[29204]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state

**Comment by asand3r** [comment]
[netbox_python_crash.txt](https://github.com/netbox-community/ansible_modules/files/9226963/netbox_python_crash.txt)

**Comment by rodvand** [comment]
Check the info box here https://netbox-ansible-collection.readthedocs.io/en/latest/getting_started/how-to-use/modules.html?highlight=Dead%20starte#modules

**Comment by asand3r** [comment]
> Check the info box here https://netbox-ansible-collection.readthedocs.io/en/latest/getting_started/how-to-use/modules.html?highlight=Dead%20starte#modules

Yeap, thanks, env no_proxy='*' works for me.
