### ISSUE TITLE
[Docs]: implicit option type netbox.netbox.netbox_vlan module

### ISSUE THREAD

**Issue by napaster** [netbox-community/ansible_modules#817]
### Change Type

Correction

### Area

Configuration parameters

### Proposed Changes

Good day. The documentation is not very clear when it is required for a vlan to specify which site to associate it with. It just has the value raw. Through testing, we managed to find out that it is required to specify what is written in the site options in the slug field. Please fix the documentation

https://docs.ansible.com/ansible/latest/collections/netbox/netbox/netbox_vlan_module.html

**Comment by rodvand** [comment]
> Please fix the documentation

Feel free to add a PR fixing the documentation.
