### ISSUE TITLE
Feature: add region to query_filter options

### ISSUE THREAD

**Issue by DavidRobbNZ** [netbox-community/ansible_modules#83]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Add region to ALLOWED_DEVICE_QUERY_PARAMETERS in the inventory plugin.

##### STEPS TO REPRODUCE
I'd like to be able to apply a query filter of "region", to provide a way to select devices across a subset of sites but without specifying them all individually. 

e.g.:

query_filters:
  - region: launchsites

rather than:

query_filters:
  - site: moon
  - site: earth
  - site: mars
  - site: neptune

##### EXPECTED RESULTS

If I add "region" to the list ALLOWED_DEVICE_QUERY_PARAMETERS in /plugins/inventory/netbox.py it works as I'd hoped.

##### ACTUAL RESULTS

Currently I get this:
```
[WARNING]: Warning: region not in ('asset_tag', 'cluster_id', 'device_type_id', 'has_primary_ip', 'is_console_server', 'is_full_depth', 'is_network_device', 'is_pdu', 'mac_address',
'manufacturer', 'manufacturer_id', 'model', 'name', 'platform', 'platform_id', 'position', 'rack_group_id', 'rack_id', 'role', 'role_id', 'serial', 'site', 'site_id', 'status', 'tag',
'tenant', 'tenant_id', 'virtual_chassis_id') or starting with cf (Custom field)
```

**Comment by FragmentedPacket** [comment]
@DavidRobbNZ I'd be fine with that. It is a possible search field for finding devices. If you want to submit a PR, we'd be willing to accept it.

It's pretty straight forward contributing to the inventory plugin since we aren't currently testing it.

**Comment by FragmentedPacket** [comment]
Do you mind testing PR #89 and letting me know if that solves your issue?
