### ISSUE TITLE
[Bug]: nb_inventory: `KeyError: 'site'` when prefix dict is returned from cache.

### ISSUE THREAD

**Issue by endreszabo** [netbox-community/ansible_modules#833]
### Ansible NetBox Collection version

v3.7.1

### Ansible version

```bash
ansible [core 2.13.3]
  config file = /home/e/.ansible.cfg
  configured module search path = ['/home/e/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/e/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
  jinja version = 3.1.2
  libyaml = True
```

Inventory plugin settings:
```
plugin: netbox.netbox.nb_inventory
api_endpoint: http://localhost:8000
token: xx
validate_certs: false
config_context: true
cache: true
cache_plugin: ansible.builtin.jsonfile
cache_connection: netbox-cache
prefixes: true
site_data: false
group_by:
  - tags
  - platforms
  - is_virtual
  - sites
  - device_roles
compose:
  last_updated: last_updated
  cluster_pinned_host: device.name
  nested_variable: rack.display_name
  region: site
```

File `ansible.cfg` has the following inventory section set:
```
[inventory]
cache_plugin=jsonfile
```

### NetBox version

v3.3.2

### Python version

3.10

### Steps to Reproduce

1. Have a prefix without a site assigned.
2. Do an inventory list using `ansible-inventory --list`.
3. Everything works fine, results are stored in the cache.
4. Do an inventory list again using `ansible-inventory --list`.
5. `KeyError: 'site'` exception ensues.

### Expected Behavior

Inventory data should be parsed equally regardless of the source of information.

### Observed Behavior

Here is the full output with verbose level 5:

```py
Loading collection netbox.netbox from /usr/lib/python3.10/site-packages/ansible_collections/netbox/netbox
Using inventory plugin 'ansible_collections.netbox.netbox.plugins.inventory.nb_inventory' to process inventory source '/home/e/ansible/inventory/30-netbox.yaml'
Exception in thread Thread-11 (wrapper):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1358, in wrapper
    raise e
  File "/usr/lib/python3.10/site-packages/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1353, in wrapper
    lookup()
  File "/usr/lib/python3.10/site-packages/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 972, in refresh_prefixes
    del prefix["site"]
KeyError: 'site'
```

Coming from the cache, that `prefix` dict has the following attributes (printed using `repr()`):
```py
{'_depth': 0, 'children': 44, 'created': '2022-09-02T01:38:41.908479Z', 'custom_fields': {'linked': {'_depth': 0, 'display': 'fd4d:4045:e5e8::/48', 'family': 6, 'id': 4, 'prefix': 'fd4d:4045:e5e8::/48', 'url': 'http://localhost:8000/api/ipam/prefixes/4/'}}, 'description': '', 'display': '44.128.0.0/16', 'family': {'label': 'IPv4', 'value': 4}, 'id': 1, 'is_pool': False, 'last_updated': '2022-09-02T14:17:26.012877Z', 'mark_utilized': False, 'prefix': '44.128.0.0/16', 'role': None, 'status': {'label': 'Container', 'value': 'container'}, 'tags': [], 'tenant': None, 'url': 'http://localhost:8000/api/ipam/prefixes/1/', 'vlan': None, 'vrf': None}
```

Without using/having the cache, it has the following attributes coming straight from NetBox:
```py
{'id': 4, 'url': 'http://localhost:8000/api/ipam/prefixes/4/', 'display': 'fd4d:4045:e5e8::/48', 'family': {'value': 6, 'label': 'IPv6'}, 'prefix': 'fd4d:4045:e5e8::/48', 'site': None, 'vrf': None, 'tenant': None, 'vlan': None, 'status': {'value': 'container', 'label': 'Container'}, 'role': None, 'is_pool': False, 'mark_utilized': False, 'description': '', 'tags': [], 'custom_fields': {'linked': {'id': 1, 'url': 'http://localhost:8000/api/ipam/prefixes/1/', 'display': '44.128.0.0/16', 'family': 4, 'prefix': '44.128.0.0/16', '_depth': 0}}, 'created': '2022-09-02T14:11:17.380170Z', 'last_updated': '2022-09-02T14:17:17.708727Z', 'children': 42, '_depth': 0}
```

When checked with bare `pynetbox` the prefix Record always has that `site: null` set.

The [problem is here](https://github.com/netbox-community/ansible_modules/blob/c2d2cd309b4a8f3bfb274c68fee7e93daea72a49/plugins/inventory/nb_inventory.py#L967):

```py
    # We are only concerned with Prefixes that have actually been assigned to sites¶
    for prefix in prefixes:¶
        print(prefix)¶
        print(repr(prefix))¶
        print(dir(prefix))¶
        if(prefix['id']==4):¶
            raise ValueError('ez itt a kert')¶
        if prefix.get("site"):¶
            self.prefixes_sites_lookup[prefix["site"]["id"]].append(prefix)¶
        # Remove "site" attribute, as it's redundant when prefixes are assigned to site¶
        del prefix["site"]¶
```

At first glance, it might look like the problem is that the `del` command is not scoped to the `if` clause, thus it runs for dicts that do not have the `site: null` attribute available. When I moved the `del` under `if`, the `ansible-inventory` apparently worked just fine, **BUT** it lacked any items in the `prefixes: []` array for any given site. So I'm quite sure this is not the way to solve this matter. As such it has a significant difference in the resulting file sizes:

```
-rw-r--r-- 1 e e  74047 Sep 19 15:13 with-cache.json
-rw-r--r-- 1 e e 355983 Sep 19 15:13 without-cache.json
```

**Comment by yaiqsa** [comment]
This problem exists in the current version with a redis cache as well 😢 

My versions:
Ansible Netbox collection: 3.19.1

```
ansible [core 2.16.9]
  config file = /home/me/src/ansible-beheer/ansible.cfg
  configured module search path = ['/home/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

Netbox: 4.0.8
Python: 3.10.12

Almost exactly the same error is thrown.

Does anyone know if there is currently any way to cache the Netbox inventory plugin?

**Comment by yaiqsa** [comment]
Okay, I've been digging though this for 3 hours in which I leaned more about Ansible caching than I was planning on, and only afterwards started modifying the code.

It appears to me that moving `del prefix["site"]` into the if statement (by indenting one level), it **does** solve the problem, and does not leave site prefixes empty 😅 

So it might have had to do with your inventory settings, or some (Included) source code changed in the meantime which fixed the problem.

I guess I'll submit a MR tomorrow, for now locally changing [line 1143](https://github.com/netbox-community/ansible_modules/blob/434baf8bc4ba897735d1cb948118301992cea00c/plugins/inventory/nb_inventory.py#L1143) by indenting it 4 spaces should fix the issue

**Comment by endreszabo** [comment]
Thanks for looking into this. I can't tell if it has been fixed meanwhile as I made my own ansible inventory module that also caches.
