### ISSUE TITLE
[Feature]: netbox plugin needs negative search

### ISSUE THREAD

**Issue by ppbrown** [netbox-community/ansible_modules#835]
### NetBox version

v3.2.5

### Feature type

Change to existing Plugin

### Proposed functionality

The netbox API supports negative searches.
For example

/api/dcim/devices/?q=&tenant_id!=3

But I dont see a way to specify that sort of thing via netbox.netbox plugin. It only seems to support inclusive search syntax?

### Use case

If you have multiple (sites or tenants), ONE of which is an internal site, and 20 are not...
It is far more efficient to ask, "show me all sites except our internal one"

Not to mention that every time you add a new external site you currently have to update all the search configs, unless you can use exclusion searches.

**Comment by ThomasADavis** [comment]
try it with 'tenant_id__n=3'

If you open the API docs, you can see all the possible search terms; they are added via a '__term' mechanism.

**Comment by ppbrown** [comment]
Oh, excellent! Thank you!

I think it would be really helpful, then, if the examples at
https://docs.ansible.com/ansible/latest/collections/netbox/netbox/nb_inventory_inventory.html

included one negative example, then.

**Comment by sc68cal** [comment]
@ppbrown If you add an example into the docs, I would be happy to approve it

**Comment by ppbrown** [comment]
how's the above?

**Comment by sc68cal** [comment]
Looks great, thank you for the contribution!
