### ISSUE TITLE
Feature: netbox_ip_address should suppoert DNS Name

### ISSUE THREAD

**Issue by pugnacity** [netbox-community/ansible_modules#84]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
netbox_ip_address should be able to set the dns_name field

**Comment by FragmentedPacket** [comment]
Are you familiar with submitting a PR?

I think this should be as easy as adding it within the argument_spec since it's just a text field.

**Comment by FragmentedPacket** [comment]
I went ahead and got a PR submitted for it. This should get merged pretty fast and then I'm waiting for two other things before I release a new version, but hopefully this weekend at the latest.
