### ISSUE TITLE
[Bug]: Unsupported media type "application/x-www-form-urlencoded" in request

### ISSUE THREAD

**Issue by kemeris2000** [netbox-community/ansible_modules#845]
### Ansible NetBox Collection version

v3.8.1

### Ansible version

```
ansible [core 2.12.8]
```

### NetBox version

v3.3.5

### Python version

3.9

### Steps to Reproduce

"{{ query('netbox.netbox.nb_lookup', 'secrets', api_filter='role=linux-user-pwd name=testuser', api_endpoint=netbox_api_endpoint, plugin='netbox_secretstore', token=netbox_api_token, private_key=netbox_vault_priv_key) }}"

### Expected Behavior

Get response. Request executed via curl client works as expected.

### Observed Behavior

msg: 'An unhandled exception occurred while running the lookup plugin ''netbox.netbox.nb_lookup''. Error was a <class ''pynetbox.core.query.RequestError''>, original message: The request failed with code 415 Unsupported Media Type: {''detail'': ''Unsupported media type "application/x-www-form-urlencoded" in request.''}. The request failed with code 415 Unsupported Media Type: {''detail'': ''Unsupported media type "application/x-www-form-urlencoded" in request.''}'

**Comment by rodvand** [comment]
Can you get this to work using pynetbox on its own?

**Comment by kemeris2000** [comment]
It's pynetbox problem.
