### ISSUE TITLE
[Feature]: Add device field to virtual_machine module

### ISSUE THREAD

**Issue by fprina** [netbox-community/ansible_modules#848]
### NetBox version

v3.3.5

### Feature type

Change to existing Module

### Proposed functionality

Since netbox v3.3.0 [a virtual machine may be assigned to a site and/or cluster](https://github.com/netbox-community/netbox/issues/5303); would be great have/manage this data also via ansible_modules

A nice to have related feature could be `vm_device` as `group_by` option

### Use case

We would like to be able to collect and assign a device to the virtual machines

**Comment by rodvand** [comment]
I've added this with #849 - you can use the devel branch if you want to test this already, or wait for our next collection release. For the group_by inventory feature, please open a new FR with some more details.
