### ISSUE TITLE
[Bug]: NetBox Inventory Fails with `object has no attribute '_vars'`

### ISSUE THREAD

**Issue by josh-silvas** [netbox-community/ansible_modules#860]
### Ansible NetBox Collection version

v3.8.1

### Ansible version

I know, we're a few releases behind ;) 

```bash
ansible 2.9.13
  config file = /local/ansible.cfg
  configured module search path = ['/home/awx/.ansible/collections/ansible_collections', '/local/plugins/modules', '/root/.ansible/collections/ansible_collections']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.14 (main, Sep  7 2022, 23:02:01) [GCC 10.2.1 20210110]

```

### NetBox version

v2.9.11

### Python version

3.9

### Steps to Reproduce

With the Ansible version and NetBox version above, attempt to list inventory data from an inventory using  plugin: "netbox.netbox.nb_inventory"

`ansible-inventory --list -i inventories/prod-inventory.yml`

### Expected Behavior

Output the results of the inventory as queried from NetBox. Downgrading to v3.8.0 fixes the issue.

### Observed Behavior

root@a4cdaeb9b3d0:/local# ansible-inventory --list -i inventories/prod-inventory.yml 
[WARNING]:  * Failed to parse /local/inventories/prod-inventory.yml with script plugin: problem running /local/inventories/prod-inventory.yml --list ([Errno 8] Exec format error: '/local/inventories/prod-
inventory.yml')
[WARNING]:  * Failed to parse /local/inventories/prod-inventory.yml with auto plugin: 'InventoryModule' object has no attribute '_vars'
[WARNING]:  * Failed to parse /local/inventories/prod-inventory.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /local/inventories/prod-inventory.yml with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.
[WARNING]: Unable to parse /local/inventories/prod-inventory.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available

**Comment by rodvand** [comment]
I suspect it's this change giving you a problem: https://github.com/netbox-community/ansible_modules/pull/834

**Comment by ane-ruiz** [comment]
Hi!

I am getting the same error, but in my case the versions are as follows:

- NetBox version: 3.3.4
- Ansible ansible-playbook version: 2.10.7
- Python version: 3.8.10

**My Observed Behaviour:**

```
[WARNING]:  * Failed to parse /var/lib/jenkins/workspace/Network
Automation/Backup Fortios/inventory_plugins/netbox_inventory.yml with auto
plugin: 'InventoryModule' object has no attribute '_vars'
  File "/usr/local/lib/python3.8/dist-packages/ansible/inventory/manager.py", line 289, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/inventory/auto.py", line 59, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/var/lib/jenkins/.ansible/collections/ansible_collections/netbox/netbox/plugins/inventory/nb_inventory.py", line 1953, in parse
    self.templar.available_variables = self._vars
[WARNING]:  * Failed to parse /var/lib/jenkins/workspace/Network
Automation/Backup Fortios/inventory_plugins/netbox_inventory.yml with yaml
plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/local/lib/python3.8/dist-packages/ansible/inventory/manager.py", line 289, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /var/lib/jenkins/workspace/Network
Automation/Backup Fortios/inventory_plugins/netbox_inventory.yml with ini
plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed,
this character is reserved to provide a port.
```

I have modified my .yml file referring to the dynamic inventory in the way indicated in @rodvand's comment, and it looks like this: 

```
plugin: netbox.netbox.nb_inventory
api_endpoint: https://XXXXXXXXXXXXXX
validate_certs: False
token: XXXXXXXXXXXXXXXXXXX
fetch_all: True
interfaces: False
config_context: False
plurals: False
group_names_raw: True
group_by:
  - role
  - site
  - tenant
  - tag
  - status
query_filters:
  - tag: "{{ com_automate }}"
  - status: "{{ active }}"
```

But I have not been able to get it to work. I still get the same error.

Currently, in the server where we have Ansible installed, the collections are in the following version:

```
Collection                      Version
------------------------------- -------
ansible.netcommon               3.0.0
ansible.posix                   1.3.0
ansible.utils                   2.6.1
ansible.windows                 1.9.0
awx.awx                         21.0.0
cisco.ios                       3.0.0
community.docker                2.4.0
community.general               4.8.0
fragmentedpacket.netbox_modules 0.1.4
netbox.netbox                   3.7.1
```

Could someone help us, please?
Thanks!!

Ane

**Comment by RomainQuinaud** [comment]
@josh-silvas @ane-ruiz 

Hi,

Disclaimer: I'm not very familiar to commenting on github so please forgive any mistakes I could perform and english is not my native language.

I had troubles too with this error and here is my setup to make this inventory work in a minimal Ansible version

As a sidenote, I've found this blog very well explained to understand the differences between the ansible, ansible-base and ansible-core packages
[https://blog.while-true-do.io/ansible-release-3-0-0/](https://blog.while-true-do.io/ansible-release-3-0-0/
)

ansible-core==2.11.1 (2.11.0 not working and the following warning was thrown)
```[WARNING]:  * Failed to parse  <MY_FILE> with ansible_collections.netbox.netbox.plugins.inventory.nb_inventory plugin: Invalid value
"['device_roles']" for configuration option "plugin_type: inventory plugin: ansible_collections.netbox.netbox.plugins.inventory.nb_inventory setting: group_by ", valid values are: ['sites', 'site', 'location',
'tenants', 'tenant', 'racks', 'rack', 'rack_group', 'rack_role', 'tags', 'tag', 'device_roles', 'role', 'device_types', 'device_type', 'manufacturers', 'manufacturer', 'platforms', 'platform', 'region',
'site_group', 'cluster', 'cluster_type', 'cluster_group', 'is_virtual', 'services', 'status', 'time_zone', 'utc_offset']
```
collection netbox.netbox==3.8.1
The following pip dependance tree (from pipdeptree package):

```shell
ansible-core==2.11.1
  - cryptography [required: Any, installed: 38.0.3]
    - cffi [required: >=1.12, installed: 1.15.1]
      - pycparser [required: Any, installed: 2.21]
  - jinja2 [required: Any, installed: 3.1.2]
    - MarkupSafe [required: >=2.0, installed: 2.1.1]
  - packaging [required: Any, installed: 21.3]
    - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
  - PyYAML [required: Any, installed: 6.0]
  - resolvelib [required: >=0.5.3,<0.6.0, installed: 0.5.4]
pip==22.0.2
pipdeptree==2.3.3
pynetbox==6.6.2
  - requests [required: >=2.20.0,<3.0, installed: 2.28.1]
    - certifi [required: >=2017.4.17, installed: 2022.9.24]
    - charset-normalizer [required: >=2,<3, installed: 2.1.1]
    - idna [required: >=2.5,<4, installed: 3.4]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.12]
  - six [required: ==1.*, installed: 1.16.0]
pytz==2022.6
setuptools==59.6.0
```
Have a nice day
Regards

**Comment by rodvand** [comment]
> 
> I have modified my .yml file referring to the dynamic inventory in the way indicated in @rodvand's comment, and it looks like this:
> 
> ```
> plugin: netbox.netbox.nb_inventory
> api_endpoint: https://XXXXXXXXXXXXXX
> validate_certs: False
> token: XXXXXXXXXXXXXXXXXXX
> fetch_all: True
> interfaces: False
> config_context: False
> plurals: False
> group_names_raw: True
> group_by:
>   - role
>   - site
>   - tenant
>   - tag
>   - status
> query_filters:
>   - tag: "{{ com_automate }}"
>   - status: "{{ active }}"
> ```
> 
> But I have not been able to get it to work. I still get the same error.

I didn't mean to suggest you should use the feature introduced by the change, but it's likely that this issue is due to the `_vars` was introduced in ansible 2.11. I'll try to push a new version soon, but until then I suggest either updating ansible to 2.11+ or downgrading the netbox collection to 3.8.0.
