### ISSUE TITLE
[Feature]: nb_inventory should return device serial number by default

### ISSUE THREAD

**Issue by mkurjanski** [netbox-community/ansible_modules#921]
### NetBox version

v3.4.0

### Feature type

Change to existing Plugin

### Proposed functionality

The Serial Number field is currently not provided by the plugin. Getting the serial number requires a dedicated lookup per each inventory host. Serial should be returned from the inventory plugin as an ansible fact/hostvar by default.

### Use case

Easier access to the serial number data.

**Comment by rodvand** [comment]
Added in collection version 3.11.0.
