### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jhofmueller** [netbox-community/ansible_modules#925]
### Ansible NetBox Collection version

v3.10.0

### Ansible version

```bash
ansible [core 2.12.8]
  config file = /home/jogi/git/dcim/netbox-dev/ansible.cfg
  configured module search path = ['/home/jogi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/jogi/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  jinja version = 3.0.3
  libyaml = True
```

### NetBox version

v3.3.6

### Python version

3.10

### Steps to Reproduce

Try to create a netbox webhook with a condition like:

  condition: '{"and": [ {"attr": "status.value", "value": "active"} ] }

on ipam.ipaddress.

### Expected Behavior

A webhook with the above specified condition should be created.

### Observed Behavior

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'conditions': ["Ruleset must be a dictionary, not <class 'str'>."]}

**Comment by sc68cal** [comment]
That change looks good to me, propose a PR and I'll 👍  it

**Comment by sc68cal** [comment]
Did they change the type for conditions in the NetBox API recently?
