### ISSUE TITLE
[Feature]: add parameter tenant to aggregate module

### ISSUE THREAD

**Issue by chuegel** [netbox-community/ansible_modules#967]
### NetBox version

v3.4.6

### Feature type

Change to existing Module

### Proposed functionality

Hi,

the existing [aggregate module](https://docs.ansible.com/ansible/latest/collections/netbox/netbox/netbox_aggregate_module.html#ansible-collections-netbox-netbox-netbox-aggregate-module) doesn't have the parameter **tentant** supported by the API in netbox 3.4.6

### Use case

We would like to add tenant specific aggregates to have a more clear separation.

**Comment by rodvand** [comment]
Will be available in the next collection release.
